### ISSUE TITLE
Local multiplayer with Gamepad on Base Version ?

### ISSUE THREAD

**Issue by HideriFN** [hmxmilohax/rock-band-3-deluxe#105]
Normally, I am playing this game with 1 or 2 more people using "Pad is Guitar" build. Since that build is not getting new update anymore, I wank to ask some questions. Is the "Base version" build support more than 1 gamepad? Because when using "Pad is Guitar" build, we just use 3 gamepad for playing multiplayer. Thanks.

**Comment by jnackmclain** [comment]
The base version allows a standard gamepad to act as a vocal player, but select any instrument. I am unsure about multiplayer with all gamepad play but that isn't a standard supported use case with how everything is laid out

**Comment by LinosM** [comment]
A bit late, but toggling "All Instruments Mode" should now allow you to use multiple pads again without the need for "Pad is Guitar" if you want to try it out.

**Comment by HideriFN** [comment]
Just plug more than 1 gamepad and turn on "All instrument mode", or maybe we need some step to do it?

**Comment by DarkRTA** [comment]
> Just plug more than 1 gamepad and turn on "All instrument mode", or maybe we need some step to do it?

its literally:
* enable all instruments mode
* connect second gamepad
* done

**Comment by LinosM** [comment]
Make sure you're on the latest version of Deluxe, this functionality was only added 2 days ago
