### ISSUE TITLE
how to create deluxe version with iso

### ISSUE THREAD

**Issue by grandosegood** [hmxmilohax/rock-band-3-deluxe#109]
hey all, i have a RB3 full iso, but am having trouble figuring out how to create the deluxe version from it. could you offer a few tips? Thanks.

**Comment by thoudankeykang** [comment]
rb3dx does not work as a custom iso instead it works as a custom update 

read the installation instructions to install

**Comment by LlysiX** [comment]
on 360, you will have to extract the iso before you can install dx, use [xisoextract](https://digiex.net/attachments/isoextract-rar.7679/)
on ps3, just paste dx files over top of the update files, don't touch the iso at all
