### ISSUE TITLE
freezing on 'manage songs'

### ISSUE THREAD

**Issue by grandosegood** [hmxmilohax/rock-band-3-deluxe#112]
hi there,
thank you for all the hard work. after building the game per the instructions for wii, i started it for the first time from usb loader gx. it started ok, asked me if i wanted to save on the SD card (i said yes), and then i went to manage songs, where it froze on the loading screen. i'm pretty sure i used the initializer correctly, could you offer any tips? thanks.

**Comment by LlysiX** [comment]
wii is no longer being supported.

**Comment by grandosegood** [comment]
thanks for the quick reply, but is there anything i could have potentially done wrong, or has this just not worked for some time?

**Comment by LlysiX** [comment]
¯\\_(ツ)_/¯
