### ISSUE TITLE
Exceeding the 3000 song limit

### ISSUE THREAD

**Issue by Deevun155** [hmxmilohax/rock-band-3-deluxe#126]
Hi there,
I'm using RB3DX on a HEN PS3 and I've exceeded the vanilla game's built in 3000 song limit. I've found that, while the game and all of the songs seem to work, I cannot add reviews for over 3000 songs. For example, I'm at 3294 songs, and when I rate all the songs and restart the game it'll say there are 294 with no review. Is this a known issue and if so is it possible for it to be fixed?

Thanks and great work on the project!

**Comment by LlysiX** [comment]
known issue, it would require changing how the save file works which is not something we can or want to do
