### ISSUE TITLE
Question: RBHP Support

### ISSUE THREAD

**Issue by wesmwitt** [hmxmilohax/rock-band-3-deluxe#13]
I was watching one of the YouTube videos for this project ( https://youtu.be/0zvLYKWUJ68 ) and It mentioned specific support for Rock Band Harmonies Project. I was wondering where I could find more information about this affects the install process.

Thanks for your hard work on this!

**Comment by jnackmclain** [comment]
Rock Band Harmonies Project's inclusion has been superseded by [RB3_plus](https://github.com/rjkiv/rb3_plus)
The inclusion brings several updates to songs, baked directly into rb3dx.
Harmonies for legacy songs, vetting and fixes for issues within RBHP, upgrades to legacy songs with additions from rb4 (added lanes), etc. See the rb3_plus github for more information.

This is included into the rb3dx base install with no change to any installation. This works with official DLC no matter the source, but you will still need to bring your own dlc.
The only things not baked directly into rb3dx at this time, are pro strings/keys upgrades, as there are additional issues that prevent this from being as seamless as the other midi upgrades talked about previously.

Over 1000 midi upgrades for songs are included in rb3dx, and are applied automatically when you build an ark using this repo.
