### ISSUE TITLE
Implement proper hi-hat pedal mode

### ISSUE THREAD

**Issue by joshuaboniface** [hmxmilohax/rock-band-3-deluxe#145]
I'm hoping that this is possible!

The quick background: I'm using a real eDrum kit to play RB3 drums, but this would apply to the original drums as well.

From my searching on the Internet so far, at some point in time, some people were able to have the Hi-Hat pedal option actually change the note of the hi-hat from Yellow to Blue. However other people say this never worked, and it only applied in fills/practice mode. Apparently this changed in *some* patch but information is spotty and anecdotal at best. I can confirm that in my version, fully up-to-date and with RB3Deluxe, the hi-hat pedal mode does *not* change the actual function during charts, and either open or closed the hi-hat triggers Yellow.

It would be a huge QoL improvement to re-implement this: while the "Hi-hat pedal" option is enabled, the hi-hat triggers a *Blue* hit, rather than a Yellow hit.

Most people in my situation work around this by outputting different MIDI events from their drum head for open/closed, but unfortunately my kit just can't do that: I'm stuck with note+CC#4 at best. And the game does recognize this, because it works in fills/before the chart begins, but having this actually work in the chart would be amazing.

**Comment by jnackmclain** [comment]
Sorry but unfortunately that's not really something we can implement
