### ISSUE TITLE
[HELP] not able to activate the animations

### ISSUE THREAD

**Issue by juanmatheus02** [hmxmilohax/rock-band-3-deluxe#148]
I am not able to activate the animations through the .bat script located in the windows.bat folder
I recorded a video showing my installation process, did I do something wrong?
[https://youtu.be/9heVQfFqCAk](https://www.youtube.com/watch?v=9heVQfFqCAk)

**Comment by lunalawl** [comment]
You need to rebuild Deluxe in order for it to take effect.

**Comment by LlysiX** [comment]
run build_ps3.bat.

**Comment by juanmatheus02** [comment]
can you guys explain to me what is the installation order to activate the animations please? I'm having a little trouble
![image](https://user-images.githubusercontent.com/130406166/231006342-77c41704-3553-4cfc-95e8-1b1d222c00cc.png)

**Comment by juanmatheus02** [comment]
hello?

**Comment by lunalawl** [comment]
Open a new command prompt and type `pip install requests`

**Comment by juanmatheus02** [comment]
Thank you so much!
