### ISSUE TITLE
 Game origin icons in the setlist 

### ISSUE THREAD

**Issue by kcpwnsgman** [hmxmilohax/rock-band-3-deluxe#158]
I got Rock Band 3 Deluxe running about a week ago on RPCS3 and noticed game origin icons on some songs like they are in RB3 Enhanced. Since then I set up RB3DX on a new windows installation with RPCS3 again, and the icons do not exist. 

Was this ever a feature rolled into Rock Band 3 Deluxe?

**Comment by lunalawl** [comment]
Game origin icons are an Enhanced feature, not sure where you saw them in Deluxe

**Comment by jnackmclain** [comment]
As above. These do not exist for Deluxe. RB3Enhanced only. And as well, RB3Enhanced is only on 360 and Wii.
