### ISSUE TITLE
author finder does not work on ps3 hardware

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#179]

**Comment by jnackmclain** [comment]
fixed with [a211bd6](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/a211bd68411e31c7758ac1b376c889d431fae54d)
aka commit 1000

**Comment by jnackmclain** [comment]
"fixed"
its less of a problem because it still doesnt work but doesnt show the debug line anymore
