### ISSUE TITLE
Arena re-loads on multiplayer after first song

### ISSUE THREAD

**Issue by kattothepast** [hmxmilohax/rock-band-3-deluxe#200]
Having an empty arena loaded only seems to work for the first song of a set when playing online MP.

**Comment by LinosM** [comment]
The host of the lobby also needs to have the empty venue set, otherwise you'll just load whatever venue the host is on after the first song,

**Comment by kattothepast** [comment]
Oh that makes sense. Thank you for the info on this, please accept my apologies for the erroneous issue thread.
