### ISSUE TITLE
Latest nightly build crashes on real PS3 hardware

### ISSUE THREAD

**Issue by Quiza3245** [hmxmilohax/rock-band-3-deluxe#224]
Latest nightly build cause crashes after selecting the instrument difficulty, with any and all songs installed through PKGs. The Rock Band 1 and the disc songs load and play fine. The Rock Band 1 songs were installed over FTP, which leads me to believe it is an issue with all PKG installed packs. 

Tested online and offline with RB2, GDRB, LRB, RB dlc packs, RB3 dlc packs, GH packs, RB4 and RB4 dlc packs, and all songs cause the PS3 to freeze after selecting the difficulty. Song previews do play and even the leaderboards load if testing online. Deleting the RB3DX config DTAs does nothing, still freezes with fresh RB3DX installs.

The log.dta included is a RB1 song being loaded, closed and then selecting a RB2 song, right before the PS3 crashed.

This does not happen with vanilla RB3 nor 1.05 official update, songs load an play just fine using those. The last working RB3DX build was from 2 or 3 week ago, but unfortunately I overwrote it with the latest and don't have it downloaded for reference.

RPCS3 does not have this issue, using the same PKGs.

Tested on PS3 slim, HFW 4.90 HEN 3.2.2
[log.zip](https://github.com/hmxmilohax/rock-band-3-deluxe/files/11901451/log.zip)

**Comment by thoudankeykang** [comment]
Do you use a special build of rb3dx? like the keys build or original mids build?

**Comment by jnackmclain** [comment]
Hi, so it seems likely you do not have multiman installed. to satisfy what rb3dx looks for, simply create a file.
dev_hdd0/game/BLES80608/USRDIR/COLOR.INI

**Comment by Quiza3245** [comment]
Used the normal build, right now I'm installing the original midis and will create the COLOR.INI file after testing the original midis

**Comment by jnackmclain** [comment]
I can def tell you all builds will fail on ps3 hw if you do not have this file on your hard drive

**Comment by Quiza3245** [comment]
I don't have the color.ini file yet, but with the "original midis" latest build the RB2, LRB, GDRB, DLCs and RB4 songs are loading fine

**Comment by jnackmclain** [comment]
well huh, that's really interesting 🤔

**Comment by Quiza3245** [comment]
After creating the color.ini file the songs are loading fine in the normal build, but it seems it's the only build that requires it as per my tests:

- UP8802-BLUS30463_00-RB3DXNITEE8F508E.pkg with no COLOR.INI crashed all PKG songs
- UP8802-BLUS30463_00-RB3DXNITEE8F508E.pkg with dev_hdd0/game/BLES80608/USRDIR/COLOR.INI everything worked
- UP8802-BLUS30463_00-RB3DXOMID2CC33BF.pkg and no COLOR.INI everything worked
- UP8802-BLUS30463_00-RB3DXKEYS20887B1.pkg and no COLOR.INI everything worked

I will leave the file in the HDD anyway and will keep using the keys builds. Thank you!

**Comment by Mitchanator099** [comment]
anybody know of a fix for this? I have a PS3 slim running 4.90 HEN 3.2.2 and every time I load a DLC song my game freezes after selecting the difficulty. I have 4000+ songs installed using the .pkg bundles. I've tried RB3DX and RB3DX keys version, both cause my game to crash after selecting a difficulty.

**Comment by jnackmclain** [comment]
@Mitchanator099 this is fixed in the develop branch and i am working hard on getting it ready to merge
https://nightly.link/hmxmilohax/rock-band-3-deluxe/workflows/build/develop

**Comment by jnackmclain** [comment]
also author finder no longer crashes ps3 hardware on the develop branch

**Comment by Mitchanator099** [comment]
> also author finder no longer crashes ps3 hardware on the develop branch

so what must I do so my game no longer crashes? @jnackmclain 

Edit: I'm gonna install what seems to be the developer version of RB3DX from the link above
