### ISSUE TITLE
Toggleable "Xbox Guitar/Drums/Keys" Modes for Controllers (player seperated)

### ISSUE THREAD

**Issue by dude98** [hmxmilohax/rock-band-3-deluxe#225]
i have a bunch of xbox rock band stuff, but a modded ps3. i want to be able to use my drums and guitars with my ps3, which i can kind of do using ps3xpad, but the gamepad bindings you guys made make it impossible to use the real instruments.
i just want a toggle for each player that enables "Xbox Guitar/Drums" in the menu that switches the bindings to be their normal ones
(A is green fret, B is red, X is blue, and so on.)

It'd be cool if you could mod in proper support for xbox guitars and drums to be seen as a guitar or drums, but that'd be incredibly difficult i think.
Keys and Pro keys could be possible too, since they use joystick axis points for what key or key combo is being pressed.

**Comment by LinosM** [comment]
>gamepad bindings you guys made

Those bindings were set by Harmonix that were leftover back in the GH2 days for gamepad play without a guitar, we simply re-enabled that ability.

>proper support for xbox guitars and drums to be seen as a guitar or drums

Due to how ps3xpad works, ANY controller that goes through it will make RB3 see it as a Vocals controller. While we can change it to act as a different instrument, it can only be one or the other, not both.

>i just want a toggle

Making it a toggle to change the bindings will crash the game which is why a separate specialized build is needed, but as I mentioned before it can be only Guitar OR Drums, but not both. We do have a version of Deluxe for Xenia on Xbox Series that forces a Pad into Guitar, but perhaps we can look into making a version for ps3 in the future.

**Comment by dude98** [comment]
having it bind as a drumset (possibly multiple drumsets enabled at once without all instrument mode enabled?) would let you use both, because the guitars need the 5 frets, dpad up/down, start and select, while drums need the right bumper for pro cymbals identifier, left stick click for secondary kick pedal, and right stick click for pro drum's pad identifier. i don't fully know how the drum velocity info works though, as i have 3 RB1 drumkits, and no RB2 or RB3 kits.

**Comment by LinosM** [comment]
Using a Drum config on Guitar would not work. RB3 uses a 2nd additional modifier, binding Up and Down dpad to the yellow and blue pad so it can differentiate hitting a Yellow Pad / Blue Cymbal and vice versa at the same time. I just tested this myself and strumming is also disabled when using a Drum config on Guitar.

**Comment by dude98** [comment]
i meant it being drums first, as in it sees the controllers as drums mainly, then you can switch to guitar, since if you were using a real xbox guitar up and down on the dpad mean nothing but strum to it, and cymbals can still work.

**Comment by LinosM** [comment]
I'm fully aware of what you mean, something like this

![1](https://i.imgur.com/wThbp37.png)
![2](https://i.imgur.com/eIVGqkQ.png)

However, the way RB3 handles bindings does not work the way you think it does

https://www.youtube.com/watch?v=lEjkxmxyp5c

**Comment by LinosM** [comment]
Try out the controller settings in the Deluxe Menu from the newest version when you can

**Comment by dude98** [comment]
that works quite well if only one person is using an xbox controller, however, the moment you have 1 person using a guitar, and another using drums it breaks due to both using the same binding set.
hopefully you guys figure out a way to have separate bindings for each controller.

**Comment by LinosM** [comment]
Unfortunately that's just a limitation of ps3xpad and not much we can do on our end. Your best option would be to look into something like Ardwiino or https://rb4.app/#!/xbox to make the ps3 see the Guitar as an actual Guitar.

**Comment by jnackmclain** [comment]
Closing this issue since Linos's new feature is awesome and allows for far more control of mapping than we have ever had before
