### ISSUE TITLE
Notes randomly getting stuck in the hit position in Practice Mode on Pro Keys when restarting

### ISSUE THREAD

**Issue by Computerdude77** [hmxmilohax/rock-band-3-deluxe#229]
When playing songs in Practice Mode on Pro Keys, notes seem to get stuck in the "hit" position randomly when restarting. I've only gotten this to occur when manually restarting, but it might happen when restarting automatically, I did not test that. The issue seems to occur when a note is being hit during the restart transition. It is interesting how the bug works too, because if you press the stuck note when a note is not there (essentially overhitting the note), the note will unstick. However, if there is an actual note there that is played, it will go back to this "stuck" position afterwards. This might be hard to explain in text, so just refer to the 2 videos below to see what exactly I am talking about. This was tested on the 59506a0-nightly, which is the most recent at the time of writing this. This was played on a real hardware on a modded Xbox 360.

Video showing the notes getting stuck, and then unstuck, using Electro Rock on the Breakin'_It_Down section:

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55714746/4fa71a44-0ab6-4ed0-aaad-86e49a3ed5f2

Video showing the notes getting stuck and remaining there when hit, using Gypsy Rave Massacre Party 2 on the Verse 3 section:

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55714746/d8cd737d-6ad1-43fe-a7f3-a237f64e48c2

**Comment by jnackmclain** [comment]
To be honest this seems like an unintended side effect of the quick practice mode restart and I am unsure if i can reset the keys back to start on quick restart. this may end up remaining. I will close this issue for now.
