### ISSUE TITLE
Question: RB4 Re-Released RBN Songs Chart Upgrades and Harmonies in RB3

### ISSUE THREAD

**Issue by DemirHerif** [hmxmilohax/rock-band-3-deluxe#23]
Some songs in RBN are re-released in RB4 and this songs has received chart upgrades. (Some songs has recieved harmony upgrades too, for example In This Moment - Mechanical Love) Maybe you can implement these upgrades to RB3 too?

**Comment by jnackmclain** [comment]
Song upgrades in rb3dx are handled by [rb3_plus](https://github.com/rjkiv/rb3_plus)
