### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by Soundtoxin** [hmxmilohax/rock-band-3-deluxe#231]
What is this project's license supposed to be? I see that the similar [RB3Enhanced](https://github.com/RBEnhanced/RB3Enhanced/) project is [GPL-2.0](https://github.com/RBEnhanced/RB3Enhanced/blob/master/LICENSE.txt). If you don't specify a license, the project would default to All Rights Reserved and users would not have the usual freedoms to use/modify it. I'm not sure if that was your intention or just an oversight.

https://choosealicense.com/

**Comment by jnackmclain** [comment]
the real answer is im bad at licensing and am not really sure what to do ngl

**Comment by jnackmclain** [comment]
i also didnt mean to close the issue
case in point lol

**Comment by Soundtoxin** [comment]
I won't tell you a particular license I think you should pick, but that site I linked might help. In addition to that, I would talk to some of your more frequent contributors and get their thoughts. I believe you're acquainted with the people of the YARG project, they may be able to give some advice on picking a license as well.
The main decision would be whether to go with a permissive license or a copyleft license. Permissive licenses allow proprietary software projects to use your code, while copyleft licenses require people to keep your software free if they use it, so then if their project built on yours it would probably have to be the same license, GPL-2.0 or whatever else. So with permissive your code could go into a Rock Band 5 game, but they might not credit you or ever contribute back. The previously mentioned GPL is a copyleft license, and a popular permissive license is the MIT license. I will say you definitely want to choose an existing license and not try to write your own. They're legally-binding, so it's best to choose something that has already had a lot of thought put into it, often from lawyers. Stuff like "do whatever you want, don't be an asshole" gets messy legally, and should be avoided.

**Comment by shny-scott** [comment]
> They're legally-binding, so it's best to choose something that has already had a lot of thought put into it, often from lawyers. Stuff like "do whatever you want, don't be an asshole" gets messy legally, and should be avoided.

This mod is already based on Harmonix scripts and binaries, which are marked in the game's credits (_ark/ui/locale/locale_credits_keep.dta line 4209) as all rights reserved. It's already been arguably illegal since day 1, if a lawyer put any amount of thought into it they'd say to shut the whole project down. Licensing the Harmonix content as anything other than all rights reserved to them should be avoided as well, so there isn't really any license that would actually work.
