### ISSUE TITLE
Discord Rich Presence closing after Pressing enter.

### ISSUE THREAD

**Issue by ghost** [hmxmilohax/rock-band-3-deluxe#233]
So,i followed all steps to use the Discord Rich Presence and when i drag the .json to the .py file and press enter it justs close it like nothing and tried a few more times and still :(

**Comment by thoudankeykang** [comment]
do you have python installed?

**Comment by ghost** [comment]
Yes i have it installed

**Comment by jnackmclain** [comment]
You were dragging the dx created discordrp.json onto the py script or the cmd window?
don't drag on top of the py file. you need to open a command prompt and run "python path/to/rock-band-3-deluxe\user_scripts/discordrichpresence.py"

**Comment by ghost** [comment]
i tried it but now i get this
[DEBUG] 2023-07-06 04:08:43,584 - JSON file path read from the text file: "D:\RPCS3\dev_hdd0\game\BLUS30463\USRDIR\discordrp.json"
[ERROR] 2023-07-06 04:08:43,585 - JSON file does not exist: "D:\RPCS3\dev_hdd0\game\BLUS30463\USRDIR\discordrp.json"

Which its very weird since the file its there lol
