### ISSUE TITLE
Remove Rock Band 3 Deluxe

### ISSUE THREAD

**Issue by Aloquendiar** [hmxmilohax/rock-band-3-deluxe#238]

**Comment by jnackmclain** [comment]
Find and reinstall the vanilla rock band 3 update pkg that matches the version number of dx to uninstall and revert to vanilla. You can find this by using the bot in the rpcs3 discord

**Comment by SArpnt** [comment]
> You can find this by using the bot in the rpcs3 discord

why does this require a discord account?

**Comment by jnackmclain** [comment]
I just dont know a better place to get a verified clean vanilla ps3 game update but via their bot. im sure you can find a 1.05 BLUS30463 update pkg elsewhere

**Comment by SlothDemon1991** [comment]
Here's a Link to a Page that have a ton of Updates for PS3 Games:
https://store.brewology.com/updates.php?letters=pqr

In that page scroll down until you see Rock Band 3 (BLUS30463) Click on it and Download the 1.05 Version.
(Been using that page for years and i havent got any problem with it)
