### ISSUE TITLE
How to disable intro skip?

### ISSUE THREAD

**Issue by AARP41298** [hmxmilohax/rock-band-3-deluxe#24]
PD thank you for the mod and the collection

**Comment by jfoshee900lbs** [comment]
I am not quite sure why you would need this, but the publisher screens are skipped via a code mod in the executable. I wouldn't know how to disable that while leaving the no checksum patch.
the intro movie and press start screen is skipped via a simple script mod. in /ui/splash/splash.dta, remove lines 18 and 19:
`   (enter
      {ui goto_screen meta_loading_main_screen})`
      and that should restore both the press start screen and the intro movie

**Comment by jnackmclain** [comment]
I am not quite sure why you would need this, but the publisher screens are skipped via a code mod in the executable. I wouldn't know how to disable that while leaving the no checksum patch.
the intro movie and press start screen is skipped via a simple script mod. in /ui/splash/splash.dta, remove lines 18 and 19:
`   (enter`
     ` {ui goto_screen meta_loading_main_screen})`
      and that should restore both the press start screen and the intro movie

**Comment by AARP41298** [comment]
I just build it, and works perfectly, thank you
The reason for that is to feel nostalgia, its a shame that the publisher screen skip cant be disable, but its ok.

Again, thank you for all your work
