### ISSUE TITLE
drum freestyles not working on keys

### ISSUE THREAD

**Issue by SArpnt** [hmxmilohax/rock-band-3-deluxe#247]
when using a keyboard, pressing buttons doesn't do anything on the drum freestyles

EDIT: a guitar controller also doesn't work (i changed the instrument type to drums to test this)

**Comment by LinosM** [comment]
It's a known issue unfortunately but for the time being you can use the auto deploy modifier

**Comment by jnackmclain** [comment]
merging Drum fills on Keys don't work #408
