### ISSUE TITLE
any controller mapped as vocals can only select vocal instruments when joining mid-song

### ISSUE THREAD

**Issue by SArpnt** [hmxmilohax/rock-band-3-deluxe#248]
when joining mid-song on a controller mapped as vocals (such as a gamepad by default), only solo and harmony can be selected from the menu shown to join mid-song

anything mapped as any other instrument works perfectly fine, and you can even map the gamepad as a different instrument and still select vocals and many other instruments from the menu

**Comment by LinosM** [comment]
This is intentional, as the game crashes when you try to drop-in as a laned instrument mid-song on the vocals controller
