### ISSUE TITLE
Jukebox mode loops when skipping song

### ISSUE THREAD

**Issue by hubjit23** [hmxmilohax/rock-band-3-deluxe#251]
Thanks for getting the Jukebox mode in, a thing I have always wanted.
I tried it with party shuffle and when skipping songs it gets stuck in a loop of results overlay and restarting the same song.
Also
on Mic ps3 controller and tried dropping out and rejoinging as guitar and then it just freezes 
Also 
is it possible to change the venue/music video when going through a set list, ie new venue every 3 songs or every song?

**Comment by jnackmclain** [comment]
On your three notes.

1. I'll look into it. It's supposed to automatically continue to the next song, but I don't think i ever tried skipping a song.

2. Yeah switching from vox to laned in the same slot mid game is unsupported unfortunately.

3. I don't believe so, as that would either need to add an additional loading screen (may or may not be possible), or cause the game to lag while it loads a new venue.
I do agree it would be nice

**Comment by LinosM** [comment]
The restart loop is still being looked into, but a new modifier has been added to change the venue after every song if you want to check it out

**Comment by hubjit23** [comment]
Godly work at the speed of sound.

**Comment by jnackmclain** [comment]
I don't know when this was fixed but it appears to no longer happen
