### ISSUE TITLE
created custom texture does not work

### ISSUE THREAD

**Issue by hubjit23** [hmxmilohax/rock-band-3-deluxe#252]
Tried to create custom texture following instructions, ran the windows highway .bat and built the PS3 files.
Texture shows up blank in menu and is just default texture in game. so i assume I did it correctly.
tried to look at what the CMD shows during the .bat processing and don't understand it.
wondering if I did anything wrong with image format or process. Attached for reference.

(yes, I am a Naruto fan)

![Akatsuki_Shade](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/130303056/b731ce0a-4867-44c3-854b-e1af87593082)

**Comment by DarkRTA** [comment]
closing this as this has been effectively fixed in `develop` by making the process less error-prone
