### ISSUE TITLE
Bass grooves textures are acting weird

### ISSUE THREAD

**Issue by rb4dlcfan** [hmxmilohax/rock-band-3-deluxe#257]
They tend to work well the first time you play a song, but if you switch styles the textures stop working correctly.

**Comment by jnackmclain** [comment]
This is known. We have no idea how to fix this unfortunately

**Comment by natalietchi** [comment]
if the problem you're having is the overdrive texture replacing the bass streak, you can get around it by not using custom overdrive textures - it's not an ideal solution but it does work. there's another workaround pinned in the rb3-deluxe channel of the milohax discord, but you have to perform that one every time you open the game

**Comment by jnackmclain** [comment]
this is now fixed
