### ISSUE TITLE
Song Upgrade Issues

### ISSUE THREAD

**Issue by CorndogWaterGrab** [hmxmilohax/rock-band-3-deluxe#275]
I just installed the latest nightly build with the key upgrades and noticed two things:

Head Over Feet by Alanis Morissette no longer has a drum part.

Tomorrow by Silverchair freezes the game during the loading screen when selecting Harmonies.

**Comment by jnackmclain** [comment]
Thanks for the note. I'll look into it when I can

**Comment by jnackmclain** [comment]
Fixed with #276
