### ISSUE TITLE
Keys Upgrade Issues

### ISSUE THREAD

**Issue by CorndogWaterGrab** [hmxmilohax/rock-band-3-deluxe#277]
I was trying out some of the new key upgrades for songs and noticed quite a few of them cause the game to crash upon selecting difficulty. Of the ones I tried the following songs resulted in a crash:

Swing, Swing
Welcome to the Black Parade
21 Guns
ABC
All Star
Aqualung
Bad Reputation
Bad Romance
Call Me When You're Sober
I'm Shipping Up to Boston
Ghostbusters
Red Barchetta

And if this is of any use, the following songs worked fine:

3's and 7's
All the Small Things
Won't Get Fooled Again
Buddy Holly

**Comment by jnackmclain** [comment]
Question do you have author finder disabled in dx/settings/appearance/hud elements/song title

And what platform is this, ps3 hardware?

**Comment by CorndogWaterGrab** [comment]
I'm on ps3 hardware, and author finder is disabled.

**Comment by jnackmclain** [comment]
Unfortunately ps3 hardware seems to be a common thread of issues recently that I haven't been able to look into yet. It is currently recommended to revert to an earlier build instead.

Apologies

Anywhere around here or before

https://github.com/hmxmilohax/rock-band-3-deluxe/actions?page=7

**Comment by jnackmclain** [comment]
I say this as, the keys aren't the problem here, something else is at play, for instance, I played aqualung with linos online in rpcs3 and it didn't crash.
I'm going to be looking into it though, the list of songs will definitely help me debug
