### ISSUE TITLE
Billy idol Rebel Yell and white wedding (part 1) freezes the game on real ps3 hardware

### ISSUE THREAD

**Issue by Mitchanator099** [hmxmilohax/rock-band-3-deluxe#283]
When browsing the songs when I hover over billy idol rebel yell and white wedding (part 1) the game freezes. I'm using the latest developer build of RB3DX as of a few days ago. Is there a fix for this or a way to remove just these 2 songs? It also happens to 1 other song that I noticed but I honestly forgot the name of the song. Money money by billy idol doesn't freeze the game but RY and WW both freeze the game.

**Comment by jnackmclain** [comment]
This is a bug with author finder I will be fixing when I can. For now turn off author finder in dx settings/ appearance/ song title/ author finder

**Comment by Mitchanator099** [comment]
> This is a bug with author finder I will be fixing when I can. For now turn off author finder in dx settings/ appearance/ song title/ author finder

I went into deluxe settings - appearance - hud elements - in game hud - song title amd turned off author finder and it still freezes on the 2 billy idol songs

I'm running RB3DX 68D875E-nightly

**Comment by jnackmclain** [comment]
You may be running an older version of dx where the toggle did not function properly. Very sorry for the inconvenience. We are working to get this fixed

**Comment by jnackmclain** [comment]
Yeah latest action build on main disabled is by default. Make sure and update

**Comment by Mitchanator099** [comment]
> Yeah latest action build on main disabled is by default. Make sure and update
Can I please get a link to the newest version of RB3DX. I'm running the developer version (I think) because the standard version caused my game to crash everytime I loaded any dlc song on my PS3. The developer version fixed this.

**Comment by jnackmclain** [comment]
Those are in the downloads section of the readme

https://github.com/hmxmilohax/rock-band-3-deluxe
