### ISSUE TITLE
Version with old icons

### ISSUE THREAD

**Issue by Aloquendiar** [hmxmilohax/rock-band-3-deluxe#288]
Since for example for PS3 and Emulator the vanilla version of the charts was removed, a version with the original Rock Band 3 icons would be a good idea.
It may be more work, but it would be an option for those who don't get the new icons

**Comment by jnackmclain** [comment]
This already exists, check the actions section for the vanilla icons builds for both platforms. It cannot be an in game toggle it must be done via a new build.

![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55568980/bb0f6916-34f5-40c8-99fc-caf488b3091b)
