### ISSUE TITLE
FC Sound not playing unless it's Guitar/Bass

### ISSUE THREAD

**Issue by wintyre01** [hmxmilohax/rock-band-3-deluxe#306]
Minor issue, but anytime I FC on drums it doesn't play the FC Sound I select (in my case I'm using the RB4 FC). Also tested with guitar, bass, and vocals. Vox has the same issue, but it has no problem playing for the other two.

**Comment by jnackmclain** [comment]
So, vocals does not currently have a proper method for checking for full combo, which results in also still having the 99% glitch
But
idk when but just checked, and drum fc sounds works properly
