### ISSUE TITLE
Can't figure out how to activate on PS3

### ISSUE THREAD

**Issue by SellyBelly** [hmxmilohax/rock-band-3-deluxe#319]
Apologies if there was somewhere better to ask this, but I installed this on my modded PS3 but it doesn't show up as its own application somewhere and simply loading the game as usual doesn't load the mod.

Am I missing something?

My apologies again, not very mod-savvy. Had only been using my modded PS3 previously for adding custom DLC to RB3.

**Comment by DarkRTA** [comment]
what steps have to tried in order to install this

we can't help you figure out what you did wrong if you dont tell us what you did in the first place

**Comment by SellyBelly** [comment]
What the instructions said to do. Figured that was implied, sorry.

Extracted the pkg to USB root, inserted it in right-hand USB port, installed. Didn't see an error message so I assume it's installed fine but I dunno how to make it work.

**Comment by lunalawl** [comment]
make sure your rb3 is BLUS30463

**Comment by LocalH** [comment]
Did you install the latest official patch before installing the RB3DX package? I don't remember if you still have to do that first or not. Edit: Apparently you do not, carry on.

**Comment by SellyBelly** [comment]
Reinstalled and working fine now. Sorry to be a bother. All good now. Thanks for the amazing mod.
