### ISSUE TITLE
RB3DX and RPCS3 Install Issue

### ISSUE THREAD

**Issue by shanmur2706** [hmxmilohax/rock-band-3-deluxe#32]
Regardless of installing the DX pack via git or the Actions zip, neither would work as intended. Downloaded correctly either way, though when extracting to dev_hdd0\disc\BLUS30463\PS3_Game, and merge the USRDIR and misc files together, the RB3 entry in the game list would disappear. 

Due to this I attempted to just extract it in different ways: gen folder only, extract DX into an empty folder. I assumed these would be completely wrong, but just in case either might work (for some reason or another).

When installing into PS3_Game like at first and manually choosing the folder to boot game from, it booted into RB3, but vanilla and without the DX's additions/changes. When I tried playing any song and it got to the cutscene, it crashed and gave this message in emu logs:

`F {PPU[0x1000000] Thread (main_thread) [0x0017ca34]} VM: Access violation reading location 0x4 (unmapped memory)
E SYS: Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x31]
E SIG: Thread [rsx::thread] is too sleepy. Waiting for it 25147.635µs already!
E SIG: Thread [rsx::thread] is too sleepy. Waiting for it 48988.497µs already!
E SIG: Thread [rsx::thread] is too sleepy. Waiting for it 96667.692µs already!`

RPCS3 Version: 0.0.23-13956-086afbba Alpha | master

Any help would be appreciated.

**Comment by jnackmclain** [comment]
to quote the readme:
"To install on rpcs3, copy all files/folders in `_build/ps3/` to /dev_hdd0/**game**/BLUS30463/"
