### ISSUE TITLE
How to display author name?

### ISSUE THREAD

**Issue by wintyre01** [hmxmilohax/rock-band-3-deluxe#336]
I noticed that for official releases, it credits Harmonix (and other RB3DX team members for keys/strings upgrades if applicable) if you enable the option to show it with the song title, but I was wondering if there's a way to show credit for other authors, such as those for RBN and customs?

**Comment by jnackmclain** [comment]
rbn would have to manually have all author information embedded which is a very large task
for customs, simply add an author array into your song
(author "author name")

**Comment by LinosM** [comment]
Regarding customs downloaded from C3:

Onyx's Quick Convert has a checkbox labeled "Author to DTA tag" which will add that for you when converting
