### ISSUE TITLE
Some upgrades are being ignored

### ISSUE THREAD

**Issue by wintyre01** [hmxmilohax/rock-band-3-deluxe#357]
So I've been experimenting with decensoring some DLC on RPCS3 (idk if it's possible to replace MOGGs on console), but I've noticed that for songs that have harmonies built in (especially Green Day) or if it's an RBN song, it'll just completely ignore changes I've made to the vocal track in the MIDI. I've been using the updates folder in _ark/songs/updates with the proper "[insert HMX ID]_update" so idk what's going on (should also note I've tried adding harmonies to some RBN 1.0 songs and have the same issue there too)

**Comment by jnackmclain** [comment]
you must also add (shortname (extra_authoring disc_update)) to the the song data, or inject (extra_authoring disc_update) into the array of the song that already exists
I believe that gdrb songs need (extra_authoring green_day) removed from their song updates data
as far as we can tell when we tried before, rbn didnt support upgrades even with the (extra_authoring disc_update) tag

**Comment by wintyre01** [comment]
I've done that too (I was just about to come back and edit to clarify that). Didn't know about that with Green Day though I'll have to see if that works. Bummer for RBN though. Maybe I'm just missing something else for the rest of it then?

**Comment by jfoshee900lbs** [comment]
I am not quite sure what else would be missing. you then rebuilt dx and copied over the new arks correct?
but also i did forget to mention, in ark mogg updates also don't work as far as we have tried either :(

**Comment by jnackmclain** [comment]
I am not quite sure what else would be missing. you then rebuilt dx and copied over the new arks correct?
but also i did forget to mention, in ark mogg updates also don't work as far as we have tried either :(

**Comment by wintyre01** [comment]
Yes I have. It's worked with almost everything pre-RB3 (DLC and on-disc for RB1 and RB2).

Side note: For MOGGs, all I've done was make a custom with the decensored audio, then renamed it to the shortname of the target song before replacing the clean one while keeping a backup in case I'm not happy with it, then delete the dummy custom I made. All done in file explorer (again, only tried this on RPCS3, don't know if such a thing's also possible on console or Xenia)
