### ISSUE TITLE
Disable BREs loads easy chart

### ISSUE THREAD

**Issue by ThePixelPolygon** [hmxmilohax/rock-band-3-deluxe#36]
Using 3DX + 3E.
I'm getting a bug where whenever "Disable BREs" is enabled, the easy chart for a song is loaded when selecting expert. In game, the 'easy' and 'expert' options are treated the same. 'Medium' and 'hard' are unaffected.

Futhermore, this bug can only be reproduced when the modifier is enabled before gameplay. Enabling it during gameplay or during practice, then restarting doesn't seem to be affected.

**Comment by jnackmclain** [comment]
good catch, I made a script adjustment that was causing failure. this will now work again properly *for one player.

Currently I am having trouble resetting multiple players difficulty, but just so you know, the workaround for disabling bre's is to set the player on easy first, then reset the song and switch the player to expert. that reset was failing in this case. Thanks!
