### ISSUE TITLE
custom solo box textures dont properly scale in multiplayer

### ISSUE THREAD

**Issue by jnackmclain** [hmxmilohax/rock-band-3-deluxe#399]
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55568980/e8319058-8083-434e-b695-a7dd7ddf522a)

**Comment by jnackmclain** [comment]
solo box sizing should also affect vox

**Comment by lunalawl** [comment]
fixed in [08012b3](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/08012b3a55d4ff94b3467425ad2bfdf7017dd7c7)
