### ISSUE TITLE
Harmony solo countdown inaccuracies

### ISSUE THREAD

**Issue by jnackmclain** [hmxmilohax/rock-band-3-deluxe#400]
When picking Harmonies in a setlist, if the first song in the set only has Solo Vocals, countdown will behave as if it's Solo Vocals for every other song in the set and vice-versa

**Comment by LinosM** [comment]
Should be fixed by https://github.com/hmxmilohax/rock-band-3-deluxe/commit/2125f6329fb8c32f2385a80c068e7270b2cf07eb
