### ISSUE TITLE
Pro-Upgrade checks

### ISSUE THREAD

**Issue by jnackmclain** [hmxmilohax/rock-band-3-deluxe#418]
You're the best Keys addition
https://discord.com/channels/961352072140324924/961395120127750204/1159969430709735424

Additional arbys 4 pro upgrade merges
https://discord.com/channels/961352072140324924/961395120127750204/1152721938561650698

seasons of wither pro upgrade
https://discord.com/channels/961352072140324924/986378977247641600/1161014409393623050

Check through RB3_Plus again

@exoticri

**Comment by exoticri** [comment]
MISSING RB3_PLUS SONGS:
YYZ

**Comment by exoticri** [comment]
https://docs.google.com/spreadsheets/d/1xuEtDNVtKxE1gsUtQLenWPCklqPyVxKv1KrWlwsvVrQ/edit add a few missing upgrades from here

**Comment by jnackmclain** [comment]
@exoticri let me know if you can get to this before 1.0 so i can close
