### ISSUE TITLE
Trainer (learn an instrument) crashes if it is the first thing entered in a session. Works if qp game is entered first

### ISSUE THREAD

**Issue by iamSynchrony** [hmxmilohax/rock-band-3-deluxe#423]
the learn a instrument trainers are showing stars , score and a broken time when they are not supposed to
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/113392466/98eae093-b234-4d48-a84e-b13352d5305c)

**Comment by jnackmclain** [comment]
Glad to see you taking an interest in learning to actually play pro guitar
Fixed as of [84b8057](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/84b8057c8967a4e896dc552a2b446423fd4ede7f)
However, I did notice trainers will crash for some reason if it is the first thing you enter on game boot. if you enter a song first in quickplay, trainer will be fine. I spent the last hour to try and find it to no avail, so I am renaming and keeping this issue for now

**Comment by jnackmclain** [comment]
Fixed with [62d5ed0](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/62d5ed0a088a5fcfb1b3b8d82773a0a6fce15be9)
