### ISSUE TITLE
bass/pro bass groove popup overwritten by 100 note streak popup

### ISSUE THREAD

**Issue by iamSynchrony** [hmxmilohax/rock-band-3-deluxe#427]
the bass/pro bass groove popup is overwritten by 100 note streak popup

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/113392466/17a8d8f2-6e26-47af-858b-d44c18d7a259

**Comment by jnackmclain** [comment]
Fixed with [6ba93c8](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/6ba93c88e05f6ed753601d133d1c46b58d115931)
