### ISSUE TITLE
Whammy FX option doesn’t seem to work

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#431]

**Comment by jnackmclain** [comment]
luna ate it
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55568980/5f5dbb4b-e2a0-4441-abe3-dc1242e9fad4)

you left curly brackets in a situation which did not need them

**Comment by jnackmclain** [comment]
fixed in [cf126d2](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/cf126d251b70e6b66aab6189555314557bf94f8f)
