### ISSUE TITLE
Note Streak turns green late and will turn green even without an FC during Road Challenges.

### ISSUE THREAD

**Issue by sourgummyes** [hmxmilohax/rock-band-3-deluxe#434]
Video of this bug in action: https://youtu.be/7ALgCwYEKV0
Second video with a MUCH shorter song, where it switched to green nearly right after I missed: https://youtu.be/MYFJFIAfvII

The streak counter also does not start on green like it should. 
Whenever a song gets to like ~3/4s of the way through the song, it'll switch the note streak counter to green, even if the run is not a full FC. It will go back to white if you miss again however.

**Comment by jnackmclain** [comment]
Fixed in [a3fafee](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/a3fafeee690827d5a8155ec505fc2637d053c454)

The "dx" note streak is not supposed to be visible in road challenges or goals
