### ISSUE TITLE
Overshell message stays stuck on player slot when resetting controller

### ISSUE THREAD

**Issue by jnackmclain** [hmxmilohax/rock-band-3-deluxe#437]
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55568980/4086d0c0-cf47-4732-b3b7-a9e399ae79f0)

**Comment by jnackmclain** [comment]
just tried a bunch of stuff again. I cannot figure out why this happens

**Comment by jnackmclain** [comment]
https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55568980/9e321108-c781-4feb-b675-c591a5106a75

video of additional problem, some states when message should be false, still remains on screen
Here, debug settings clears properly, but menu background does not

**Comment by LinosM** [comment]
Reverted controller menu back to pre-overshell rework to fix this
