### ISSUE TITLE
In-Game Customizer should select current selected quickplay instrument, rather then the default autoplay slot.

### ISSUE THREAD

**Issue by sourgummyes** [hmxmilohax/rock-band-3-deluxe#439]

**Comment by jnackmclain** [comment]
Fixed in [9a2ebd8](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/9a2ebd8ffe75a7e528f79af655c29769838698f9)
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55568980/b8f10031-0270-412a-85f5-4de35bce3d6a)
