### ISSUE TITLE
Solo bonuses worth way too much (v1.0)

### ISSUE THREAD

**Issue by Radekore** [hmxmilohax/rock-band-3-deluxe#446]
Played the RB4 Chart of "Your Love" on Release 1.0
Solo bonuses for an FC should be 3700 and 26700 for solo 1 and 2 respectively, but were actually worth 5550 and 40050 so that gave an extra 15200 points that shouldn't have existed. Reverted to previous version of the mod right after that happened so not sure if it happens on other songs or what causes it but I'd imagine it's not specific to this song since it worked completely normal after reverting.

Broken solo bonuses:
https://youtu.be/QMUYyQx-nAk

Working as intended on previous version of the mod:
https://youtu.be/tuLTb8IWR1s

**Comment by jnackmclain** [comment]
please try what i just pushed i feel really bad about this. 10-15 minutes for actions

**Comment by jnackmclain** [comment]
Confirmed fixed. Hotfix has been issued to both branches

**Comment by Radekore** [comment]
Yep, just tried the hotfix and solo bonuses were correct
