### ISSUE TITLE
Rejoining a dropped song and switching from a laned instrument to a vocal instrument results in a crash (and vice versa)

### ISSUE THREAD

**Issue by femou1** [hmxmilohax/rock-band-3-deluxe#449]
This is dependent on the slot used, as rejoining after dropping a song defaults the lane loaded to the slot you are using.
This means that if you are in the vocal slot, rejoining a song would load the vocal lanes and therefore switching to a different instrument would result in a crash.

**Comment by LinosM** [comment]
Fixed with https://github.com/hmxmilohax/rock-band-3-deluxe/pull/450
