### ISSUE TITLE
Blank "view gamer card" with os_blnk

### ISSUE THREAD

**Issue by jnackmclain** [hmxmilohax/rock-band-3-deluxe#456]
The words "view gamer card" aren't really needed, and it is visible in some cases with dx overshell. Just blank it in locale ez

**Comment by LinosM** [comment]
Closing as solved by lunalawl 

https://github.com/hmxmilohax/rock-band-3-deluxe/commit/6a98de99bb2b3eb8c986280dff2621de05372abb
