### ISSUE TITLE
disabling jurgen taunts crashes the game

### ISSUE THREAD

**Issue by SArpnt** [hmxmilohax/rock-band-3-deluxe#461]
if i disable it in the menu ingame it crashes instantly, if i disable it in the settings i can't access the audio & sfx menu

**Comment by jnackmclain** [comment]
Try latest develop branch build from here and report back

https://nightly.link/hmxmilohax/rock-band-3-deluxe/workflows/build/develop

**Comment by SArpnt** [comment]
dev build works fine. a hotfix would be nice if there won't be a new release soon though

also i think there's a way to add instructions when people submit issues on github, i don't remember how. but it would be good to give a link to the dev builds so you could ask to test with it. i thought about testing on a dev build before i submitted the issue but didn't know where to find them

**Comment by LinosM** [comment]
Closing if this solved now
