### ISSUE TITLE
Multiplier pie watermark not set correctly if using default RB3 ring.

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#469]
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/37005649/f818de25-28bc-4fce-ad80-66c16f5794e3)

**Comment by DarkRTA** [comment]
This bug is also making it possible to go into autoplay without setting the watermark for the ring.

```
from a fresh boot with default track theme:
* go into a song
* go back to menu
* turn on autoplay
* go back into song
* multiplier ring will be missing a watermark
```

**Comment by DarkRTA** [comment]
is this still an issue

im pretty sure this got fixed at one point
