### ISSUE TITLE
Song transitions are extremely laggy on 360hw

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#493]

**Comment by qfoxb** [comment]
This was introduced with the rpcs3 practice mode crash fix iirc

**Comment by SasafrassRoot** [comment]
Completely turning off transitions causes the game to crash before a song starts on PS3 HW. The loading icon with its splash doesn't appear anymore (when starting a song).

**Comment by pokeyjojo** [comment]
Was there a fix for this ever? I’m on latest nightly and have the same issue. If I remove the rpcs3 practice mode fix because I’m on 360 HW would that work?

**Comment by jnackmclain** [comment]
this has not been fixed and it has not been looked into what cases it to recommend a manual fix

**Comment by DarkRTA** [comment]
we made a workaround for this. can we go ahead and close this or should we leave it open until we get a proper fix

**Comment by jnackmclain** [comment]
Close. The fix is good enough. Luna made loading tips only show on Xbox if song transitions are off. Perfectly acceptable, especially since we don't add the extra loading delay on 360
