### ISSUE TITLE
Postproc menu randomly goes back to the previous state

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#494]
(no button was pressed at 0:11 in the video)
https://github.com/hmxmilohax/rock-band-3-deluxe/assets/37005649/bd1919de-89c6-4b41-b267-5a1856c8218b

**Comment by lunalawl** [comment]
adding to this, some other states do this too, mainly the menu bg submenus

**Comment by jnackmclain** [comment]
Yeah I've noticed a bunch of vignettes don't have their post proc removed

**Comment by jnackmclain** [comment]
this should be fixed in latest, reopen if not
