### ISSUE TITLE
[FR] Basic Websocket/HTTP interface for Song Search and Queuing 

### ISSUE THREAD

**Issue by aenertia** [hmxmilohax/rock-band-3-deluxe#498]
One of the biggest problems when using rb3dx with a large library is being able to search and queue setlist/songs whilst people are playing.

Exposing a basic websocket/API rest endpoint and ideally basic JavaScript Search/Filter to enable spectators to find and ideally queue songs for karaoke or party play would be ideal.

Am not sure if this is feasible or would require a locally hosted ash central instance running on the local network to provide similar functionality but especially with large song libraries this is a must have.

**Comment by jnackmclain** [comment]
We do not have the capacity to make this feature, but I believe something like this in some form, perhaps not all requested features, exists in RB3Enhanced. This is however only available on Xbox 360 at this time.

https://github.com/RBEnhanced/RB3Enhanced
