### ISSUE TITLE
Consider having Rust as a build-time dependency.

### ISSUE THREAD

**Issue by DarkRTA** [hmxmilohax/rock-band-3-deluxe#499]
With the new tools repo having a heavy focus on Rust, it may be worth building that from source instead of shipping binaries in the repo.

My eventual goal is to replace all of our existing python scripts with rust tools so we would eventually be dropping python as a dependency entirely.

**Comment by jnackmclain** [comment]
@DarkRTA any progress on this? :konky:

**Comment by DarkRTA** [comment]
"needs further discussion"

**Comment by jnackmclain** [comment]
closing this for now
