### ISSUE TITLE
Can't Save Xbox 360

### ISSUE THREAD

**Issue by pmuscle** [hmxmilohax/rock-band-3-deluxe#516]
Hi Friends!

I installed RB3 deluxe on my 360 but the game wont save. When I boot the game this warning message was displayed informing to change a option on Xenia , I guess the emulator, but what i can do to fix this on original hardware?
![a57264a5-cbb8-4c76-86a8-b1e13f55d998](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/155319937/e621ffb1-4191-4776-85df-62ac2fb1b41f)

thanks in advance for any help.

**Comment by jnackmclain** [comment]
are you running the game via a GoD version or extracted?

**Comment by pmuscle** [comment]
GOD version

**Comment by jnackmclain** [comment]
That's why, GoD version is a complete container that does not allow saving of loose text files dx generates to store dx settings and such.
Only extracted is supported for full dx setting saving

**Comment by pmuscle** [comment]
Ok, thanks for the explanation! If I upload the extracted version in the same folder the game will read the DLCs ? 

Thanks again!

**Comment by jnackmclain** [comment]
yes

**Comment by andrewwfesenko** [comment]
Hi everyone, I'm having the exact same error while playing on my PS3 which is weird 😬
Any ideas on how to fix it?

**Comment by DarkRTA** [comment]
please make a new bug report instead of commenting on a really old issue
