### ISSUE TITLE
Manual Calibration Unable to "get an accurate reading" in RB2DX & RB3DX

### ISSUE THREAD

**Issue by KaijuChomps** [hmxmilohax/rock-band-3-deluxe#532]
I’ve identified a potential cause for the calibration error in RB2DX and RB3DX, where the calibration bar advances too quickly, resulting in the message “Sorry, we couldn’t get an accurate reading from your results. Please try again!” This issue doesn’t occur in Rock Band 2 or 3 vanilla.

The problem seems to arise when the user holds the strum bar (or X button on gamepads) in place during calibration, rather than releasing it immediately. For instance, during audio calibration, if the user strums down on the tick, holds it, and then snaps into the next position on the following tick, the calibration bar advances too quickly.

I have a feeling that the DX builds are continuously checking for inputs even after receiving an input for a given metronome tick, which is not how the original games work.

To better illustrate this issue, I’ve recorded two videos and uploaded them to an unlisted YouTube playlist. The first video shows the issue in RB2/3DX and the workaround, while the second video shows the calibration system functioning correctly with both strumming methods.

[Here is the link to the videos.](https://www.youtube.com/playlist?list=PLH_Y6eBFVjo9ZZb2RPsMTvylaWxQ9Z0Kb)

I hope the videos clearly demonstrate the issue, 

[edit: just to mention this has only been tested on RPCS3, i have no idea if PS3 hardware nor the 360 builds exhibit this behaviour]

**Comment by DarkRTA** [comment]
This is unfortunately not something we are able to fix without some serious code mods, which are currently out of scope for DX.
