### ISSUE TITLE
Implement an "always play crowd track" option?

### ISSUE THREAD

**Issue by coxymla** [hmxmilohax/rock-band-3-deluxe#553]
I love the crowd noise (singalong, clapping, etc.) and get annoyed when I drop combo and it abruptly cuts out.
If there was an option to just always play it no matter how badly you're doing, that would be ideal.

**Comment by jnackmclain** [comment]
I went looking for this
The issue is two fold, mute_volume in game can be overridden by songs.dta, and also doesnt get reenumerated after use.
So unfortunately, this is not possible with current knowledge

**Comment by LinosM** [comment]
The crowd track will always play now when you disable the crowd meter in deluxe settings
