### ISSUE TITLE
Where's the toggle camera feature??

### ISSUE THREAD

**Issue by wintyre01** [hmxmilohax/rock-band-3-deluxe#555]
Just upgraded to the most recent version of the beta and noticed the toggle camera feature is missing. Was hoping to keep using to test custom lipsync files up close

**Comment by DarkRTA** [comment]
do you have autoplay enabled?

that option is gated behind it assuming nobody accidentially removed it during a refactor

**Comment by wintyre01** [comment]
Yeah. Went and double-checked. Nothing :(

**Comment by DarkRTA** [comment]
its in extras instead of deluxe settings or some other menu for whatever reason

should probably move it

**Comment by DarkRTA** [comment]
apparently the option is straight up just broken right now
see #556
