### ISSUE TITLE
Cycle Camera is broken.

### ISSUE THREAD

**Issue by DarkRTA** [hmxmilohax/rock-band-3-deluxe#556]
It doesn't actually seem to cycle the camera right now, but instead just locks it in place.

**Comment by wintyre01** [comment]
I was able to find the option. Thank you. And that's weird. It's working fine on my end. I did notice in dx_camera_funcs.dta that there were comments and I ended up replacing that with an old version without those (checked if they had the same amount of lines before). I also did that out of frustration trying to figure out where the cycle camera option was before submitting #555 so don't take my word for it I'm not sure if that actually fixed anything.

**Comment by jnackmclain** [comment]
Cycle camera is not broken. you must press it multiple times to change the camera to the different positions

**Comment by DarkRTA** [comment]
I was being gaslit by the game because all of a sudden it works for me now.
