### ISSUE TITLE
Solo box scaling sometimes resets

### ISSUE THREAD

**Issue by jnackmclain** [hmxmilohax/rock-band-3-deluxe#559]
Noticed that when switching back to strings after restarting in practice or playing vox, the solo box scaling resets to how it is for the rb3/vocals box

https://cdn.discordapp.com/attachments/1214979344162750524/1214979344632516638/image.png?ex=65fb14b0&is=65e89fb0&hm=1516fcfcd2649c0fa3f9be1a9092e72c2e4e50b74ce373d7b36c185c1f7be14d&

**Comment by lunalawl** [comment]
fixed in [08012b3](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/08012b3a55d4ff94b3467425ad2bfdf7017dd7c7)
