### ISSUE TITLE
Disallow song speed changing mid-song (again)

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#564]
This was previously done before the overshell redesign but i left it out as i couldn't get it working properly for whatever reason

**Comment by DarkRTA** [comment]
Song speed is only updated on restart now unless something is broken

**Comment by jnackmclain** [comment]
this is no longer a bug

**Comment by jnackmclain** [comment]
fixed (again) with f789bba14c1ad4a02d9fd479fc5caee6deeb76a8
