### ISSUE TITLE
Enhancement: Auto kick back port, is this possible?

### ISSUE THREAD

**Issue by pokeyjojo** [hmxmilohax/rock-band-3-deluxe#566]
Hello! Really wanting some way to turn off the foot pedal. Wondering if RB3 deluxe could do something like that? I didn’t see it in the feature list. I’d try to add it myself but I’m not smart lmao

**Comment by LinosM** [comment]
You can turn on Auto Kick in the modifiers

**Comment by pokeyjojo** [comment]
I had no idea since it wasn’t in the features list and I was debating whether to find a modded 360. Thank you so much!
