### ISSUE TITLE
Does RB3 Deluxe work with customs? 

### ISSUE THREAD

**Issue by pokeyjojo** [hmxmilohax/rock-band-3-deluxe#568]
Trying to get customs running and I’m a little concerned because the website says 
“ Disable any title updates you may have for Rock Band 3 in Aurora.
Rock Band 3 Deluxe rolls the latest one into its installation.” 

the guide I’m following says to make sure your on title update 4. Will customs work or is there some other guide?
Thanks

**Comment by LlysiX** [comment]
Customs will work with Rock Band 3 Deluxe.
