### ISSUE TITLE
No Menu BGs breaks going into anything

### ISSUE THREAD

**Issue by exoticri** [hmxmilohax/rock-band-3-deluxe#57]
When I select the no menu bgs modifier and then try going into quick play or select an RB3DX modifier everything but my band info disappears and I can't do anything

**Comment by jnackmclain** [comment]
fixed with [839dda0](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/839dda0a79ac68705668d7ba5063c3576663e2a4)
