### ISSUE TITLE
Enhancement: Make modifiers save so you don’t have to re enable them every time you boot up the game

### ISSUE THREAD

**Issue by pokeyjojo** [hmxmilohax/rock-band-3-deluxe#573]
This could probably be done by like writing them to the same file as the deluxe settings, I’d love for this to be implemented because it’s annoying to re enable modifiers every time

**Comment by jnackmclain** [comment]
This already exists and is part of the game there should be a dx_modifiers.dta in the same location

**Comment by pokeyjojo** [comment]
Oh weird, is there something you have to do to enable it? It’s not working currently

**Comment by jnackmclain** [comment]
No it should just work. have you looked for that file to see it's contents? it works fine for me

**Comment by jnackmclain** [comment]
also just to confirm, this does not work on wii

**Comment by pokeyjojo** [comment]
I’m on 360, I’ll check the contents of the file in a sec

**Comment by jnackmclain** [comment]
You are not using a GoD version of the game correct? I just tested in xenia and rpcs3 and both are working fine

**Comment by pokeyjojo** [comment]
I think the issue is the file does not have the modifier that i'm trying to save (auto-kick), my file looks like this 


`(mod_doublespeed
   (mod_doublespeed 0)
)
(mod_static_fills
   (mod_static_fills 0)
)
(mod_chord_numbers
   (mod_chord_numbers 0)
)
(mod_nohud
   (mod_nohud 0)
)
(mod_miss_sounds
   (mod_miss_sounds 0)
)
(mod_remote_texture_sync
   (mod_remote_texture_sync 0)
)
(mod_practiceoverdrive
   (mod_practiceoverdrive 0)
)
(mod_nolanes
   (mod_nolanes 0)
)
(mod_rb4lanes
   (mod_rb4lanes 1)
)
(mod_synced_track_speeds
   (mod_synced_track_speeds 0)
)
(mod_nopause
   (mod_nopause 1)
)
(mod_dx_no_overdrive
   (mod_dx_no_overdrive 0)
)
(mod_mhx_color_shuffle
   (mod_mhx_color_shuffle 0)
)
`

**Comment by pokeyjojo** [comment]
how could i add this to that file?

**Comment by jnackmclain** [comment]
that is intentional
Auto kick disables saving, just like autoplay
So it intentionally removed from saving and loading the modifier file
Sorry about that, but this will not be included

**Comment by pokeyjojo** [comment]
I see, thanks for your help!

**Comment by pokeyjojo** [comment]
Know this is closed but for anyone else that wants to do this (since it won't be offically added)



following the building instructions to get the source code of RB3DX

navigate to `_ark/dx/read_write/dx_writer_macros.dta` and open it in an IDE (like vscode, you could also use notepad if you don't have an IDE)
above or below line 218 (which is `{dx_setting_saver dx_modifiers mod_mhx_color_shuffle {modifier_mgr is_modifier_active mod_mhx_color_shuffle}}`) add the line `{dx_setting_saver dx_modifiers mod_auto_kick {modifier_mgr is_modifier_active mod_auto_kick}}` and save the file


then navigate to `_ark/dx/read_write/dx_read_write_funcs.dta` and open it in an IDE (like vscode, you could also use notepad if you don't have an IDE)
above or below line 128(which is `{dx_modifier_reader mod_remote_texture_sync}`) add this line `{dx_modifier_reader mod_auto_kick}`  and save the file

use the building instructions  to build the game for your platform and copy it over to your device and follow the installation guide, then run the game to create a dx_modifiers.dta file if you don't have one already 
then in your dx_modifiers.dta (on the root of your game installation after you run the game) add this at the bottom (below the perentheses for `mod_mhx_color_shuffle`

(mod_auto_kick
   (mod_auto_kick 1)

) 

 (only tested this for xbox but it should work on PS3, DOESNT WORK ON WII)


you can follow this same process but replacing mod_auto_kick with mod_auto_play if you wish to have the autoplay modifier status save accros boots as well, hope this helps someone else out!
