### ISSUE TITLE
Crashing when going into main menu

### ISSUE THREAD

**Issue by KingDamienHamster-kun** [hmxmilohax/rock-band-3-deluxe#574]
After playing a set in Quickplay or Road Challenges, going back to the main menu causes a crash.

Console: PS3 Hardware
Nightly version: 52efe88

**Comment by DarkRTA** [comment]
Can we get steps to reproduce this along with any settings you may have.

**Comment by KingDamienHamster-kun** [comment]
No problem.

Go into Quickplay or Road Challenges
Play a setlist (one song might also work)
Exit to the main menu
*crash*

**Comment by DarkRTA** [comment]
I still can't reproduce this. Can you post your settings.

**Comment by KingDamienHamster-kun** [comment]
Not sure how to attach files, so here it is in text.

[Maintainer Edit: Removed dx_settings.dta spam]

Could also be caused by remapping pad controls, not sure.

**Comment by DarkRTA** [comment]
this is worse than attaching it. use this button that's located below the text field:
![Screenshot_2024-03-15_20-19-36](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/15368682/b91f7aa6-5d32-4ab2-b0dd-7e79c4dcf38c)

**Comment by KingDamienHamster-kun** [comment]
![dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14621765/dx_settings.txt)
