### ISSUE TITLE
Search bar for menu screen and/ or favorite songs 

### ISSUE THREAD

**Issue by pokeyjojo** [hmxmilohax/rock-band-3-deluxe#575]
I have a big song library and was amazed to find no way to set a song as a favorite and only show favorited songs? So I’d like to request either a search bar to search for songs to easily pick from a big list or be able to set a song as a favorite to filter the list. Wondering if this is even feasible?

**Comment by LinosM** [comment]
You can use the lighter/review system to mark songs you want as favorites (a vanilla feature) and sort by them.

Nautilus has a setlist manager that can read your rb3 library which you can use to search though
https://github.com/trojannemo/Nautilus

**Comment by DarkRTA** [comment]
A search feature isn't possible within the scope of RB3DX. As Linos mentioned, you can use the vanilla lighter rating system to rate songs and filter for them in your library.

**Comment by movy** [comment]
Sorry for "re-opening", but I am also struggling with a large songs library, and I think remembering last chosen sort order would be helpful (if possible within RB3DX scope of course).. 
Basically, if I sort the songlist by Artist, then closing and re-opening rpcs3/RB3DX would still keep this sort order. It would greatly help with MIDI drums, as using combos to press Select, get into sorting menu etc. gets annoying fast. 

As for favorites, there's an option to sort by Plays (or Stars, can't remember exactly), which hoists already played songs to the top of the list, keeping the rest in ABС order, and this is good enough to keep "favorites" within easy reach.

**Comment by DarkRTA** [comment]
please open a new issue for this instead of spamming an unrelated issue that was closed
