### ISSUE TITLE
Tie brutal mode to the crowd meter.

### ISSUE THREAD

**Issue by DarkRTA** [hmxmilohax/rock-band-3-deluxe#577]
This is actually how it behaves in RB4 and for accuracy reasons we should try and mimic that.

**Comment by LocalH** [comment]
I have this partially implemented. I need to finetune the positions based on a video of RB4 that jnack provided to me, and I'd like to 1) make some sort of visual indicator as to the position of the brutal cutoff, and 2) fafo and see if there's any way to stop hit sustains from reaching up to the bottom_y position.

**Comment by LocalH** [comment]
This is mostly done (1 is done, 2 not yet). Once I have adjusted the positions to better match RB4, I will close this issue.

**Comment by LocalH** [comment]
Forgot to close this issue with the release of the updated brutal mode. Rectifying that now.
