### ISSUE TITLE
Animations not working on Xbox

### ISSUE THREAD

**Issue by pul53gh** [hmxmilohax/rock-band-3-deluxe#59]
Trying to enable animated textures doesn't work for me

After running enable_animations.bat 
and setting these settings in init.dta:
![image](https://user-images.githubusercontent.com/75389344/193426677-7bc65968-537d-4157-9457-5d01f5f566e7.png)

This will happen:
![image](https://user-images.githubusercontent.com/75389344/193426750-0cc3ac98-8b65-4a23-a5c2-5505585b5d9b.png)

The screenshot isn't great but basically all the gem textures look glitched af and the highway doesn't load.

**Comment by jnackmclain** [comment]
Your init.dta and likely your build is highly out of date based on that screenshot. Make sure and update your local copy, if needed re do with init_repo.bay from the releases page.

**Comment by pul53gh** [comment]
> Your init.dta and likely your build is highly out of date based on that screenshot. Make sure and update your local copy, if needed re do with init_repo.bay from the releases page.

Yep, init.dta was preventing the merge. Ty!
