### ISSUE TITLE
Performance Mode & Autoplay crash

### ISSUE THREAD

**Issue by Cloudsify** [hmxmilohax/rock-band-3-deluxe#590]
**Describe the bug**
Game crashes when entering performance mode + autoplay and when picking a song it crashes loading the instrument overshell on Xbox 360

**To Reproduce**
1. Enable Performance Mode & Autoplay
2. Pick a song and go to select an instrument

**Expected behavior**
Shouldn't crash and I should be able to load into a venue

**DX Settings**
[dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14733597/dx_modifiers.txt)
[dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14733598/dx_settings.txt)
[dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14733599/dx_values.txt)

**Game Information**
 - Platform: Xbox 360
 - Version: (https://github.com/hmxmilohax/rock-band-3-deluxe/commit/5350286e8db442c9bf247e2b600285e8130da770)
 - Song Count: 5566

**Comment by DarkRTA** [comment]
seems to be related to #587 

song count is also pretty high for xbox 360 which makes is a bit suspect

**Comment by Cloudsify** [comment]
> seems to be related to #587
> 
> song count is also pretty high for xbox 360 which makes is a bit suspect

Never really had an issue with the song count tbh. I've had it higher and it's ran smoothly but I deleted a couple packs cause I didn't like them.

**Comment by jnackmclain** [comment]
I don't think this is a song count issue. I recently ish fixed an issue where jukebox mode was also crashing
There is likely some handle call that needs to be gated behind performance mode as well

**Comment by jnackmclain** [comment]
@knvtva try jukebox mode instead of performance + autoplay

**Comment by DarkRTA** [comment]
jukebox mode still has the crash

**Comment by DarkRTA** [comment]
we found the cause. the game doesn't like us trying to set certain textures in performance mode
