### ISSUE TITLE
Overshell color does not set immediately on Xbox if you're joining and already signed into a profile

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#595]
**Describe the bug**
Overshell color does not set immediately on Xbox if you're joining and already signed into a profile

**To Reproduce**
1. Sign into a profile before launching the game (xbox live or liveless)
2. Join

**Expected behavior**
Overshell color is supposed to set based on saved settings

**Screenshots**
Before opening overshell to set the color
![IMG_0435](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/37005649/67e7efc2-9653-4b29-af12-f9381f719ae9)
after
![IMG_0436](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/37005649/ea664278-b87f-470d-a206-067501d38c51)

**DX Settings**
- [dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14736887/dx_settings.txt)
- [dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14736888/dx_modifiers.txt)
- [dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14736889/dx_values.txt)

**Game Information**
 - Platform: Xbox 360
 - Version: 1.1.0-nightly+8bdb4a0
 - Song Count: 4922

**Additional context**
The color sets on PS3 and if you aren't signed into a profile because a state always appears on join, when you're already signed into a profile on Xbox it just joins you in

**Comment by jnackmclain** [comment]
probably fixed with 90f21ad55d9199e239627aac0b7067b959b57f54
the strip is really annoying
