### ISSUE TITLE
Song won't end - game locks up and loops - audio still plays and menus are functional

### ISSUE THREAD

**Issue by Weenus420** [hmxmilohax/rock-band-3-deluxe#596]
**Describe the bug**
At the end of the song the game freezes, audio still playing and drums still functional, able to press start button and restart the song. The song was Michelle by The Beatles, gotten from the meats. The song timer in the top right keeps going down to 0:00 and then resetting to 0:02.

Important to note I'm one of the few with the midi drums RPCS3 e-kit scripts (or however you call them)

**To Reproduce**
bug found on a setlist for road challenges but replicated 100% on quickplay, play Michelle on expert drums (also on pro drums), at the end it gets stuck in an infinite loop. 

**Expected behavior**
Like a normal song ending, to go to the third and final song in the setlist.

**Screenshots**
Attached a short video displaying the bug.

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/129349743/18e11be0-d867-4d97-ae55-1d4e17b6375b

**DX Settings**
[dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14737741/dx_settings.txt)
[dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14737742/dx_modifiers.txt)
[dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14737740/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-nightly+fe51bcb
 - Song Count: 4805

**Additional context**
marty20k on discord if you need me to do extra testing.

**Comment by jnackmclain** [comment]
The Beatles pack is known to have loop bug issues. This is a customs issue, not a DX issue.
delete the pack you have and install this one https://keepitfishy.com/tbrb/
or this one https://drive.google.com/file/d/1ieQSCVeOw3WSNg8fxf0JZCxx0pzltPqw/view?usp=drivesdk
