### ISSUE TITLE
Invisible colour values that potentially goes as low as -4%

### ISSUE THREAD

**Issue by WarGod480** [hmxmilohax/rock-band-3-deluxe#600]
**Describe the bug(s)**
When trying to change the green or blue values of the colour settings, the entire value display disappears, hindering you from seeing what value you put in, as opposed to the red value, that stays visible when selected.

A second issue is that you can put the colour values to -4%

**To Reproduce**
1. Go to Options -> Deluxe Settings -> Advanced -> Menu options -> Color
2. Scroll down to and click either the Green or Blue value

As for the "-4%" bug, if the Green or Blue value starts lower than '100%' and gets decreased (towards 0%) there is a chance that it goes to -4%.
**NOTE:** This is not replicated 100% of the time

**Expected behavior**
All colour values should be visible at all times when adjusting, and it should not go below -4%

**Video**
https://github.com/hmxmilohax/rock-band-3-deluxe/assets/123154581/fc8bf40e-eb5a-4382-a316-05f617c2e928

**DX Settings**
- [dx_settings.txt] (https://github.com/hmxmilohax/rock-band-3-deluxe/files/14781121/dx_settings.txt)
- [dx_modifiers.txt] (https://github.com/hmxmilohax/rock-band-3-deluxe/files/14781124/dx_modifiers.txt)
- [dx_values.txt] (https://github.com/hmxmilohax/rock-band-3-deluxe/files/14781129/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-nightly+b9ee02d
 - Song Count: 5141

**Additional context**
This my first post, please be nice and no bully ^^

**Comment by DarkRTA** [comment]
> This my first post, please be nice and no bully ^^

<img width="128" alt="out" src="https://github.com/hmxmilohax/rock-band-3-deluxe/assets/15368682/2019e1cb-e2b8-4367-8e07-49b3ac25be05">

**Comment by WarGod480** [comment]
![sadge](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/123154581/b7cf16ed-7e9e-4960-b1aa-90bda32c6d18)

**Comment by jnackmclain** [comment]
fixed with 13c789eba4454349dbb9317b3c365d2cac32c320
