### ISSUE TITLE
Refreshing options on play a show causes a crash (Xbox)

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#605]
**To Reproduce**
1. Go to 'Play A Show'
2. Click on 'Vote 5. (Refresh Options)'

**Expected behavior**
Refreshes play a show options

**DX Settings**
- [dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14808978/dx_settings.txt)
- [dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14808979/dx_modifiers.txt)
- [dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14808980/dx_values.txt)

- [playashow.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14808981/playashow.txt)

**Game Information**
 - Platform: Xbox 360
 - Version: 1.1.0-nightly+191cb61
 - Song Count: 4922

**Comment by DarkRTA** [comment]
Probably not an issue anymore.
