### ISSUE TITLE
Play A Show does not allow disc songs to be played (PS3/RPCS3)

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#606]
**Describe the bug**
Play A Show only scans for DLC, and does not look for disc songs, if no DLC is installed it just displays "no songs found"

**Expected behavior**
Disc songs appear in Play A Show

**Game Information**
 - Platform: RPCS3
 - Song Count: 85

**Comment by DarkRTA** [comment]
No longer an issue.
