### ISSUE TITLE
Goal popups and DX setting descriptions don't show up on Wii

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#607]
**Describe the bug**
When you complete a goal, the sound plays but the popup thing doesn't appear, and when you open Deluxe Settings, there are no descriptions

**Expected behavior**
Goal popups show up when you complete a goal, DX setting descriptions show up when you hover over a setting in Deluxe Settings

**Screenshots**
https://github.com/hmxmilohax/rock-band-3-deluxe/assets/37005649/ab844d01-6632-401e-886c-c8ad230a2320

**DX Settings**
(n/a)

**Game Information**
 - Platform: Wii
 - Version: 1.1.0-nightly+[83db5a9](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/83db5a96c0914d6aaedd6530e563d0122a1e2cab)
 - Song Count: 83

**Additional context**
they work on every other platform lawl

**Comment by jnackmclain** [comment]
fixed with ffacf0a0ae221592a22026bbd7cf11be854dcca5
