### ISSUE TITLE
When using only microphone in song list on WII the button 2 is no longer accesible this should show the alphabet in the song list screen

### ISSUE THREAD

**Issue by slaan1974** [hmxmilohax/rock-band-3-deluxe#609]
**Describe the bug**
In the previous version which i used which was 1.0.8 we where able to use the 2 button to show the alphabet list, this is handy when you have a large list of songs, but this seems no longer working in 1.1.0 beta5

**To Reproduce**
1. Go to 'RB3 deluxe 1.10 beta5' , follow opening screen , press + to select only microphone user, now navigate to list of songs, when in list of songs you should be able to press 2 to get alphabet list in screen, this is no longer working on WII
No error displays just nothing, now you have to navigate with right/left through the list of songs

**Expected behavior**
This was a handy feature previously especially when you have a large list of songs

So when you attach a guitar , the purple/orange button works, so you get the alphabet, the feature itself does still exist in the software

 - Song Count: 2493

**Additional context**

**Comment by jnackmclain** [comment]
fixed with a5f25c0eed6033bab62523fa62c2cbb54a1efd6e
