### ISSUE TITLE
Opening screen on WII stays black

### ISSUE THREAD

**Issue by slaan1974** [hmxmilohax/rock-band-3-deluxe#610]
**Describe the bug**
When you load the RB3 deluxe 1.1.0 beta5 it is asked to save content on SD, you then press YES, after this you will expect the normal opening screen. This is not shown, so it shows in the upper right corner a statement and in the lower right corner the version. But if you press on any drum/guitar/microphone the menu in the bottom shows.
![20240406_155618](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/35326996/c70eaadc-d50a-4bae-bf7b-c3390179aba4)

Have fun

**Additional context**

**Comment by jnackmclain** [comment]
This is known and intentional as the splash screen runs ridiculously bad on Wii so I discard it for now
