### ISSUE TITLE
Countdown Does Not Always Appear

### ISSUE THREAD

**Issue by WarGod480** [hmxmilohax/rock-band-3-deluxe#612]
**Describe the bug**
The Countdown does not appear during a very long pause

**To Reproduce**
1. Play "High Voltage (Live)"
2. Get to "Section: Break 1"
3. Voilà

**Expected behavior**
I expect to see the Countdown

**Video**

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/123154581/c123603d-7aec-4221-af2c-0a259794d3e1

**DX Settings**
- `dx_settings.dta`: [dx_settings.txt]: (https://github.com/hmxmilohax/rock-band-3-deluxe/files/14895787/dx_settings.txt)
- `dx_modifiers.dta`: [dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14895790/dx_modifiers.txt)
- `dx_values.dta`: [dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14895792/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-nightly+1a03597
 - Song Count: 5141

**Additional context**
The pause from between the two notes is ~50 seconds

**Comment by jnackmclain** [comment]
fixed with b57a01188e07d252838ee81c300fae220141b4e5
