### ISSUE TITLE
Countdown / Solo Box jankery on the song "Holiday"

### ISSUE THREAD

**Issue by Radekore** [hmxmilohax/rock-band-3-deluxe#620]
**Describe the bug**
A few bugs with this one:
- Selecting the song from the menu consistently caused the "3" error to prevent the highway from appearing with Countdowns Hide Highway enabled for the first load of the song. Restarting would fix it, but the "Get Ready!" flashed twice weirdly
- The box during the solo would most of the time error and not display any Countdown after the end, also didn't display the word "Points" like it should have. Countdown did work as expected on a few occasions, but in those cases the solo bonus points didn't actually show at all. I'd guess it may have something to do with interactions between a super long sustain interfering with the timing of the end of the solo.

Video of all the errors / inconsistency:
https://github.com/hmxmilohax/rock-band-3-deluxe/assets/143662734/04b51c1f-f13b-42eb-8276-d4ad43c130ab

**To Reproduce**
1. Play "Holiday" by Green Day
2. Intro Countdown will most likely stay on 3 and not disappear
3. Restart the song and play to the end of the solo
4. See which of the 2 behaviors happens, should be that the Countdown starts but most of the time it didn't

**Expected behavior**
Countdown should disappear at the start of the song, as well as the end of the solo which should have caused the highway to disappear too.

**Game Information**
 - Platform: 360 HW
 - Version: 1.1.0-nightly+12dbdf7
 - Song Count: 2908

**Additional context**
Not sure if calibration matters in this case but I was on ridiculous delay settings as usual lol

**Comment by Radekore** [comment]
Small update; previously only ever saw the "3" error happen on countdowns at the very beginning of a song and never after actual notes - until now:
https://github.com/hmxmilohax/rock-band-3-deluxe/assets/143662734/093f4b9e-7f1e-4eb6-8dfd-477a243c27f2

**Comment by jnackmclain** [comment]
can you link the song or custom with this one pls (i dont recognize it)

**Comment by Radekore** [comment]
Sorry forgot that - it's the Power Gig chart of "Blood On My Hands" by The Used
https://discord.com/channels/961352072140324924/1148300784748994560/1233832682421747732

**Comment by jnackmclain** [comment]
fixed both cases with b57a01188e07d252838ee81c300fae220141b4e5
