### ISSUE TITLE
Pressing cancel on console-related warnings will change the setting anyway

### ISSUE THREAD

**Issue by qfoxb** [hmxmilohax/rock-band-3-deluxe#631]
**Describe the bug**
When toggling Detail level on Console, the warning about changing detail level appears but even when pressing cancel it changes the level anyway

**To Reproduce**
1. Overshell
2. Options
3. Deluxe Settings
4. Graphics
5. Detail level
6. Press cancel on warning
7. Level changes anyway

**Expected behavior**
Option should not toggle unless confirm is pressed.

**Game Information**
 - Platform: Xbox 360
 - Version: 1.1.0nightly-1fbb7ec

**Comment by qfoxb** [comment]
This also applies to 60 fps change

**Comment by jnackmclain** [comment]
fixed with c66d25939fecd89d9aba5a5fb71cee444d2c5536
