### ISSUE TITLE
Difficulty doesn't change when selecting instruments

### ISSUE THREAD

**Issue by ItsRandomDude** [hmxmilohax/rock-band-3-deluxe#632]
**Describe the bug**
Going through different instruments in the menu only show the first instrument's difficulty.

**To Reproduce**
1. Select song.
2. Scroll through instruments

**Expected behavior**
Scrolling through instruments show their difficulty.

**Screenshots**
![nodiffdx](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/93051417/158b06a5-5dcb-4c51-ba9c-2b0ce6d8cab6)

**DX Settings**
[dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15050925/dx_settings.txt)
[dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15050926/dx_modifiers.txt)
[dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15050927/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-nightly
 - Song Count: 7512

**Comment by DarkRTA** [comment]
do you have the commit hash for this? its part of the version string

**Comment by DarkRTA** [comment]
also not an issue in beta 6. im gonna bisect

**Comment by DarkRTA** [comment]
43fefc86ad87f9e1961317ccc74f6bcb02e17dc8 is the first commit with this issue

**Comment by jnackmclain** [comment]
fixed in latest dev
