### ISSUE TITLE
Play A Show Bugs

### ISSUE THREAD

**Issue by carlmylo** [hmxmilohax/rock-band-3-deluxe#633]
## Bug 1: Backing out of a selected opener will break Play A Show:
Play a Show requires selecting an opener to establish filters and parts. Back out during part selection breaks it.

1. Start Play A Show.
2. Select a song and go into part selection.
3. Back out of the part selection.
4. Select another song.
5. Finish the song.
6. Voting will never initialize.

**Expected behavior**
Play A Show should ask for votes after finishing the song.

## Bug 2: Woman vocalist option doesn't pick a song sung by a women:
Selecting a song sung by a woman vocalist resulted with a Blink-182 song being selected.

1. Start Play A Show.
2. During the voting section, pick a song by a woman vocalist.
3. Get a song by Blink-182.

**Expected behavior**
Voting for a song with a woman vocalist should pick a song with a woman vocalist.

**DX Settings**
- N/A

**Game Information**
 - Platform: PS3 (HEN)
 - Version: beta7
 - Song Count: Slightly over 1000

**Additional context**
Happened on a local band setup. Can ask for more info if needed.

**Comment by jnackmclain** [comment]
both fixed with 0a74f2b4a0ae2bd3ad3b39ea319861b56891bcea
and by that i mean i removed female vocalist
