### ISSUE TITLE
Menu Music Desync After Reboot

### ISSUE THREAD

**Issue by Radekore** [hmxmilohax/rock-band-3-deluxe#637]
**Describe the bug**
Music in the main menu (Kids in America by The Muffs) had instrument stems not in sync after clicking Reboot Game, honestly sounded kinda cool in a way but was obviously not supposed to do this. Not sure if it's consistent or not, I don't usually use the reboot option. It did get fixed after going into a menu that caused the music to stop and reload.

**To Reproduce**
1. Click Reboot Game
2. See if music is out of sync I guess

**Expected behavior**
Audio playing in sync and not being off by a beat

**Screenshots**
https://github.com/hmxmilohax/rock-band-3-deluxe/assets/143662734/e68cd91a-aa84-40d2-873a-853a87c6247b

**Game Information**
 - Platform: 360 HW
 - Version: 1.1.0-nightly+12dbdf7
 - Song Count: 2985

**Comment by jnackmclain** [comment]
reboot game hooks an rb3e function that we have no control of, we just call. best to report there. sorry

**Comment by Radekore** [comment]
Right, forgot that wasn't a DX feature. My bad lol
