### ISSUE TITLE
All custom songs erased after updating RB3 Deluxe to latest beta release on PS3

### ISSUE THREAD

**Issue by chintwo123** [hmxmilohax/rock-band-3-deluxe#638]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**DX Settings**
- `dx_settings.dta`: (rename to .txt and attach here)
- `dx_modifiers.dta`: (rename to .txt and attach here)
- `dx_values.dta`: (rename to .txt and attach here)

**Game Information**
 - Platform: [eg. Wii/Dolphin/Xbox 360/PS3/
 - Version: [eg. 1.1.0-beta4]
 - Song Count: [eg. 4269]

**Additional context**

**Comment by DarkRTA** [comment]
please fill out the issue template

**Comment by DarkRTA** [comment]
We looked into this anyway based on the title and tracked the bug down to a tool we depend on.
