### ISSUE TITLE
MTV Overlay doesn't show song details properly

### ISSUE THREAD

**Issue by ItzSlicedcorn** [hmxmilohax/rock-band-3-deluxe#639]
**Describe the bug**
The MTV overlay does not show any information about the current song outside of the current section name. This issue persists over reboots of the game and versions of DX.

**To Reproduce**
1. Choose any song to play (either in Quickplay or Practice mode) with my settings
2. Wait until the song title pops up
3. Bug

**Expected behavior**
The second screenshot shows what the MTV overlay should normally look like

**Screenshots**
1. The issue:
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/96348747/aaaeb269-4f12-4857-be5d-2e13dad63e7d)

2. Intended behavior (credit to [this Linos video](https://www.youtube.com/watch?v=zt9CcFCL4E0))
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/96348747/bab7d583-a334-4668-94bc-ce5e19e14f30)

**DX Settings**
- [dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15211432/dx_settings.txt)
- [dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15211433/dx_modifiers.txt)
- [dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15211441/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-nightly+5e4e76c
 - Song Count: 3885

**Additional context**
The song details used to show fine, however, when I started to turn on some Song Detail settings (I forget exactly which ones), that's when this issue started to pop up

**Comment by ItzSlicedcorn** [comment]
So turns out I had a bad dx_settings, so refreshing that seemed to fix it. Not sure how mine got to that point though.

**Comment by jnackmclain** [comment]
If you accidentally turned off author finder or pulled a settings from ps3 hw (which turns off author finder) it probably leads to this. Glad it's fixed for you
