### ISSUE TITLE
Harmony microphone input support?

### ISSUE THREAD

**Issue by G8RPHD** [hmxmilohax/rock-band-3-deluxe#64]
When playing RB3 (or DX) using RPCS3 or Xenia, microphone support is incomplete, apparently for different reasons. RPCS3 supports lead vocals but not harmonies due to apparent audio i/o problems in the emulator. Xenia does not appear to support microphone passthru at all, at this time.

See this thread on RPCS3, which documents the issue (especially the post by Readek, 5/19):
https://github.com/RPCS3/rpcs3/issues/8209

These appear to be very low priorities for the respective emulator project devs since only a handful of games support multiple microphone inputs; however, to RB3DX users, this is a major playability feature of the game.

Is it possible to patch RB3DX to correctly recognize enumerated audio i/o captures for multiple, simultaneous microphones? Alternatively, could a developer on the DX team make suggestions to the RPCS3 community on how the game sees audio i/o in order to make harmonies playable?

**Comment by LlysiX** [comment]
Neither deluxe nor the dx team can do anything about this.
Be patient, the emulators will support it someday.
