### ISSUE TITLE
Game Crashes When Returning to Music Library

### ISSUE THREAD

**Issue by Radekore** [hmxmilohax/rock-band-3-deluxe#641]
**Describe the bug**
Not super consistent but at least once a day the game will crash when returning to Music Library. Happened 4 times now - most of them were when selecting "Back to Music Library" from the pause menu, but just had one when pressing green on the song results screen to get back to the song list.

Also had 2 crashes on boot when loading the game, both seemed to happen at the same time as the AshCentral welcome screen. This may be a separate issue, but figured it was worth mentioning.

**To Reproduce**
1. Click Return to Music Library from the pause menu
2. Game might crash, might not - the bug isn't super consistent but I think it may somehow be related to the song info being added to the main menu, never had this crash before that was added. So far I remember it happening once from practice mode, mid-song pause twice, and song end screen once.

**Expected behavior**
Game returns to song list without crashing

**Game Information**
 - Platform: 360 HW
 - Version: 1.1.0+nightly b50082d
 - Song Count: 2989

**Comment by LightningXCE** [comment]
Also noticed this consistently when selecting "Play A Show" and returning during the first song - might be related?

**Comment by jnackmclain** [comment]
Please give latest dev a try

**Comment by Radekore** [comment]
Doesn't seem completely fixed, just updated to latest nightly and got a crash when just trying to select a new section within the same song in practice mode. Haven't fully tested returning to song library yet

**Comment by Radekore** [comment]
Haven't played as much in the last week but the return to library crashing has seemed better. Still getting random crashes in other menus, just had one when trying to get to the calibration menu from a mid-song pause

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/143662734/d7b57699-fab1-4a1c-a249-657e68d75c21

**Comment by jnackmclain** [comment]
i tried a bunch of times after making this change and it doesnt seem to crash anymore. closing for now with fingers crossed and hopeless optimism
