### ISSUE TITLE
Scrolling through the Select Venue options randomly kicks you to previous menu

### ISSUE THREAD

**Issue by Radekore** [hmxmilohax/rock-band-3-deluxe#642]
**Describe the bug**
Had this happen a few times, seems most frequent if it's one of the earliest modifications I try to make after starting the game. I'll be scrolling through the venues and all of a sudden it's back in the first venue options menu despite no inputs other than the strum bar

**To Reproduce**
1. Go to Venue Options
2. Try to select a venue
3. Hold the strum bar down to scroll through
4. See if it kicks back out

**Expected behavior**
Venue list remains normal without forced exit

**Game Information**
 - Platform: 360 HW
 - Version: 1.1.0+nightly b50082d
 - Song Count: 2989

**Comment by jnackmclain** [comment]
fixed with e768bf468d4dffcaa70c1b7fc191311facac68c3
