### ISSUE TITLE
Countdowns can appear during end screen

### ISSUE THREAD

**Issue by Radekore** [hmxmilohax/rock-band-3-deluxe#643]
**Describe the bug**
Somehow I got a countdown to appear during the end screen of a song, was the RhythmVerse custom of Camera Shy by School Boy Humor. Appeared consistently with this one, never saw this happen on anything else though.
AshCentral was down at the time of this error, not sure if that affected end screen behavior in any way. Wasn't included in the video but the end song feedback did correctly display the FC.

**To Reproduce**
1. Play Camera Shy (or any other song that can cause this error)
2. See if a Countdown appears after the song

**Expected behavior**
NOT a countdown after the end of the song

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/143662734/24dbf12e-b04f-4652-91c7-3bcca0bd820f

**Game Information**
 - Platform: 360 HW
 - Version: 1.1.0+nightly b50082d
 - Song Count: 2990

**Comment by jnackmclain** [comment]
fixed with 8cefcca0164368eedd98b91effb3c9c081b2d09e
