### ISSUE TITLE
Wii build not working with Deluxe Initializer (just need to figure out what I'm doing wrong)

### ISSUE THREAD

**Issue by gboliveira011** [hmxmilohax/rock-band-3-deluxe#644]
**Describe the bug**
No matter what I do I cannot make a proper custom build for the Wii version. I've extracted my Wii ISO and got the main_wii.hdr and stuff into the out folder,

**To Reproduce**
1. Go to designated Deluxe build folder
2. Click on scripts folder
3. Select build_wii.bat (for Windows anyway)

**Expected behavior**
Wii build should finish successfully

**Screenshots**
<img width="934" alt="Wii Failure" src="https://github.com/hmxmilohax/rock-band-3-deluxe/assets/116613564/ae8f5f5e-e3d9-4bf3-a979-7ede04aba978">

**DX Settings**
Nothing at the moment

**Game Information**
 - Platform: Wii/Dolphin
 - Version: eg. 1.1.0-beta7
 - Song Count: 83 (only main setlist lol)

**Additional context**
360 and PS3/RPCS3 will build just fine, so I don't know what's wrong with Wii/Dolphin

**Comment by DarkRTA** [comment]
You need to extract the original game files (from retail) using dolphin.

**Comment by gboliveira011** [comment]
Just did that, but still getting the same error. Is there a specific location the bat needs to look in? I put it in the out/wii folder

**Comment by gboliveira011** [comment]
Nevermind. Apparently, I can't read and skimmed over the part of the error where it needs to look in the platform folder. Sorry about that lol

**Comment by gboliveira011** [comment]
Actually new problem: Whenever I carry over the completed custom patch from the Wii folder into the patch files directory in the Wii patcher folder, all of my personal modifications are ignored.

**Comment by DarkRTA** [comment]
closing in favor of #646
