### ISSUE TITLE
Option to automatically turn black venue songs into color/music video venues with randomized angles

### ISSUE THREAD

**Issue by chintwo123** [hmxmilohax/rock-band-3-deluxe#645]
When playing Clone Hero songs in Rock Band 3, they all have black venues as there is no venue performance info with CH (some have video backgrounds). Can we setup a feature to automatically turn black venue songs into color venues or music videos with randomized angles? Better to see that then just stale black venues with only one angle. Let me know what you guys think.

**Comment by DarkRTA** [comment]
This is not something we can do with DX. Adding venue infomation is the job of the chart author or tool you are using to convert.
