### ISSUE TITLE
Building for Wii ignores custom build features

### ISSUE THREAD

**Issue by wintyre01** [hmxmilohax/rock-band-3-deluxe#646]
**Describe the bug**
Having a similar issue as I saw in #644, or moreso why it seems to have been reopened. Just like the gentleman in that one issue I was able to make a build for Wii, but when I copy the ark files into the patch files folder for the Wii version patcher, it ignores everything I’ve done, such as custom sources, custom goals, etc. so I don’t know what either of us are doing wrong.

**To Reproduce**
1. Build Wii version using dump from Dolphin
2. Throw main Wii ark and main Wii 10 ark in the patch file folder to replace the default ones in there
3. Build RB3 Deluxe wbfs as you would normally
4. See that none of my custom sources or goals are appearing

**Expected behavior**
Personal modifications should also appear.

**Screenshots**
N/A

**DX Settings**
All default as of right now on the Wii

**Game Information**
 - Platform: Wii/Dolphin
 - Version: 1.1.0-beta7
 - Song Count: 104 (first time testing with Wii so I have a limited number of tracks right now)

**Additional context**
Should also note that I think it breaks some of the text, especially the “loading DLC from SD card” to display the variable name instead “dlc_sdmode_desc”

**Comment by DarkRTA** [comment]
Only thing i can suggest is looking at how its done in CI. I seriously do not know what you are doing wrong here as copying from the `out/wii` dir *after* building will give you a build with your changes.

https://github.com/hmxmilohax/rock-band-3-deluxe/blob/100069d1c2293424a659ecb4a5ddacc3b91c4f9b/.github/workflows/build.yml#L125

As a sanity check, edit a commonly used locale string and make sure its reflected in-game.

**Comment by wintyre01** [comment]
Double-checked and it seems like my goals DO appear, but anything relating to songs gets ignored
Example: I've been able to get successful decensors for Beautiful People, Don't Bury Me, and Viva la Resistance working on 360 and...sort of PS3 (mogg doesn't read well there so I have to block those on there and use cons until there's a fix but that's besides the point) but Wii isn't reading anything in that regard (the two beta tracks Feelin' Alright and the full version of Black Magic Woman won't even show in that version if that says anything)

**Comment by jnackmclain** [comment]
It has been my understanding that mogg updates from in ark do not work, except potentially for disc songs. In ark mogg updates for dlc haven't ever worked for us.

**Comment by DarkRTA** [comment]
closing this as resolved.

if you need general dev help consider joining the milohax discord guild
