### ISSUE TITLE
Game crashes at random when "Pressing Orange"

### ISSUE THREAD

**Issue by WarGod480** [hmxmilohax/rock-band-3-deluxe#647]
**Describe the bug**
Game crashes when trying to quickplay a song from the main menu (Press Orange to play song x)

**To Reproduce**
Press Orange i guess
Pray that it doesn't crash
Game fails our prayers and crashes anyway

**Expected behavior**
dont crash

**Video**
https://github.com/hmxmilohax/rock-band-3-deluxe/assets/123154581/9e0c9995-040d-4e88-b4d4-df47cc39efe9

**DX Settings**
- `dx_settings.dta`: [dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15287922/dx_settings.txt)
- `dx_modifiers.dta`: [dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15287923/dx_modifiers.txt)
- `dx_values.dta`: [dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15287924/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-nightly+608c64e
 - Song Count: 5140

**Additional context**
seems to happen at random, at first it happened when i pressed it the first time, and trying to recreate it, it ended up like in the video

**Comment by jnackmclain** [comment]
Seemingly fixed in latest dev
