### ISSUE TITLE
Menu Backgrounds menu does not let you select another type of background after setting one 

### ISSUE THREAD

**Issue by qfoxb** [hmxmilohax/rock-band-3-deluxe#654]
**Describe the bug**
When changing a menu background setting, after selecting an option i get sent back to a menu that resembles the menu for choosing between changing song transitions, menu backgrounds and song select backgrounds, but all of the buttons just load a new song transition.

**To Reproduce**
1. Deluxe Settings
2. Venue Options
3. Menu Backgrounds...
4. Select Main Menu or Music Library or Song Transitions
5.  select an option or Shuffle All
6. get brought back to the menu with main menu, music library and song transitions
7. No buttons do anything

**Expected behavior**
The buttons for selecting which type of menu background should work after selecting one type

**Screenshots**
https://github.com/hmxmilohax/rock-band-3-deluxe/assets/42038239/ce661a94-5c05-4721-879e-b22383ae0b9f
(excuse the weird resolution)

**Game Information**
 - Platform: RPCS3 but also tested on Xbox 360 HW
 - Version: 1.1.0-beta7
 - Song Count: 3569

**Comment by jnackmclain** [comment]
fixed with e768bf468d4dffcaa70c1b7fc191311facac68c3
