### ISSUE TITLE
Shuffling all song transitions on rpcs3 causes a crash. 

### ISSUE THREAD

**Issue by qfoxb** [hmxmilohax/rock-band-3-deluxe#655]
**Describe the bug**
 Selecting shuffle all under song transitions causes a 0x0 crash on rpcs3. 

**To Reproduce**
1. Deluxe Settings
2. Venue Options
3. Menu backgrounds
4. Select Song Transitions
5. Shuffle All
6. F {PPU[0x1000000] Thread (main_thread) [0x008f901c]} VM: Access violation reading location 0x0 (unmapped memory)

**Expected behavior**
Doesn't crash

**Screenshots**
https://github.com/hmxmilohax/rock-band-3-deluxe/assets/42038239/5c10a8ce-f4ea-47df-930a-178231a37375

**Game Information**
- Platform: RPCS3
- Version: 1.1.0-beta7
- Song Count: 3569

**Comment by jnackmclain** [comment]
fixed in 723cf4800f5d2029eea2c5be0b44bc7f8fb8b06f
