### ISSUE TITLE
Super messed up menu+animation state / stats error after pressing orange on main menu

### ISSUE THREAD

**Issue by Radekore** [hmxmilohax/rock-band-3-deluxe#656]
**Describe the bug**
Game gets all kinds of broken after pressing orange to play the menu track and then backing out by hitting red, animations and menus in particular

**To Reproduce**
1. Play any song (then quit to menu)
2. Press Orange on main menu to play the main menu song
3. Press red to back out into song library
4. Song stats are partially hidden but not fully (mostly the icons seem to deload), and band members are also frozen in menu idle animations. Issue persists even when re-entering the song menu a 2nd time without pressing orange
5. Animations in general enter a very bizarre state which is hard to describe, see video. Pausing the song also doesn't really pause the highway but unpausing does seem to return the song to it's normal position (if anything about the game can even be described as normal at that point)

**Expected behavior**
**Not** any of all that shenanigans

**Screenshots**
https://youtu.be/mNvSolcMmM0

**Game Information**
 - Platform: Xbox 360 HW
 - Version: 1.1.0-nightly+afa452f
 - Song Count: 2992

**Additional context**

**Comment by jnackmclain** [comment]
try latest dev i already pushed a potential fix

**Comment by Radekore** [comment]
Newest patch seems to have resolved all the errors

**Comment by jnackmclain** [comment]
amazing, im ngl im kinda surprised
