### ISSUE TITLE
Music Library Refresh Option Request

### ISSUE THREAD

**Issue by chintwo123** [hmxmilohax/rock-band-3-deluxe#657]
I think putting in a refresh music library option will be helpful in-game so that we don't have to restart the game anytime we make changes to music metadata and whatnot. Would save a bit of time

**Comment by jnackmclain** [comment]
closing as this is blocked by #662

**Comment by DarkRTA** [comment]
this should remain open and be given the blocked label imo

**Comment by jnackmclain** [comment]
added in 18b201c1d16d5cbf9243fd9725568ac1fcbead96
closing for real now

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55568980/9e151a42-7c00-4fb8-a7eb-da06e56a0852
