### ISSUE TITLE
Learn An Instrument is broken

### ISSUE THREAD

**Issue by trishiskukky** [hmxmilohax/rock-band-3-deluxe#658]
**Describe the bug**
When trying to enter the trainers in Learn an Instrument, the game immediately crashes.
(I have only tested this on RPCS3 and with Pro Guitar and Pro Drums)

**To Reproduce**
1. Go to "Practice" --> "Learn An Instrument" via Main Menu.
2. Select an instrument to train.
3. Select any 'lesson group'.
4. Game crashes consistently.

**Expected behavior**
Being able to play the trainers.

**Screenshots**
[Pictured: Me going from the main menu to the crashing]

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/163791405/b18e1ac1-4194-4518-bff4-1bad8347fb8a

**DX Settings**
[dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15368527/dx_settings.txt)
[dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15368528/dx_modifiers.txt)
[dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15368529/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-nightly+fd834bd
 - Song Count: 5475

**Additional context**
Very bad.

**Comment by jnackmclain** [comment]
If you accidentally turned off author finder or pulled a settings from ps3 hw (which turns off author finder) it probably leads to this. Glad it's fixed for you

**Comment by jnackmclain** [comment]
This is the wrong issue... sorry

**Comment by jnackmclain** [comment]
I believe this was also fixed with c8e5c9cf408dee7b59c8b59442b7859b3bffb2da

![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55568980/fa45caac-2c59-43f3-9e16-617c54cb2206)
