### ISSUE TITLE
New menu screen causes framerate drops

### ISSUE THREAD

**Issue by paulsd95** [hmxmilohax/rock-band-3-deluxe#66]
Pretty much what the title says - the current menu screen (which appears to be derived from the title screen) causes severe framerate drops that weren't there on the usual menu screens.

**Comment by LlysiX** [comment]
im assuming emulator since this should not be a problem on hardware.

If you are building the game yourself, change $svnumber in ui/init.dta to something else (as stated in the comment there, 3 is default).
If not, just deal with it
