### ISSUE TITLE
Enabling Countdowns Hide Highway causes the 4x multiplier glow animation to show up too early as a static image

### ISSUE THREAD

**Issue by Radekore** [hmxmilohax/rock-band-3-deluxe#661]
**Describe the bug**
Normally there's nothing around the multiplier ring until it hits 4x, but when Countdowns Hide Highway is enabled the glow appears at all times if the highway comes in after a countdown. It'll be completely static until the multiplier reaches 4x then start animating as intended

**To Reproduce**
1. Enable Countdowns Hide Highway
2. Select any song that has a countdown at the beginning

**Expected behavior**
No glow at all until multiplier hits 4x, glow continues in proper state if highway hides mid-song and then returns

**Screenshots**
![Countdowns Hide Highway Ring](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/143662734/cda988a2-1ba2-42bd-bb60-db0fc2d88114)

In this case it's a blue ring since I have FC indicator set to Ring, I'm guessing it'd be gold if it's set to Both or Glow

**Game Information**
 - Platform: Xbox 360 HW
 - Version: 1.1.0+nightly fc71a84
 - Song Count: 2989

**Comment by LinosM** [comment]
Should be fixed now by https://github.com/hmxmilohax/rock-band-3-deluxe/commit/d0b89286c565d7d0aed3d6bda9a28571b9c00fcb, tested this but let me know if anything else seems off

**Comment by Radekore** [comment]
Looks great! Just tested latest nightly on the Keys chart of Before I Forget since it has a ton of countdowns and they all showed the correct multiplier glow state
