### ISSUE TITLE
[RPCS3] Deleting songs crashes the game

### ISSUE THREAD

**Issue by carlmylo** [hmxmilohax/rock-band-3-deluxe#662]
**Describe the bug**
Deleting a song from within Rock Band 3 will cause a crash. I have tested vanilla (V1.06) with the same DLC packs and it works fine there.
I've tested with similar DLC counts in both vanilla and DX.

This hasn't been tested on PS3 as far as I know.

**To Reproduce**
1. Go to the song library
2. Pick a song to delete and delete it
3. Wait for Rock Band 3 to finish refreshing content
4. Crash.

**Expected behavior**
Rock Band 3 Deluxe should be able to delete a song within the library.

**Screenshots**
N/A

**DX Settings**
[dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15400907/dx_modifiers.txt)
[dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15400908/dx_settings.txt)
[dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15400909/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-nightly+29cc948
 - Song Count: 5381

**Additional context**
`F {PPU[0x1000000] Thread (main_thread) [0x00a83804]} VM: Access violation reading location 0x2d32313d (unmapped memory)`

**Comment by carlmylo** [comment]
I have tested every single release from 1.0c up to the latest workflow (ffacf0a). I've reset DX settings, tested with various amounts of DLC, and tested with different game dumps and it kept crashing.
Deleting my save file and trying to delete a song pack made it work.

**Comment by DarkRTA** [comment]
I genuinely think this is a bug with either RPCS3 or the vanilla game.

**Comment by carlmylo** [comment]
Tested with the same save file in vanilla BLUS30463 01.05. Deleting works without causing crashes.

**Comment by jnackmclain** [comment]
genuinely rpcs3 issue

**Comment by carlmylo** [comment]
JDK and I were on outdated firmware (3.41 and 4.82 respectively). We installed the latest (4.91) and the issue is resolved.
