### ISSUE TITLE
Using beta 8, trying to toggle over to "more info" on the Setlist screen crashes the game

### ISSUE THREAD

**Issue by EuroMIX2** [hmxmilohax/rock-band-3-deluxe#665]
Using beta 8, trying to toggle over to "more info" on the Setlist screen crashes the game.

Select Setlists to enter the Setlists screen.
Scroll down to a setlist.
Press Y (on Xbox).
Game locks up and fatal crashes.

Pressing Y to toggle to the setlist's more info screen without crashing,

**Screenshots**
None currently.

**DX Settings**
- `dx_settings.dta`: (rename to .txt and attach here)
- `dx_modifiers.dta`: (rename to .txt and attach here)
- `dx_values.dta`: (rename to .txt and attach here)
^ Not sure where these are located, but I'll add them if instructed.

 - Platform: Xbox 360 (Real Hardware)
 - Version: [eg. 1.1.0-beta8]
 - Song Count: [eg. 2969]

**Additional context**
Worked fine on beta 7.

**Comment by jnackmclain** [comment]
fixed with d452ddf88553c9bcb2d2da84fcc4d36495f8102e
