### ISSUE TITLE
Setlists In Goals Crash The Game

### ISSUE THREAD

**Issue by LongTallJodie** [hmxmilohax/rock-band-3-deluxe#668]
**Describe the bug**
In Beta 8 using RPCS3, attempting to play a goal that loads a setlist crashes the game after selecting your difficulty.

**To Reproduce**
1. Go to 'Career'
2. Go to 'My Goals'
3. Choose the top 'Rock Band' option, then 'Deluxe Goals', then 'Spongebob' (for example)
4. Choose your instrument and difficulty.
5. See error

**Expected behavior**
The game beings normally with the first song in the setlist.

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-beta8
 - Song Count: 13489
 
[dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15440532/dx_modifiers.txt)
[dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15440534/dx_settings.txt)
[dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15440535/dx_values.txt)

**Comment by jnackmclain** [comment]
Fixed with c8e5c9cf408dee7b59c8b59442b7859b3bffb2da
