### ISSUE TITLE
[RPCS3] Changing Menu Backgrounds Leads to Crash After Song Complete

### ISSUE THREAD

**Issue by carlmylo** [hmxmilohax/rock-band-3-deluxe#669]
**Describe the bug**
Changing `dx_forced_main_menu_bg` can lead to crashes after continuing past the song score screen. 

**To Reproduce**
1. Go to Deluxe Settings > Venue Options > Menu Backgrounds > Main Menu
2. Change it to something else
3. Jump into a song and complete it
4. Crash (seems to mostly happen when online)

**Expected behavior**
The game shouldn't crash after continuing past the score screen.

**Screenshots**
N/A

**DX Settings**
[dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15441796/dx_modifiers.txt)
[dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15441797/dx_values.txt)
[dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15441798/dx_settings.txt)

**Game Information**
 - Platform: RPCS3
 - Version: 56edfef
 - Song Count: 6425

**Additional context**
Changing `dx_forced_main_menu_bg` back to default settings seems to stops crashes.
Reporting on behalf of @trishiskukky
This bug was first spotted on `02/05/2024` but seems to only be reported now.

**Comment by jnackmclain** [comment]
fixed with 6f39dd19c9590d13287668ab116e95b670f4fd8e
