### ISSUE TITLE
Keys trainer speed adjustment does not slow down track, changes pitch instead

### ISSUE THREAD

**Issue by paulsd95** [hmxmilohax/rock-band-3-deluxe#67]
This is a weird one. When using the Pro Keys Trainer (which used to not work at all), if I try to slow down the tempo, it'll try to slow down, then reset back to full speed, but with the song's pitch changing wildly, as if it was slowed down at the same pitch, then sped up with a varispeed.

**Comment by jnackmclain** [comment]
Fixed in [d39e0f1](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/d39e0f1f4c898b58e5057ed1e8038ddd569e52ee)
