### ISSUE TITLE
5 lane compatibility for GH drums

### ISSUE THREAD

**Issue by Proofeek** [hmxmilohax/rock-band-3-deluxe#670]
It would be great if you added 5-lane compatibility for pro charts, similar to Clone Hero, for players using Guitar Hero drums. They have a conversion table presented on this page https://wiki.clonehero.net/books/guitars-drums-controllers/page/drum-mapping-guide :

![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/78957574/6aba355f-29b5-43af-ab80-58f39828a2ad)

Although I think that the blue cymbal should be converted to the yellow cymbal
Here is some additional information on how they implemented it: https://wiki.clonehero.net/books/guitars-drums-controllers/page/video-game-drums
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/78957574/7ff4c1de-921a-4f08-8e34-274ad5658dcb)

**Comment by DarkRTA** [comment]
This is impossible to do in DX alone, sorry. That being said, you can still play pro drums by enabling only the green cymbal.
