### ISSUE TITLE
Pro Keys icon when you plug in Pro Keys

### ISSUE THREAD

**Issue by Aloquendiar** [hmxmilohax/rock-band-3-deluxe#674]
![Pro Guitar](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/48574329/55cccc9d-1907-4668-8aca-b47943dfaefd)
As you can see when using Pro Guitar, the icon changes to the PRO icon before entering, unlike Pro Keys where it remains in its standard icon. I don't know if it is possible for this to change to the PRO icon, it would be good for the online mode.

**Comment by DarkRTA** [comment]
> it would be good for the online mode.

technically wouldn't benefit online mode at all as the game only has 1 type of keyboard controller, unlike guitars where there are actually two distinct types of guitar controllers, hence the need for the pro distinction in the overshell here

that being said, im not opposed to this being implemented but there's not really much of a strong argument for doing so outside of aesthetic changes

**Comment by DarkRTA** [comment]
after thinking about it a bit more, we probably shouldn't do this since some people force a pad into the keys slot and it would falsely represent them as pro keys if we did this
