### ISSUE TITLE
Starting/Resuming A Road Challenge Causes A Crash

### ISSUE THREAD

**Issue by carlmylo** [hmxmilohax/rock-band-3-deluxe#675]
**Describe the bug**
Entering a road challenge crashes the game when part selection comes up

**To Reproduce**
1. Go to Road Challenge
2. Start or resume a Road Challenge
3. Select a setlist
4. Crash

**Expected behavior**
You should be able to start or resume road challenges.

**Screenshots**
N/A

**DX Settings**
[dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15473669/dx_values.txt)
[dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15473670/dx_modifiers.txt)
[dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15473671/dx_settings.txt)

**Game Information**
 - Platform: RPCS3 (Tested on PS3 too)
 - Version: 1.1.0-beta8
 - Song Count: 5738

**Additional context**
I tested with Sloth and SAMUEL_POSTING brought this up initially.

**Comment by carlmylo** [comment]
Works in beta7.

**Comment by jnackmclain** [comment]
guess what
this was also fixed with c8e5c9cf408dee7b59c8b59442b7859b3bffb2da
