### ISSUE TITLE
Crash Accessing Theme Customizer

### ISSUE THREAD

**Issue by carlmylo** [hmxmilohax/rock-band-3-deluxe#676]
**Describe the bug**
Accessing the real time theme customizer will crash the game.

**To Reproduce**
1. Go to Menu > Options > Deluxe Settings > Track Theme > [Customize]
2. Select [Enter Customizer]
3. Confirm that you want to enter the customizer
4. Crash

**Expected behavior**
The real time theme customizer should work.

**Screenshots**
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/56451149/7384e243-a580-4272-81c7-50c0a901434d)

**DX Settings**
[dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15476743/dx_modifiers.txt)
[dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15476744/dx_settings.txt)
[dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/15476745/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: beta8
 - Song Count: 5738

**Additional context**
Submitted by jobo69 on Discord. I was able to replicate it.

**Comment by carlmylo** [comment]
Works in beta7.

**Comment by jnackmclain** [comment]
fixed in c8e5c9cf408dee7b59c8b59442b7859b3bffb2da
