### ISSUE TITLE
Juke Joint Jezebel (UGC_5001220) lacks venue animations

### ISSUE THREAD

**Issue by Bakartridge** [hmxmilohax/rock-band-3-deluxe#679]
Just noticed that Juke Joint Jezebel doesn't have proper venue animations in RB3DX, they're there properly in RB2, though in RB3DX it's just a static shot of the band playing, and like 95% of the time they just wander off-stage so the drummer is the only one left.

**Comment by r0bd0g** [comment]
I'm not seeing a problem at first glance. Do other RBN1 keys update songs have working venues?
(Examples include Push Push (Lady Lightning), Bodies, Dogs Can Grow Beards All Over.)

**Comment by Bakartridge** [comment]
Those do have working venues actually (tried all the rbn1 songs I have with keys updates), it's just that one song for some weird reason.

**Comment by r0bd0g** [comment]
This one has a weird track name in the pro drums update. Because it's the first track name in that track, it's possible it could cause the drum update to not apply? But could that possibly break the venue???

**Comment by jnackmclain** [comment]
fixed via #685
