### ISSUE TITLE
No Trainers Crash Protection doesn't work

### ISSUE THREAD

**Issue by carlmylo** [hmxmilohax/rock-band-3-deluxe#683]
**Describe the bug**
Deluxe's crash protection when trainers are missing from a song is not working, causing the player to crash when accessing a song without trainers.

**To Reproduce**
1. Go to `Learn a Song`
2. Pick a song without trainers (will depend on user's library)
3. Crash

**Expected behavior**
The player should be kicked back to the song menu and a message ("No Trainer for Pro-[Instrument] found in song.") should appear, [[as outlined here]](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/1bf4976edbc052ae7f58ac275fb11a561edc8946).

**Screenshots**
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/56451149/b745c301-702d-4160-97ae-bd137df16a1d)

**DX Settings**
[dx_values.dta.txt](https://github.com/user-attachments/files/15528997/dx_values.dta.txt)
[dx_modifiers.dta.txt](https://github.com/user-attachments/files/15528998/dx_modifiers.dta.txt)
[dx_settings.dta.txt](https://github.com/user-attachments/files/15528999/dx_settings.dta.txt)

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-beta8
 - Song Count: Over 6000

**Additional context**
N/A

**Comment by carlmylo** [comment]
Last seen working in 1.1.0-beta3. It has been broken in every beta release since 1.1.0-beta4.

**Comment by jnackmclain** [comment]
the commit that it broke on is 99999d8c6d64712a1dba032bcf0540560b8fbc87
looking into it

**Comment by jnackmclain** [comment]
fixed with 395d295086caa775960ac8189dfef4efbc559832
