### ISSUE TITLE
Disable V-Sync by Default on RPCS3

### ISSUE THREAD

**Issue by qfoxb** [hmxmilohax/rock-band-3-deluxe#686]
Putting this here so it isn't forgotten - Disabling V-Sync on rpcs3 gets rid of a lot of performance issues on lower end hardware

**Comment by jnackmclain** [comment]
i already fixed auto turning on vsync in calibration mode
like 5 minutes ago lol

**Comment by jnackmclain** [comment]
*screen not mode

**Comment by jnackmclain** [comment]
Both of these were actually already done, luna just typod the platform
