### ISSUE TITLE
Entering the customizer from the main menu with a sub-menu open leaves main menu in a weird state

### ISSUE THREAD

**Issue by LightningXCE** [hmxmilohax/rock-band-3-deluxe#688]
**Describe the bug**
If you enter the Track Theme customizer while a sub-menu is open on the main menu and then exit the customizer, the game returns to the main menu where the sub-menu is still open, but not visibly. Scrolling up and down still shows sub-menu items.

**To Reproduce**
1. Go to Main Menu, select anything with a sub-menu (play, etc)
2. Open theme customizer
3. Exit
4. Scroll up and down in an invisible sub-menu except for transitioning name highlights

**Expected behavior**
Main menu should reset state when being returned to.

**Screenshots**
Attached Video.

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/720172/e03137ee-8fb2-4dc3-8683-e59e2306afac

**Game Information**
 - Platform: Xbox 360
 - Version: [develop](https://github.com/hmxmilohax/rock-band-3-deluxe/compare/develop) ([#687](https://github.com/hmxmilohax/rock-band-3-deluxe/pull/687))
 - Song Count: 6k something idk

**Additional context**
Minor and fixes itself when pressing B, but still might cause issues?

**Comment by jnackmclain** [comment]
fixed with 434c227e6819d2477117d48f38641d5a21a726e1
