### ISSUE TITLE
[Feature Request] Disable Touch Bar FX

### ISSUE THREAD

**Issue by paulsd95** [hmxmilohax/rock-band-3-deluxe#69]
It seems that 'Disable Whammy FX' only works on guitar/bass, but does nothing for the modulation done by the touch bar on keyboard. Is that something that is workable, or as I assume something that is beyond the bounds of what the mod can tweak?

**Comment by jnackmclain** [comment]
Unfortunately, there doesn't appear that I can see to be any indication of the touch bar modulation like whammyfx. whammyfx can be found in beatmatch.dta, but I'm not seeing anything similar for keys.
The call for whammy is a simple array "whammy_enabled" true or false, which we are also lucky enough that it checks multiple times in games. several other things, including "mute_volume" in the same dta, only get checked once per boot.
