### ISSUE TITLE
Entering track customizer while in gameplay causes a soft lock

### ISSUE THREAD

**Issue by LightningXCE** [hmxmilohax/rock-band-3-deluxe#693]
**Describe the bug**
While playing a song, attempt to enter the track customizer. Game will back out of gameplay, show loading screen, and then soft lock with the animated loading icon.

**To Reproduce**
1. Play song
2. Enter Customizer
3. Stare at the kaledoscope

**Expected behavior**
Customizer loads. Looks like it does attempt to load a new song inbetween but we never hit gameplay.

**Game Information**
 - Platform: 360
 - Version: Latest Nightly [969e371](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/969e3710e2988a03f22853842243bf4faab38261)

**Comment by jnackmclain** [comment]
yeah because you shouldnt do that
but ill lock it behind being in game to avoid this

**Comment by jnackmclain** [comment]
fixed with e86f140627ca149ecd0599f541bcb37d72b3279e
