### ISSUE TITLE
Artist label jumping doesn't work as intended in practice song select

### ISSUE THREAD

**Issue by zanesix** [hmxmilohax/rock-band-3-deluxe#696]
**Describe the bug**
Instead of jumping artist-by-artist like in quickplay song select, the game will freeze for a few seconds and then jump to the next letter, like in the vanilla game.

**To Reproduce**
1. Go to practice mode
2. Make sure songs are sorted by artist
3. Hit the orange fret (or your instrumental equivalent)
4. See that you are now at the top of the next letter

**Expected behavior**
Should go down to the next header, like in quickplay.

**Screenshots**
N/A

**DX Settings**
N/A

**Game Information**
 - Platform: Xbox 360
 - Version: Latest commit, [2ee0558](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/2ee0558f584b03fc0d58a137a11eec5c65f4a212)
 - Song Count: Not relevant, but 3895

**Additional context**
N/A

**Comment by jnackmclain** [comment]
fixed in a53ecf8b143adb8e0588912503e9c4c1946624f6
and by fixed, turns out since i rely on being able to highlight headers, this wont work anywhere that disables header selection, like practice mode.
so normal shortcut skipping will be used in that case
