### ISSUE TITLE
Bad menu bg settings causes a crash

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#700]
**Describe the bug**
the game is like dyslexic or something

**To Reproduce**
1. fuck up your dx_settings.dta
2. idk i found this happened when i set the main menu bg to "deluxe screen" and then disabling all

**Expected behavior**
the game doesn't choke and die

**Game Information**
 - Platform: rpcs3
 - Version: idk
 - Song Count: yes

**Comment by jnackmclain** [comment]
It would be helpful to also get a fucked up settings dta

**Comment by lunalawl** [comment]
Reproduced here 
[dx_settings.txt](https://github.com/user-attachments/files/15572527/dx_settings.txt)

**Comment by jnackmclain** [comment]
fixed with 6f39dd19c9590d13287668ab116e95b670f4fd8e
