### ISSUE TITLE
In-game difficulty rings don't work

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#701]
**Describe the bug**
In-game difficulty rings don't work

**To Reproduce**
1. Go ingame
2. See error

**Expected behavior**
The difficulty rings work

**Game Information**
 - Platform: all of them

**Comment by jnackmclain** [comment]
fixed with eb551c232e8cd1613ff4b68ed1a28c5fa18e7f27
