### ISSUE TITLE
Leaving Deluxe Settings will most likely cause a crash on xbox

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#703]
**To Reproduce**
1. Go to 'Deluxe Settings'
2. you may have to fuck around in there a bit but most of the time when you back out the game will crash

**Expected behavior**
the game doesnt crash

**DX Settings**
[dx_settings.txt](https://github.com/user-attachments/files/15598809/dx_settings.txt)
[dx_modifiers.txt](https://github.com/user-attachments/files/15598812/dx_modifiers.txt)
[dx_values.txt](https://github.com/user-attachments/files/15598813/dx_values.txt)

**Game Information**
 - Platform: Xbox 360
 - Version: latest nightly i cant read the text on the crt
 - Song Count: 5236

**Comment by jnackmclain** [comment]
fixed with 9e679dd4d8aaf2099f96dcf2cfa8bb0d9886f3d3
