### ISSUE TITLE
On-screen keyboard doesn't come up on Wii

### ISSUE THREAD

**Issue by r0bd0g** [hmxmilohax/rock-band-3-deluxe#706]
Or so I've heard.

**Comment by r0bd0g** [comment]
Or maybe actually the keyboard is fine and it's just crashing trying to visit the customizer in general? Honestly I'm not super sure from the description when the crash occurs b/c honestly I've never used the feature.

**Comment by APerson7778** [comment]
For me, the game just crashes as soon as the animation from going into the character customizer plays

**Comment by jnackmclain** [comment]
this was fixed at some point
