### ISSUE TITLE
Game locks up after the last song of a Road Challenge Venue

### ISSUE THREAD

**Issue by Ardebitis** [hmxmilohax/rock-band-3-deluxe#708]
**Describe the bug**
Instead of showing the results screen of a Road Challenge Venue, the game freezes. This has happened consistently ever since the RB3DX update today.

**To Reproduce**
1. Play through all songs in a road challenge venue.
2. Press green.

**Expected behavior**
A venue results screen.

**Screenshots**
N/A

**DX Settings**
- `dx_settings.dta`: 
[dx_settings.txt](https://github.com/user-attachments/files/15693782/dx_settings.txt)
- `dx_modifiers.dta`: 
[dx_modifiers.txt](https://github.com/user-attachments/files/15693821/dx_modifiers.txt)
- `dx_values.dta`:
[dx_values.txt](https://github.com/user-attachments/files/15693848/dx_values.txt)

**Game Information**
 - Platform: PS3/RPCS3
 - Version: 1.1.0-beta9
 - Song Count: 2112

**Comment by jnackmclain** [comment]
mind trying nightly?
https://nightly.link/hmxmilohax/rock-band-3-deluxe/workflows/build/develop

**Comment by LongTallJodie** [comment]
I came to report this myself and can confirm that the latest nighty did NOT fix it for me.  Also on RPCS3.

**Comment by Ardebitis** [comment]
Seconded. Tried the latest nightly and the bug still persists.

**Comment by jnackmclain** [comment]
just tracking, this is the issue
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55568980/57029e85-663e-4974-9001-ba7d87e146cc)

**Comment by jnackmclain** [comment]
fixed in latest dev as of 43a7c606aa305edce59097b9d93c2aa2419964db
