### ISSUE TITLE
Lock up after completing a career goal, Fatal Crash Intercepted

### ISSUE THREAD

**Issue by h3llb3nt** [hmxmilohax/rock-band-3-deluxe#712]
**Describe the bug**
crash just after completing a career goal

**To Reproduce**
while working on "my goals" pick any goal and complete it the goal, once the final song you need is completed and you are on the score screen the game will crash and you get sent back to the dashboard 

**Expected behavior**
to not crash and take the player back to the my goals screen from whence they came i assume. 

**Screenshots**
![Screenshot 2024-06-07 085019](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/22822528/0110be14-c1e8-448d-9bed-b81c9c0aa158)
![Screenshot 2024-06-07 085045](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/22822528/9ceabcf4-db0c-4a76-a731-26b4548cb934)

**DX Settings**
[dx_modifiers.dta.txt](https://github.com/user-attachments/files/15739258/dx_modifiers.dta.txt)
[dx_settings.dta.txt](https://github.com/user-attachments/files/15739259/dx_settings.dta.txt)
[dx_values.dta.txt](https://github.com/user-attachments/files/15739260/dx_values.dta.txt)

**Game Information**
 - Platform: Xbox 360
 - Version: 1.1.0-beta9
 - Song Count: 2673

**Additional context**

**Comment by jnackmclain** [comment]
mind trying nightly?
https://nightly.link/hmxmilohax/rock-band-3-deluxe/workflows/build/develop

**Comment by h3llb3nt** [comment]
sure thing, i'll let you know later tonight

**Comment by h3llb3nt** [comment]
Three goals in and no crashes!
