### ISSUE TITLE
AIM is currently busted

### ISSUE THREAD

**Issue by jnackmclain** [hmxmilohax/rock-band-3-deluxe#715]
cc: @LinosM

**Comment by LinosM** [comment]
cc: @jnackmclain 
https://github.com/hmxmilohax/rock-band-3-deluxe/commit/eb551c232e8cd1613ff4b68ed1a28c5fa18e7f27

**Comment by jnackmclain** [comment]
oops it was meeeeeeeeeeeeeeeee
