### ISSUE TITLE
BNS 150% clarification for those who have a masters degree in complaining

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#721]

**Comment by DarkRTA** [comment]
we have labels for a reason, luna

**Comment by lunalawl** [comment]
> we have labels for a reason, luna

your mom

**Comment by rjkiv** [comment]
> > we have labels for a reason, luna
> 
> your mom

dot com

**Comment by DarkRTA** [comment]
> > > we have labels for a reason, luna
> > 
> > 
> > your mom
> 
> dot com

forward slash go fuck yourself

**Comment by jnackmclain** [comment]
> > we have labels for a reason, luna
> 
> your mom

Brb adding "your mom" as a "to-do"

**Comment by lunalawl** [comment]
added in idk im too lazy to look it up
