### ISSUE TITLE
rbn song updates are messed up

### ISSUE THREAD

**Issue by jnackmclain** [hmxmilohax/rock-band-3-deluxe#732]
I wanted to use YARG Song Updates with YARG and it complains about 6 songs. When I delete songs_updates folder from my song directory, these 6 RBN songs loads and work fine. Could someone help with this issue?
Total Errors: 6

D:\YARG songs\Rock Band Network 1.0\Maylene & The Sons of Disaster - Step Up (I'm On It) - Node UGC_5001644
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update

D:\YARG songs\Rock Band Network 1.0\MC Frontalot - Hassle_ The Dorkening - Node UGC_5005406
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update

D:\YARG songs\Rock Band Network 1.0\Ron Wasserman - American Hero - Node UGC_5002723
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update

D:\YARG songs\Rock Band Network 1.0\Ron Wasserman - Fight Back - Node UGC_5001524
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update

D:\YARG songs\Rock Band Network 1.0\The Stills - Being Here - Node UGC_5001127
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update

D:\YARG songs\Rock Band Network 1.0\Voodoo Pharmacology - Minnesota - Node UGC_5001063
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update

**Comment by jnackmclain** [comment]
cc: @exoticri tbh

**Comment by jnackmclain** [comment]
fixed with #736

**Comment by r0bd0g** [comment]
It seems this error reporting only ever shows 6 errors at a time, so whenever we fix them it just makes room for the next 6 errors to show up.

Total Errors: 6

D:\YARG songs\Rock Band Network 1.0\Maylene & The Sons of Disaster - Step Up (I'm On It) - Node UGC_5001644
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update

D:\YARG songs\Rock Band Network 1.0\MC Frontalot - Hassle_ The Dorkening - Node UGC_5005406
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update

D:\YARG songs\Rock Band Network 1.0\Ron Wasserman - American Hero - Node UGC_5002723
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update

D:\YARG songs\Rock Band Network 1.0\Ron Wasserman - Fight Back - Node UGC_5001524
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update

D:\YARG songs\Rock Band Network 1.0\The Stills - Being Here - Node UGC_5001127
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update

D:\YARG songs\Rock Band Network 1.0\Voodoo Pharmacology - Minnesota - Node UGC_5001063
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update
