### ISSUE TITLE
Some songs have messed up tom markers

### ISSUE THREAD

**Issue by r0bd0g** [hmxmilohax/rock-band-3-deluxe#738]
I'm not sure how it happened but a lot of songs have drums updates with mangled pro tom markers. Text events may have also been impacted. Drum fill locations may have also been impacted. I've made notes about some of the things that I noticed were wrong on the affect songs, but it's not a complete list.

This is a list of songs where issues have been spotted. There are probably more songs than these with issues; keep your eyes peeled idk. I don't have the RB4 updates to cross-reference to make sure none of the changes stem from there.

- firstdate - This update was missing entirely, and has since been readded. Some of the markers have been changed in a way that erroneously removes toms from lower difficulties (at least at m30 and m31). I also noticed that some drum fills have been removed? I'm not sure why the fills at m53, m65, and m97 were removed.
- ifoughtthelaw - This update was missing entirely. It's been readded, but some of the markers/text events might still be wrong, potentially in ways that only impact non-expert difficulties, not sure. Animation text events might be wrong.
- whatsmyageagain - This update was missing entirely. It's been readded, but some of the markers/text events might still be wrong, potentially in ways that only impact non-expert difficulties, not sure.
- redbarchetta - Tom markers missing/too short in measures 24, 46, 86, 98, and 99.
- goodtimesroll - Bad tom markers. Fills removed.
- cmoncmon - Issues reported.

**Comment by SonicSBL** [comment]
So that's why Good Times Roll has cymbals mixed with toms on almost every fill. You might want to check that one out too.

**Comment by r0bd0g** [comment]
I wonder if it's mainly songs that had pro drums updates on disc that are affected. That's been the case so far. But there are over 600 such songs.

**Comment by r0bd0g** [comment]
Yeah confirming the tom markers are wrong and also that some important drum fills have been removed on goodtimesroll.

**Comment by r0bd0g** [comment]
Not quite the same issue, but it was noticed that the pro drums updates are missing from everfalleninlove and acleanshot.

**Comment by jnackmclain** [comment]
all fixed via nightly update reprocessing

**Comment by MJC100** [comment]
acleanshot is still broken for me

**Comment by r0bd0g** [comment]
I glanced through the midi and didn't see any issues.

**Comment by MJC100** [comment]
The intro drum riff to 13 Steps to Nowhere by Pantera is the same for both pro drums and non pro drums. The pro drums chart is different in vanilla rb3 (I think pro drums update might be missing)

**Comment by r0bd0g** [comment]
There is no vanilla rb3 pro drums update. What you describe is a fix from the rb4 updates.

**Comment by MJC100** [comment]
ok good to know thank you
