### ISSUE TITLE
Bugged vocal track on "Space Oddity"

### ISSUE THREAD

**Issue by oiledupscourgegyatt** [hmxmilohax/rock-band-3-deluxe#752]
**Describe the bug**
David Bowie's "Space Oddity" has a bugged solo vocal track, plays a harmony track instead and gives no score. Persists after restart.

**To Reproduce**
1. Play "Space Oddity" on Solo Vocals

**Expected behavior**
I expected the normal track to be there and not a bugged harmony track

**Screenshots**
Video: (excuse my horrible voice)

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/53867821/a5461fe3-05bd-4994-bd53-126020fa1a9b

**DX Settings**
- [dx_settings.txt](https://github.com/user-attachments/files/15994398/dx_settings.txt)
- [dx_modifiers.txt](https://github.com/user-attachments/files/15994401/dx_modifiers.txt)
- [dx_values.txt](https://github.com/user-attachments/files/15994403/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: v1.1.0-nightly
 - Song Count: 4182

**Comment by jnackmclain** [comment]
Nightly currently has a bunch of vocals issues for rb3 and rb3dlc content we are working through with upgraded midis

**Comment by jnackmclain** [comment]
Fixed all of these occurrences in latest nightly
