### ISSUE TITLE
Crash when using the vanilla intro

### ISSUE THREAD

**Issue by Aloquendiar** [hmxmilohax/rock-band-3-deluxe#753]
**Describe the bug**
The game crashes before seeing part of the intro

**To Reproduce**

1. Change the intro to vanilla
2. Restart the game
3. Wait after the EA or Harmonix logos come out.
4. Crash

**Expected behavior**
The game should show the original intro without any problem

**DX Settings**
- [dx_settings.txt](https://github.com/user-attachments/files/16023028/dx_settings.txt)
- [dx_modifiers.txt](https://github.com/user-attachments/files/16023037/dx_modifiers.txt)
- [dx_values.txt](https://github.com/user-attachments/files/16023040/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: v1.1.0-nightly
 - Song Count: 3425

**Comment by DarkRTA** [comment]
issue was a bad external drive

closing
