### ISSUE TITLE
Game freezes after one or two songs when returning to the song list

### ISSUE THREAD

**Issue by Roger-Poa** [hmxmilohax/rock-band-3-deluxe#757]
System: Windows 11 Pro

Crash will happen in both last version and Beta10, running on the latest Dolphin 5.0-21460, after one or two songs.

Installed following instructions from https://wiki.dolphin-emu.org/index.php?title=USB_Passthrough for:

1. two or more mics (VID 046D)
2. Harmonix RB3 Keyboard for Nintendo Wii (VID 1BAD)
3. Rock Band Drum Set (VID 1BAD)

Gameplay is normal, but when returning to the song list, a pop-up will appear:

Warning:
Invalid write to 0x00000000, PC = 0x8000416c

If "Ignore for this session""  is pressed game will freeze.
If "OK" is pressed, address will keep changing, but error will remain

Tried with both Vulkan and DX12

 - Platform: Dolphin
 - Version: 1.1.0 and Beta10
 - Song Count: 1013

**Comment by jnackmclain** [comment]
you ran out of memory. memory issues are plaguing dx right now. i still dont know the fix.
make sure you increase emulated memory size but that wont help too much currently 
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55568980/cdceb617-c1a9-49e6-8f4c-2759bd012662)
