### ISSUE TITLE
Missing background events for RBN 2.0 songs

### ISSUE THREAD

**Issue by Apasher** [hmxmilohax/rock-band-3-deluxe#76]
I haven't extensively tested every RBN 2.0 song, but I've noticed the camera angle doesn't change at all with the ones I tried:

Amberian Dawn
-My Only Star
-Passing Bells
-Lost Soul

**Comment by jnackmclain** [comment]
I just tested all three you listed here in rpcs3 and they all work fine. ill test xenia too but closing as I suspect this was tried in an outdated version of rb3dx
