### ISSUE TITLE
Fatal Crash Intercepted when loading RB3Enhanced

### ISSUE THREAD

**Issue by patricksouza472** [hmxmilohax/rock-band-3-deluxe#761]
**Describe the bug**
When loading the game, it crashes a little after loading the RB3Enhanced plugin, going into a Fatal Crash Intercepted loop.

**To Reproduce**
1. Add RB3Enhanced to dashlaunch plugins list
2. Load RB3 Deluxe
3. Crash loop after intro

**Expected behavior**
Expected the game to work perfectly alongside RB3Enhanced

**Game Information**
 - Platform: Xbox 360
 - Version: 1.1.0-beta10
 - Song Count: 2425

**Additional Context**
Jasper Console, RGH 3.0

**Comment by JarenM03** [comment]
I am having this exact same issue! As soon as I disable the RBEnhanced plug-in, the fatal crashing boot-loop quits. If anyone has any ideas/updates, please do let us know!

**Comment by JarenM03** [comment]
Update: @patricksouza472, in case you're still troubleshooting, I figured out how to fix this issue, with thanks to helpful folks on Discord! So I had my "rb3" folder contents (the "config" and "ui" folders), as well as the "RB3Enhanced.dll" file stored in the root of my Xbox's HDD. Seems the game does not like to run stable when you do that, and much rather prefers to crash-loop endlessly.

Instead, copy both your individual config/ui folders, as well as your .dll file, over to the directory in which you have Rock Band 3 .xex files stored. For example, mine were located in HDD:/Content/0000000000000000/Rock Band 3. As soon as I copied the "config" folder, the "ui" folder, and the .dll file into where the rest of my RB3 files are, stability seems to be great thus far!

**Comment by SuperRiderTH** [comment]
I know this issue is closed, but I just wanted to chime in and say that I found this issue because I was having issues *closing* the game with a fatal crash loop. But I too had my RB3Enhanced files on the root of the HHD. Moving them into the game directory stopped the crashing.

**Comment by garland-tim** [comment]
Just commenting because this was the first result when searching. I found that the .ini could be on the root of the drive and the .xex plugin can be anywhere, but everything else needed to be in the game folder. I was having the same issue as @SuperRiderTH.
