### ISSUE TITLE
"A Jagged Gorgeous Winter" drums are broken

### ISSUE THREAD

**Issue by SonicSBL** [hmxmilohax/rock-band-3-deluxe#771]
**Describe the bug**
When playing "A Jagged Gorgeous Winter" on drums, pro or not, no notes can be hit in normal play.

**To Reproduce**
1. Go to Quickplay.
2. Play "A Jagged Gorgeous Winter" on drums.
3. Play the song normally and miss every note.

**Expected behavior**
When played correctly, notes should register as hit.

**Screenshots**
N/A

**DX Settings**
- [dx_modifiers.txt](https://github.com/user-attachments/files/16134488/dx_modifiers.txt)
- [dx_settings.txt](https://github.com/user-attachments/files/16134490/dx_settings.txt)
- [dx_values.txt](https://github.com/user-attachments/files/16134492/dx_values.txt)

**Game Information**
 - Platform: PS3 HW
 - Version: 1.1.0-nightly+c85ec06
 - Song Count: 681

**Additional context**
There may be other songs with this issue.

**Comment by r0bd0g** [comment]
The update midi has two drum tracks in it for some reason.

**Comment by jnackmclain** [comment]
oops
and to think i thought doing these manually would lead to no issues

**Comment by jnackmclain** [comment]
fixed in latest nightly
