### ISSUE TITLE
Rock Band drums are recognized as Pro Guitar on PS3

### ISSUE THREAD

**Issue by dante4001** [hmxmilohax/rock-band-3-deluxe#78]
I have a PS3 with Rebug 4.82.4 D-REX and Band Hero Drum Controller
With RB3DX installed, the drums are recognized as Pro Guitar, so you can choose a pro guitar or pro bass track. But if I uninstall RB3DX by applying official 1.05 patch, everything works as expected

**Comment by jnackmclain** [comment]
You need to download the nightly build marked as [RB3DX-PS3-stock-instrument-mapping](https://nightly.link/hmxmilohax/rock-band-3-deluxe/workflows/build/main/RB3DX-PS3-stock-instrument-mapping)
