### ISSUE TITLE
The "New Personal Best" pop-up does not check the instrument the score was saved under

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#785]
**Describe the bug**
For example, if you have a song played on bass only, and you switch to guitar and beat the bass score on guitar, it says "New Personal Best"

**Expected behavior**
The "New Personal Best" thing tracks the score for the instrument it was saved under

**Game Information**
 - Platform: Xbox 360
 - Version: https://github.com/hmxmilohax/rock-band-3-deluxe/commit/dc3dc851f8826780f1bc2ae3c09eaf5192ec2b99
 - Song Count: 5345

**Comment by jnackmclain** [comment]
this is a guitar bass quirk with the game. When the game runs players through the menus, it assigns you as a guitar by default, then as bass after you choose bass.
The high score is fetched on song selection, before you choose instrument.
So if you play a song as bass, choose the same song, but then select guitar instead, you will see this behavior.

I can't really fix that unfortunately.
