### ISSUE TITLE
Cycling guitar FX seems to be busted on HMX's part

### ISSUE THREAD

**Issue by LocalH** [hmxmilohax/rock-band-3-deluxe#796]
**Describe the bug**
Regardless of the setting's value, the game always seems to use the flanger FX.

**To Reproduce**
1. Cycle to different FX (although there is no feedback as to which is selected), whether in a song or not
2. Play a song and either activate or reach a solo section

**Expected behavior**
The guitar FX should cycle through the different types of FX.

**Game Information**
 - Platform: RPCS3
 - Version: latest develop, with or without modifications to show the user the selected FX

**Additional context**
I was looking into adding visual feedback to the menu selection, so the user could see the current FX setting. In doing so, I found that the setting never actually seems to change. We're using the same scripting that HMX used for the debug purpose, so it seems like the function is busted on their end. What HMX does is cycle the variable $test_guitar_fx through the values 0 to 4, then cycles through each active player and calls that player's update_guitar_fx function. This may be unfixable, and the feature may need to be removed.

**Comment by Lynxeption** [comment]
small little update on this from my experience:

the guitar FX cycling *does* work, it seems like it only picks up when using guitar binds in Rock Band mode on RPCS3. however, the effect order seems to be busted, i did some small research using the solos in Train Kept A Rollin' RB1 and it goes as follows:

Wah -> chorus
Flanger -> wah
Echo -> flanger
Chorus -> echo
None -> nothing

not sure what the hell triggered this "disorder" but surely enough the FX cycles and seems to work, so everything alright there

**Comment by jnackmclain** [comment]
fixed recently
