### ISSUE TITLE
Band streak doesn’t account for the entire band

### ISSUE THREAD

**Issue by exoticri** [hmxmilohax/rock-band-3-deluxe#799]
**Describe the bug**
When playing online or locally with 3 other laned instruments, the band streak will only pick one player to account for.

**To Reproduce**
1. Enable band note streak counter
2. Get a lobby with other players on laned instruments
3. Start playing a song
4. See the streak only move when one player plays

**Expected behavior**
The streak is supposed to account for everyone’s playing

**Game Information**
 - Platform: Xbox 360
 - Version: latest nightly
 - Song Count: >5000

**Comment by jnackmclain** [comment]
removed so fixed
