### ISSUE TITLE
Character Customizer Crashing (Wii, Beta Build)

### ISSUE THREAD

**Issue by APerson7778** [hmxmilohax/rock-band-3-deluxe#803]
Whenever the character customizer is opened, the game crashes immediately

1. Not sure if this affected anything, but I had a save from the original Rock Band 3
2. Select "customize character"
3. Game goes through the animation sequence
4. Game crashes

Expected behavior:
Character customizer opens, allowing the character to be customized

**Game Information**
 - Wii (Dolphin)
 - Version: 1.1.0-beta11
 - Song Count: No extra songs (83)

**Comment by jnackmclain** [comment]
This is fix in nightly.

**Comment by APerson7778** [comment]
@jnackmclain The nightly build crashes before even getting to the main menu

**Comment by jnackmclain** [comment]
I may have forgotten that detail, apologies, but I can assure you, character customization is fixed when I fix the slight issue of instant crashing

**Comment by APerson7778** [comment]
@jnackmclain I understand
