### ISSUE TITLE
Nightly Build Crashes at Main Menu (Wii, Dolphin)

### ISSUE THREAD

**Issue by APerson7778** [hmxmilohax/rock-band-3-deluxe#805]
**Describe the bug**
The game crashes immediately upon trying to load main menu

**To Reproduce**
1. Start game
2. Wait through intro logos
3. Press button to start game
4. Game crashes

**Expected behavior**
Game goes into main menu

**Game Information**
 - Platform: Wii (Dolphin)
 - Version: 1.10-nightly
 - Song Count: No extra songs (83)

**Additional context**
Beta build worked, but often crashed after songs and crashes at the character customizer

**Comment by jnackmclain** [comment]
yeah i haven't figured out why yet but ive seen this too. i have a local change that lets me get into the game but overshell is completely broken as well. have to investigate further. sorry
