### ISSUE TITLE
Consistent game crash after playing Call Me by Blondie

### ISSUE THREAD

**Issue by davesilva** [hmxmilohax/rock-band-3-deluxe#808]
**Describe the bug**
In v1.1.0-beta11 the game crashes every time when returning to menu after playing Call Me by Blondie. This particular crash does not happen in v1.1.0-beta10.

**To Reproduce**
1. Start playing Call Me by Blondie
2. Pause the game and select "back to music library"
3. Game will crash as soon as library appears

**Expected behavior**
Game returns to music library without crashing

**DX Settings**
- `dx_settings.dta`: [dx_settings.txt](https://github.com/user-attachments/files/16444837/dx_settings.txt)
- `dx_modifiers.dta`: [dx_modifiers.txt](https://github.com/user-attachments/files/16444842/dx_modifiers.txt)
- `dx_values.dta`: [dx_values.txt](https://github.com/user-attachments/files/16444845/dx_values.txt)

**Game Information**
 - Platform: Xbox 360
 - Version: v1.1.0-beta11
 - Song Count: 1226

**Comment by zanesix** [comment]
To add onto this, even just scrolling past the song manages to break author finder until you play a different song.
![10 0 0 99-image20](https://github.com/user-attachments/assets/3f25d5eb-23c9-4e87-a1bc-1b19ee0c7ea2)

**Comment by zanesix** [comment]
Fixed as of the authorfinder4all update

**Comment by lunalawl** [comment]
cool

**Comment by jnackmclain** [comment]
oh nice i wasnt even going for that
