### ISSUE TITLE
How to test video backgrounds?

### ISSUE THREAD

**Issue by AARP41298** [hmxmilohax/rock-band-3-deluxe#81]

**Comment by jnackmclain** [comment]
create a bik file using radvideotools.

Make sure the bik is below 50mb in size or it will not work

I recommend not going above 1280x720 either

Place the bik file in the location of the dlc, named as the shortname

So this would be inside a con/live file on xbox or in the dev_hdd0/game/BLUSxxxx/songs/shortname/shortname.bik

biks cannot be loaded from inside an ark
