### ISSUE TITLE
Instruments supported for Mac version 

### ISSUE THREAD

**Issue by stevesmash23** [hmxmilohax/rock-band-3-deluxe#817]
Can’t figure out what instruments are supported for Mac version and how would I get them to work? I have all Xbox one instruments trying to use them if possible. I am able to connect to a Xbox one controller via Bluetooth but no other instruments would this even be possible to use Xbox one instruments?

**To Reproduce**
1. Try and connect various controllers on Mac 

**Expected behavior**
Ability to connect various instruments to Mac for gameplay

**Game Information**
 - Platform: Using MacBook Pro M2 running rpcs3
 - Version: up to date

Additional context
Want to see/test what instruments are possible to use on Mac version. Also have Xbox 360 instruments + legacy adapter if possible that route somehow.

**Comment by jnackmclain** [comment]
This is not a DX bug. RPCS3 on mac should be using SDL afaik, i would recommend asking around in milohax or consulting the instrument guide rather than making an issue here
https://rb3pc.milohax.org/english/controllers/

**Comment by carlmylo** [comment]
Mac is a bit of an interesting case because, to my knowledge, [the Xbox 360 driver](https://github.com/360Controller/360Controller) that exists no longer works. That and the forks that exist that try to fix this require disabling security features which is not cool. I'm not entirely knowledgeable on Mac since it's not my main platform. Hopefully someone can correct me if I'm wrong.

**Comment by shny-scott** [comment]
> I am able to connect to a Xbox one controller via Bluetooth but no other instruments 

To my knowledge, none of the Xbox One instruments support Bluetooth. They only connect with the proprietary Xbox One controller dongle, I don't know if that's supported at all on Mac.

As others have said, far out of scope for what Deluxe is capable of. Changing scripts in Rock Band 3 will not add Bluetooth support to a guitar that physically does not have Bluetooth hardware.
