### ISSUE TITLE
Author finder only gets information for the first song played (PS3)

### ISSUE THREAD

**Issue by Aloquendiar** [hmxmilohax/rock-band-3-deluxe#823]
**Describe the bug**
When playing a song it will show the author data, but when moving to a new song the data will not be updated and only the data of the first song will remain.

**To Reproduce**
1. Start the game
2. Play any song on any instrument
3. Return to the song library
4. Choose another song with a different author
6. The information will not be updated

**Expected behavior**
Author details must be displayed correctly

**DX Settings**
- `dx_settings.dta`: [dx_settings.txt](https://github.com/user-attachments/files/16575437/dx_settings.txt)

- `dx_modifiers.dta:` [dx_modifiers.txt](https://github.com/user-attachments/files/16575439/dx_modifiers.txt)

- `dx_values.dta`: [dx_values.txt](https://github.com/user-attachments/files/16575443/dx_values.txt)

**Game Information**
 - Platform: PS3
 - Version: 1.1.0-nightly+c173e8f
 - Song Count: 3519

**Comment by SonicSBL** [comment]
To add to this, many items don't appear properly whether they're on or off. I tried enabling the album, and it would often show the first album loaded or no album at all.

**Comment by LocalH** [comment]
This may also be the root cause of the countdown issue. I bet section names are getting stuck too.

**Comment by jnackmclain** [comment]
latest nightly should fix this im super dumb

**Comment by jnackmclain** [comment]
specifically this one
https://github.com/hmxmilohax/rock-band-3-deluxe/actions/runs/10341750968
