### ISSUE TITLE
"Soak Up the Sun" crashes the game

### ISSUE THREAD

**Issue by SonicSBL** [hmxmilohax/rock-band-3-deluxe#825]
**Describe the bug**
When previewing "Soak Up the Sun" by Sheryl Crow, the game crashes. Even if you select the song before the preview can play, the game crashes when trying to load the song.

**To Reproduce**
1. Go to music library
2. Scroll down to 'Soak Up the Sun'
3. Crash

**Expected behavior**
The song should preview on hover and load after being selected, just like any other.

**Screenshots**
N/A

**DX Settings**
- [dx_settings.txt](https://github.com/user-attachments/files/16576093/dx_settings.txt)
- [dx_modifiers.txt](https://github.com/user-attachments/files/16576094/dx_modifiers.txt)
- [dx_values.txt](https://github.com/user-attachments/files/16576095/dx_values.txt)

**Game Information**
 - Platform: PS3 HW
 - Version: 1.1.0-nightly+47bd958
 - Song Count: 711

**Additional context**
This didn't happen in nightly build 7236DAC or with any other RB4-era songs. Also, the preview crash only happens with the difficulty rings setting, not the dots.

**Comment by SonicSBL** [comment]
Updating to the latest nightly, the song loads and plays, but then crashes when returning to the music library. This is true of any song.

Updated files:
[dx_modifiers.txt](https://github.com/user-attachments/files/16602685/dx_modifiers.txt)
[dx_settings.txt](https://github.com/user-attachments/files/16602686/dx_settings.txt)
[dx_values.txt](https://github.com/user-attachments/files/16602687/dx_values.txt)

**Comment by jnackmclain** [comment]
Fixed it with 46f72265607d674361f2c574747b484c117ae3e3! SHEEESH this was actually quite frustrating
should have no more song select crashes
still working on hooking up author finder for on disc songs
