### ISSUE TITLE
One Armed Scissor crash

### ISSUE THREAD

**Issue by trishiskukky** [hmxmilohax/rock-band-3-deluxe#826]
**Describe the bug**
When confirming your difficulty before playing "One Armed Scissor" by At The Drive-In, the game will unexpectedly crash. This happens on every instrument.

**To Reproduce**
1. Pick "One Armed Scissor" in your library.
2. Picking any difficulty on any instrument will crash your game.

**Expected behavior**
Being able to play the best RB3 song.

**Screenshots**

**DX Settings**
[dx_values.txt](https://github.com/user-attachments/files/16576293/dx_values.txt)
[dx_modifiers.txt](https://github.com/user-attachments/files/16576294/dx_modifiers.txt)
[dx_settings.txt](https://github.com/user-attachments/files/16576295/dx_settings.txt)

**Game Information**
 - Platform: RPCS3
 - Version: this one
![image](https://github.com/user-attachments/assets/4e59c2be-a37a-447e-9f4c-4e1634fa616a)

 - Song Count: 5656

**Additional context**

**Comment by jnackmclain** [comment]
fixed in nightly *author finder still not running on disc songs but wont crash
