### ISSUE TITLE
Crash on startup on latest RPCS3

### ISSUE THREAD

**Issue by paulsd95** [hmxmilohax/rock-band-3-deluxe#83]
So I was playing an older version of RB3DX, probably from early november, after updating RPCS3, with no issues. Then I update RB3DX to current, then I get a crash on startup, with a "The PS3 application has likely crashed, you can close it." on screen.

F {PPU[0x1000000] Thread (main_thread) [0x008ed15c]} VM: Access violation reading location 0x8 (unmapped memory)
[RPCS3.log](https://github.com/hmxmilohax/rock-band-3-deluxe/files/10191640/RPCS3.log)
RPCS3 log attached.

**Comment by jnackmclain** [comment]
I do not see the same behavior on latest rpcs3 and latest rb3dx.
Try starting over and making sure it was installed properly to the update directory.

**Comment by paulsd95** [comment]
Ok I hit the new git reset file I didn't see before, resetting some custom setting or another I had. Looks like it's working now.

Side note the 'new' menu screen isn't laggy anymore. Probably due to upgrading hardware to an i5-12400 and an RTX 3050
