### ISSUE TITLE
Eyebrow icons in character creator look broken

### ISSUE THREAD

**Issue by Vois30** [hmxmilohax/rock-band-3-deluxe#832]
When selecting eyebrows when making a new character, the graphics for showing the eyebrows either don’t align or are broken

1. Begin creating a character
2. Go to “Modify Head”
3. Then go to “Customise Face”
4. Go to “Eyebrows”
5. See the fucked up icons

**Game Information**
 - Platform: Xbox 360 (haven’t tried other platforms)
 - Version: 1.1.0 nightly (current nightly build)

![image](https://github.com/user-attachments/assets/e8497fee-cc92-4e31-bd1f-abbaa86b9b33)

**Comment by jnackmclain** [comment]
fixed in latest dev
