### ISSUE TITLE
Faild to compile wii version

### ISSUE THREAD

**Issue by AARP41298** [hmxmilohax/rock-band-3-deluxe#84]
I just clone the repo and execute the `_build_wii.bat`

But it fails with the next error:
`Executing file changes
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Todo\infotec\repos\wiirb3dx\_build\wii\main_wii_0.ark'.
File name: 'C:\Todo\infotec\repos\wiirb3dx\_build\wii\main_wii_0.ark'`

**Comment by jnackmclain** [comment]
You must have extracted the vanilla ark files from a base rb3 Wii disk to that directory before running build Wii script
