### ISSUE TITLE
Note streak box present in solo vox despite not functioning

### ISSUE THREAD

**Issue by shny-scott** [hmxmilohax/rock-band-3-deluxe#845]
**Describe the bug**
The note streak box does not go up when vox phrases are hit or lose its green color when a phrase is missed, which I assume is an unfixable limitation of scripting. However, the box is still present when playing vox with no other instruments.

**To Reproduce**
1. Deluxe Settings > Advanced > In-Game HUD > Note Counter: Single
2. Play a song in vocals or harmonies without another instrument present.

**Expected behavior**
The nonfunctional box should not show up, just like if it was disabled.

**Screenshots**
![image](https://github.com/user-attachments/assets/e598437f-9a6e-4c47-9e95-1b7217ae76c5)

**Game Information**
 - Platform: RPCS3
 - Version: Nightly, self built like one commit ago
 - Song Count: 4089

**Comment by jnackmclain** [comment]
was removed so fixed
