### ISSUE TITLE
Feelin' Alright (beta song) needs lipsync

### ISSUE THREAD

**Issue by glitchgod0** [hmxmilohax/rock-band-3-deluxe#850]
**Describe the bug**
Feeling Alright lacks lipsync so the singer just babbles

**Expected behavior**
The lips should sync to the song

**Comment by SonicSBL** [comment]
Last time I checked, that song had almost no animations at all. I don't think Harmonix got that far.

**Comment by glitchgod0** [comment]
yeah i noticed the anims weren't lively. there could be other aspects missing aswell.

**Comment by jnackmclain** [comment]
has been removed
