### ISSUE TITLE
Album covers changed that don't need changing.

### ISSUE THREAD

**Issue by GalaxisBeast** [hmxmilohax/rock-band-3-deluxe#853]
A bunch of album covers are changed to way worse versions. Such as Hail to the King, Unholy Confessions and Let There Be Rock. ![image](https://github.com/user-attachments/assets/d5f30537-f03f-41d5-b949-c83ed8d32c75)![image](https://github.com/user-attachments/assets/07543e34-383c-4e5a-bc8d-4ac8dbdc8979)![image](https://github.com/user-attachments/assets/4b961212-db8b-4a59-a0ec-ce6ca8b2823d)

**Comment by jnackmclain** [comment]
@exoticri fixed these
