### ISSUE TITLE
Guitar Lanes appearing where they shouldn't be

### ISSUE THREAD

**Issue by Rebster505** [hmxmilohax/rock-band-3-deluxe#855]
**Describe the bug**
Lanes sometimes appear in songs on guitar that wouldn't have them in vanilla Rock Band 3

**To Reproduce**
1. Leave all lane modifiers on default
2. select Pre-Chorus 2 on No More Tears in practice mode
3. Trill lane will appear where there shouldn't be one.

This also affects Dr. Feelgood in GTR SOLO 2B. There could well be more examples, but these are the two I can remember

**Screenshots**
![image](https://github.com/user-attachments/assets/9f51a30d-713e-45ed-8fdb-5bbcd23c35d8)
![image](https://github.com/user-attachments/assets/41edeaac-dcff-4193-b836-060844f7aa5d)

**DX Settings**
- `dx_settings.dta`: [dx_settings.txt](https://github.com/user-attachments/files/16753062/dx_settings.txt)
- `dx_modifiers.dta`: [dx_modifiers.txt](https://github.com/user-attachments/files/16753087/dx_modifiers.txt)
- `dx_values.dta`: [dx_values.txt](https://github.com/user-attachments/files/16753089/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: [eg. 1.1.0-beta11]
 - Song Count: 731

**Additional context**
I am on the european version of Rock Band 3, But I don't know how much that really affects things.

**Comment by jnackmclain** [comment]
This is not a bug, this is a feature.
These songs as well as others got lane upgrades in rb4 which are present in deluxe. As well as a multitude of song upgrades. No chart changes were made outside of the rb4 stuff however. all rb4 did was add lanes. and all we do is add pro instruments.
You can simply turn lanes off in modifiers in dx

**Comment by Rebster505** [comment]
But would that just remove the lanes that Rock Band 4 would add? or would it remove all lanes?
Is there an option to just have the vanilla Rock Band 3 lanes?

**Comment by Rebster505** [comment]
Oh thanks for the super speedy reply by the way. I did not expect that.

**Comment by LocalH** [comment]
Each time our CI makes a build, there should also be a "FUB Edition" that has only RB3 stock midi updates. I don't remember if we also apply other metadata updates in that build, but it would have the same lanes that you'd get by playing a given song on vanilla RB3.
