### ISSUE TITLE
Missing songs for the Rock Band spreadsheet

### ISSUE THREAD

**Issue by LostChris894** [hmxmilohax/rock-band-3-deluxe#861]
The songs by Honest Bob and the Factory-to-Dealer Incentives, (Hey and I Don't Want to Hear About Your Crappy Boyfriend) are not on the Rock Band song spreadsheet. They were Rock Band Network 2.0 songs.

**Comment by shny-scott** [comment]
This isn't an issue with RB3DX specifically and should probably be raised somewhere else instead.

That being said, this does seem to be an issue specifically with individual CONs if an artist's name is longer than the entire filename limit. I can confirm all 3 Honest Bob songs are present in the full RBN packs and the curated "RBN Bangers" setlist in the Milohax Discord.

**Comment by MsHillesRGH** [comment]
green day longview wasn't in there

**Comment by lunalawl** [comment]
if you are missing longview please update RB3Enhanced to nightly and clear your song cache
