### ISSUE TITLE
2 Harmony Bars

### ISSUE THREAD

**Issue by ItsRandomDude** [hmxmilohax/rock-band-3-deluxe#867]
Having a second harmony bar for when the harmony singers are doing separate things. Don't know if this is feasible with .dta files, more or less just curious.

The vocal break section of Sugar, We're Going Down - Fall Out Boy for an example (Had a video, too many mbs)
![image](https://github.com/user-attachments/assets/0c4f69b5-ee16-4deb-a329-1d7e9e99f472)

**Comment by DarkRTA** [comment]
This is unfortunately not possible with deluxe alone as it would require some pretty serious modifications to the game's code itself.
