### ISSUE TITLE
New Play A Show Options Not Working on PS3

### ISSUE THREAD

**Issue by CorndogWaterGrab** [hmxmilohax/rock-band-3-deluxe#879]
I'm running the 1.1.0-beta12 build on my PS3 and after playing the first song, none of the song options appear correctly.
My options were:

1. A song by Unknown
2. Please Don't Leave Me _P!nk_
3. A song from Unknown _Unknown_
4. A Unknown tier song
5. A Unknown song
6. Refresh Options

Choosing any option will still give you a song and you can play the show as normal. Refresh Options doesn't affect the Unknown issue.

**Comment by jnackmclain** [comment]
Known current bug

**Comment by chintwo123** [comment]
Seeing same thing here

![IMG_7211](https://github.com/user-attachments/assets/aa38da8e-6d0e-4286-be56-b928b60af7c7)

**Comment by jnackmclain** [comment]
fixed
