### ISSUE TITLE
PS3 HEN Game is in German Language

### ISSUE THREAD

**Issue by BobRooney1979** [hmxmilohax/rock-band-3-deluxe#881]
Hello, i have a PS3 slim with hen.
i have installed my german version on my hdd and renamed it into Rock Band 3 Europe.
now i want to install rb3 deluxe.  i have dowloaded the version BLUS30463 and installed it also on my hdd.
when i start blus3063 it is in german and deluxe doesnt work.

THX for your help

**Comment by jnackmclain** [comment]
please join the discord for further troubleshooting installations
https://discord.gg/milohax
