### ISSUE TITLE
Song metadata doesn't load in music library on PS3

### ISSUE THREAD

**Issue by SonicSBL** [hmxmilohax/rock-band-3-deluxe#884]
**Describe the bug**
When previewing a song in the music library with difficulty rings on, the song's extended metadata (author, source, etc.) never appears, whether it's set to load automatically, or by holding the button.

**To Reproduce**
1. Go to Options > Deluxe Settings > Advanced > In-game HUD
2. Set "Song Select Diff" to "Rings" and "Hold for Metadata" to "On"
3. Go to the music library
4. Preview any song
5. Hold the blue fret (or equivalent)
6. The load metadata message disappears and that's it

**Expected behavior**
The additional metadata should load.

**Screenshots**
N/A

**DX Settings**
- [dx_settings.txt](https://github.com/user-attachments/files/17237634/dx_settings.txt)
- [dx_modifiers.txt](https://github.com/user-attachments/files/17237636/dx_modifiers.txt)
- [dx_values.txt](https://github.com/user-attachments/files/17237637/dx_values.txt)

**Game Information**
 - Platform: PS3 HW
 - Version: 1.1.0-nightly+10dcd55
 - Song Count: 707

**Additional context**
This bug was present at least a month before beta12. The source icons never appear either.

**Comment by SonicSBL** [comment]
Okay, I just discovered it only works for RB3 disc songs

**Comment by jnackmclain** [comment]
same issue as #879
