### ISSUE TITLE
Mapping drum instrumen on rb3 ps3 dualshock 3

### ISSUE THREAD

**Issue by Safari78** [hmxmilohax/rock-band-3-deluxe#89]
Can we got this mapping on rb3 on ps3 with dualshock 3? 
L2 = red
L1 = yellow
R2 = blue
R1 = green
X = kick

**Comment by jnackmclain** [comment]
grab [joypad.dta](https://github.com/hmxmilohax/milo-script-library/blob/main/rb3/360/(..)/(..)/system/run/config/joypad.dta) and place it in the rb3dx repo in `\_ark\(..)\(..)\system\run\config`. you can edit any controller mapping to whatever you like, the mappings start at line 751 in this dta, just have to rebuild the ark and reinstall.
I won't change default joypad mappings on the repo, im not about to introduce issues with controls people may already be used to.
