### ISSUE TITLE
AIM player count fix for Discord RPC causes the song timer to no longer be positioned properly

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#890]
commit https://github.com/hmxmilohax/rock-band-3-deluxe/commit/8d044b2cb434d7484ddb2faef3bba76a38ad4852

should be below the streak box

![posex](https://github.com/user-attachments/assets/1410d162-bb8c-44be-ad3c-0fe45a013c96)

**Comment by jnackmclain** [comment]
fixed in latest dev btw
