### ISSUE TITLE
Track camera números originais 

### ISSUE THREAD

**Issue by Msx325** [hmxmilohax/rock-band-3-deluxe#896]
Acabei mexendo na track camera sem querer aí queria saber os números originais

**Comment by DarkRTA** [comment]
If you screwed with the experimental track camera settings restarting the game should fix it.

Also in the future please make an attempt to use english in the issue tracker if you are able to. Almost all of the dev team can only speak english and won't be able to properly handle anything reported in he reported in portuguese.
