### ISSUE TITLE
Melhorias

### ISSUE THREAD

**Issue by Msx325** [hmxmilohax/rock-band-3-deluxe#897]
Algumas ideias seriam:
Tirar isso de jogar no expert pra ganhar estrelas douradas,
Retirar efeitos de luz branca muito forte,
nas opções deluxe ter mais opções para deixar o jogo mais parecido com o rock band 1 e o 2 no mais fiel possível
no teclado fazer o som da distorção quando jogado no controle(no som da distorção),
No rock band 2 a barra de overdrive piscava forte e quando acertava as notas saiam umas ondas legais tipo umas ondas de vento
E na bateria se der pra colocar o pedal no botão X(laranja) e o resto no (verde, vermelho, amarelo, azul) ia ficar mais fácil de jogar

**Comment by DarkRTA** [comment]
Almost all of these are not possible with oue current tools but in regards to the drum bindings you *can* already do this.

Unfortunately custom bindings aren't fully fleshed out yet and most notably won't save between sessions. We do have an active issue open for that.
