### ISSUE TITLE
Song metadata special characters shown as asterisks

### ISSUE THREAD

**Issue by clwalker85** [hmxmilohax/rock-band-3-deluxe#900]
**To Reproduce**
1. Go to Play Now -> Quickplay -> Choose Songs
2. Find "Oye Mi Amor"
4. See asterisks in Album title.

**Expected behavior**
I expected to see accented letters, tildas, and question marks where appropriate in song metadata, particularly for non-English album titles. If I press the triangle button to see full song details, the correct album title is shown.

**Screenshots**
![PXL_20241019_220148616 MP](https://github.com/user-attachments/assets/d1bdd829-72f9-4651-b0f9-f26c10abc597)

**DX Settings**
Configuration: [config_BLUS30463.txt](https://github.com/user-attachments/files/17447837/config_BLUS30463.txt)

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-nightly+d7fc9bb
 - Song Count: 2485

**Additional context**
In the previous build I installed, this data wasn't showing for Rock Band 3 on-disc songs at all. Seems to be a recent change.

**Comment by jnackmclain** [comment]
![image](https://github.com/user-attachments/assets/d73ccd28-9f6b-4b22-8e48-31578a1ef150)

**Comment by jnackmclain** [comment]
same as #849
