### ISSUE TITLE
Holding blue song metadata does not activate additional data (PS3)

### ISSUE THREAD

**Issue by Aloquendiar** [hmxmilohax/rock-band-3-deluxe#901]
**Describe the bug**
Metadata does not appear

**To Reproduce**
1. Go to Play Now -> Quickplay -> Choose Songs
2. Holding blue button in random song

**Expected behavior**
Load metadata and origin icon

**Screenshots**
![20241020_234428](https://github.com/user-attachments/assets/18a7fe08-a420-4be6-8138-a5210b871084)
![20241020_234433](https://github.com/user-attachments/assets/a6bb94b1-b53d-4f92-96d9-98d9915c1ed6)

**Game Information**
 - Platform: PS3
 - Version: 1.1.0-nightly+2b30f18
 - Song Count: 3881

**Additional context**
In previous builds the metadata were displayed correctly

**Comment by jnackmclain** [comment]
same issue as #879
