### ISSUE TITLE
[PS3 Hardware] Song key keyboard overlay does not update

### ISSUE THREAD

**Issue by carlmylo** [hmxmilohax/rock-band-3-deluxe#904]
**Describe the bug**
As Author Finder doesn't work on anything but on-disc consistently, songs are stuck on with the previous song key highlights.

**To Reproduce**
1. Enable the Song Key highlight function
2. Play a song that's not on-disc
3. If the player previously played an on-disc song, it'll stay on that. Otherwise, it will be blank.

**Expected behavior**
The song key should update.

**Screenshots**
N/A

**DX Settings**
[dx_settings.dta.txt](https://github.com/user-attachments/files/17532866/dx_settings.dta.txt)
[dx_values.dta.txt](https://github.com/user-attachments/files/17532867/dx_values.dta.txt)
[dx_modifiers.dta.txt](https://github.com/user-attachments/files/17532868/dx_modifiers.dta.txt)

**Game Information**
 - Platform: PS3
 - Version: 4a62995
 - Song Count: 3068

**Additional context**
PS3 with CFW (latest)

**Comment by SonicSBL** [comment]
This works now, but many songs have the wrong song key information or are missing it entirely. I'll submit a PR for that soon.

**Comment by jnackmclain** [comment]
Oh right makes sense. I'll close this issue for now. Appreciate the incoming pr!
