### ISSUE TITLE
Lego Rock Band hud

### ISSUE THREAD

**Issue by UltraDanHR** [hmxmilohax/rock-band-3-deluxe#906]
Please add everything related to Lego Rock Band so we can fully replicate the HUD
(Would be killer to also ask for clothes replacements but that's probably hard if not impossible)

**Comment by glitchgod0** [comment]
LRB gems are quite hard, the lego piece effect is done through a model which we cant really change properly yet. you can use LRB textures in track themes to get quite close.

**Comment by UltraDanHR** [comment]
Aren't instruments and such doable though?

**Comment by jnackmclain** [comment]
No, because the two game's file formats are completely different
