### ISSUE TITLE
Accents appearing as asterisks

### ISSUE THREAD

**Issue by UltraDanHR** [hmxmilohax/rock-band-3-deluxe#907]
**Describe the bug**
All accents appear as asterisks, at least on spanish translation. Not always though.

**To Reproduce**
Switch language to spanish, check clothes in shop, check that many have *

**Expected behavior**
The correct accent letter should appear

**Screenshots**
![imagen](https://github.com/user-attachments/assets/a80067de-edbb-40bb-8f80-860b05605697)
**Game Information**
 - Platform: RPCS3
 - Version: v1.1.0-beta12
 - Song Count: (all? didn't count)

**Comment by jnackmclain** [comment]
![image](https://github.com/user-attachments/assets/ba92c23f-e45b-47bf-b21f-b5244e676c8d)
fixed
