### ISSUE TITLE
[Xbox 360 Hardware] Performance Issues Using New Song Progress Bar

### ISSUE THREAD

**Issue by ThePixelPolygon** [hmxmilohax/rock-band-3-deluxe#914]
**Describe the bug**
During gameplay, the game will stutter when the new progress bar is enabled, and gets progressively worse as the song continues.

**To Reproduce**
1. Play any song with all instruments, ensuring the progress bar is turned on.
2. Observe song in its entirety.
3. Play the same song without the progress bar enabled.

**Expected behavior**
The game should run at a constant framerate in both cases.

**Game Information**
 - Platform: Xbox 360
 - Version: 1.1.0-nightly (downloaded on November 7, 2024)
 - Song Count: 4697

**Additional Context**
The severity of the lag may be affected by the amount of instruments in play. This bug was discovered while playing in all instruments mode with a song that had all instruments charted, and was later checked against a song where pro keys had no part. The lag was significantly more noticeable in the former case.

**Comment by jnackmclain** [comment]
Fixed in latest nightly
