### ISSUE TITLE
[PS3HEN] Guitar "Echo" effect audio while OD/solo and lag in the latest nightly

### ISSUE THREAD

**Issue by MandyR0cks** [hmxmilohax/rock-band-3-deluxe#915]
**Describe the bug**
The guitar audio goes to the "Echo" effect from the RB guitar when deploying overdive or going to the solo, and I'm using a Guitar Hero guitar.
The game also starts losing frames when playing in the middle of the song, it has the same feeling as when you turn off Vsync in games.

**To Reproduce**
1. Choose a song that is at least 4 minutes long
2. If the song has a lot of lightning changes, the background will start to have frame issues
3. The highway will start stuttering in the middle of the song.

**Game Information**
 - Platform: PS3 Hardware
 - Version: v1.1.0-nightly (November 7)
 - Song Count: 4648

**Comment by lunalawl** [comment]
This is because the guitar FX toggle in settings is set to "chorus" by default, I can change the default setting but for now go to Deluxe Settings > Audio & SFX and set Guitar FX to None

**Comment by MandyR0cks** [comment]
oh I didn't know this was a modifier! My bad 😅

Thank you for explaining! 😄

**Comment by jnackmclain** [comment]
Lag is also fixed in latest nightly

**Comment by lunalawl** [comment]
Guitar FX now set to none by default in [b4781f3](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/b4781f3cd1fc89e669b5e2846268c3698be590a2)
