### ISSUE TITLE
Submenu reboot button does not reboot

### ISSUE THREAD

**Issue by MetricCepheid** [hmxmilohax/rock-band-3-deluxe#919]
**Describe the bug**
Submenu reboot button does not reboot

**To Reproduce**
1. Overshell Menu
2. Options
3. Deluxe Settings
4. Track Theme
5. Default
6. Reboot Game

**Expected behavior**
Game Reboots

**Videos**
https://youtu.be/fOAEJ7d3ZRs

**DX Settings**
[dx_modifiers.txt](https://github.com/user-attachments/files/17788577/dx_modifiers.txt)
[dx_settings.txt](https://github.com/user-attachments/files/17788578/dx_settings.txt)
[dx_values.txt](https://github.com/user-attachments/files/17788579/dx_values.txt)

**Game Information**
 - Platform: Xbox 360
 - Version: v1.1.0-beta12
 - Song Count: 4253

**Comment by jnackmclain** [comment]
update rb3e to nightly version, this isnt a dx issue
https://github.com/RBEnhanced/RB3Enhanced/actions/runs/11006681381
