### ISSUE TITLE
Drum Navigation with PS3 RB1 drums mapped to wrong functions

### ISSUE THREAD

**Issue by Soundtoxin** [hmxmilohax/rock-band-3-deluxe#920]
**Describe the bug**
Yellow/Blue pads are treated like Triangle (view more info) and Square (Review score) so I can't move through the track list without the dpad. Turning Drum Navigation off/on doesn't change behavior.

**To Reproduce**
1. Go to Play Now -> Quick Play -> Choose Songs
3. Hit Yellow or Blue and observe behavior

**Expected behavior**
Menu navigation

**DX Settings**
- `dx_settings.dta`: (rename to .txt and attach here)
- `dx_modifiers.dta`: (rename to .txt and attach here)
- `dx_values.dta`: (rename to .txt and attach here)

**Game Information**
 - Platform: PS3
 - Version: 1.1.0-beta12
 - Song Count: 290

**Additional context**
On the main menu, Yellow also acts as triangle and acts as Next Message. I have cross and circle swapped on my PS3 if that matters (so red pad to confirm in RB3).

**Comment by DarkRTA** [comment]
rb1 drums don't send all of the inputs required for drum navigation to work

you have to use the dpad unfortunately

**Comment by Soundtoxin** [comment]
I feel like this functionality is drastically more important than viewing extra song info or giving it a rating. Would love a setting to make those pads do the menu navigation instead, even if it becomes impossible to rate the song and such. Is that not possible to swap?

**Comment by DarkRTA** [comment]
It's simply not possible for us to implement this without modifying *every* single menu in the game to account for it.
