### ISSUE TITLE
List of Bugged Clothing

### ISSUE THREAD

**Issue by carlmylo** [hmxmilohax/rock-band-3-deluxe#923]
**Describe the bug**
This is a list of bugged clothing that was caused by the crossdressing clothing update.

# Masculine
### Classic Action
2 - How the Vest was Worn
3 - Like a Virgin
4 - Trail Blazer (could work???)
5 - LA Woman
6 - Simply Irrestistable
7 - Pristine Jean Jacket
8 - Hells Belle
9 - '80s Jacket
10 - MA-1 Classic Flight
11 - Defiant Leathers
12 - Lost my License
13 - Plaid Reputation
14 - Nights in Tight Satin
15 - Melancholy Prom
16 - Pro and Con Blazer
17 - You Jane
18 - Solid Bikini
19 - Suit to Thrill Blazer
20 - Worn in the USA Vest
21 - Flower Child
22 - Geometric Figures
23 - Simply Mod
24 - Maximum Mini
25 - Art School Dress
26 - Rockington Prep Uniform
27 - Achy Breaky Shirt
28 - It's Mod, Mod, Mod, Mod World
29 - Restrain-coat (could work??)
30 - Hickey Hider
31 - Dance Commander
### Artful Attire
2 - Beverly Frills
3 - Ao Dai Top
4 - Lace Trace
5 - Skull Crossed
6 - Angelic Corset
7 - Coat of Our Discontent
8 - Weepy Hollows Top (Could work???)
9 - Hell and Ready
10 - Suspension of Disbelief
11 - Mistress of the Night V-Neck
12 - Anne of Seven Gables
13 - Black Widow Cape
14 - Crimefighter Cape
15 - Cape Odd
16 - Mourning Glory Corset
17 - Annabelle Lee
### Suburban Anarchy
2 - Mesh Missiles Hoddie
3 - Hot Under the Collar
6 - Bad Reputation
7 - 300 lbs. Club
8 - Dirty Denim Jacket
9 - Catch as Catch Cannibal
10 - Frankestein's T-Shirt
11 - Rockington Reform Uniform
12 - The Right Stripes
13 - Nikola Parka
15 - GoTag Thermal
18 - A-to-Zebra Silk Top
19 - Panzer Girl
20 - Chute the Moon
21 - Punks Not Threads Top
23 - Plague Doctor (does not load)
24 - Ghost Ranchers - (does not load)
### Uninhibited
2 - Back in Straps
3 - Take a Bow
4 - Buckled Under Pressure
5 - "It's a Cinch" Top
6 - Netting But a Good Time
7 - Beatrix
8 - Not So Straitjacket
9 - Rapt and Strapped Top
10 - Love Triangle Jacket
11 - Evil Corset
12 - Right as Raincoat
13 - Chill Up Your Spine Boots (does not load)
14 - Spinap Tap Classic Logo Tee (should this be here? isn't this a premium shirt?)
15 - Bob Marley Legacy Tee (should this be here? isn't this a premium shirt?)
### Ms. Kitty 
2 - High-waisted Dress
3 - Atomic Prom
4 - Club Girl Halter
5 - C'est Chic Halter
6 - Romp Le Monde Top
7 - Sweet Cheetah
8 - Barbarian Princess
9 - Easy Tiger
10 - Lovely Assassin
11 - God Save the Queen
12 - Matadorable Jacket
13 - Par for the Corset Top
14 - Metropolicious Top
15 - Venom Vixen Top
16 - Skull Flowers
17 - Bare Your Skull (does not load)
18 - Airport Security Disaster (does not load)
19 - Glamma Bandana (does not load)
20 - Face the Tiger (does not load)
21 - Punks Not Threads Briefs (does not load)
### Modern Basics
2 - Good Gal V-neck
3 - Atom Splitter
4 - Wave Rider
5 - Cat Scan
6 - ...What a Tee-shirt!
7 - Football Jersey
8 - Winged Serpent
9 - Good Hoodie
10 - Might As Well Jumpsuit Top
11 - Starlight
12 - Lucky Star
13 - Chains of Love
14 - Melange a Trois
15 - Earn Your Stripes Top
16 - Sleeveless in Seattle
17 - Top Tank
18 - Moped Devotee
19 - Cyber Panther
20 - Therma-stat
21 - Undone Sweater
22 - Magic Tanktop Ride
### Dystopia 1996
2 - Lonely Hearts Club
3 - Apocalypse Girl
4 - Fur Elise
5 - Articulated Leather Jacket
6 - Roadstar Armor
7 - Giant Killer Armor
8 - Toci's Chest
9 - Ch-ch-chain Is
10 - Breastplate
11 - Battlefield Corset
12 - Metacular Corset
13 - Ram it Home Skull Top
14 - Wyvern Slayer Armor
15 - Spiketress Armor
16 - Titanium Maiden Armor
17 - Metal Goddess Bodice
18 - Citlalicue's Chest
### The T-Shirt Shop
2 - Trashin' Tee
3 - Open Heart Serger Tee
4 - Fender Shirt
5 - 10k Fun Run
6 - Ernie Ball Shirt
7 - Muscle Car
8 - Promark Baseball Tee
9 - American Girl
10 - Rossi's Motorcycles
11 - DW Drums Tee
12 - Electro-Harmonix Tee
13 - EMG Tee
14 - Ernie Ball Crest Tee
15 - Grestch Drums Tee
16 - Ludwig Tee
17 - Pearl Tee
18 - Nuclear Proliferation Tee
19 - Dead Ringer
20 - Sennheiser Tee
21 - Fit to be Tie-Dyed
22 - Z.Vex Tee
23 - Metallica Classic Logo Tee
24 - Guitar Tee
25 - Bass Tee
26 - Drums Tee
27 - Vox Tee
28 - Keys Tee
29 - All Four Tee
30 - The Rock Band Tee
31 - Unimpressed (does not load)
32 - Mistress Stilettos (does not load)
33 - Italian Bandana (does not load)
34 - Spiked Gauntlet (does not load)
35 - Jean Genie (does not load)
36 - The Zebra (does not load)
### Premium T-Shirts
1 - The Door Band Tee
2 - The Door Morrison Tee
3 - The Door Logo Tee
4 - Jimi Hendrix Electric Ladylan Tee
5 - Jimi Hendrix Are You Experienced Tee
6 - Jimi Hendrix Guitar Tee
7 - Jimi Hendrix Band of Gypsys Tee
8 - Jimi Hendrix Rock Pose Tee
9 - Jimi Hendrix Valley of Neptune Tee
10 - Jimi Hendrix Woodstock Tee
11 - Bob Marley Exodus Tee
12 - Bob Marley Lion Tee
13 - Bob Marley Soul Rebel Tee
14 - Bob Marley Trenchtown Tee
15 - Bob Marley Vintage Tee
16 - Spinal Tap Flame Logo Tee
17 - Spinal Tap Intravenus de Milo Tee
18 - Spinal Tap Shark Sandwich Tee
19 - Spinal Tap Skeleton Tee
20 - Spinal Tap Stongehenge Tee
21 - The Who Triumph Tee
22 - The Who Union Jack Tee
23 - The Who Rock Jump Tee
24 - The Who Maximum R&B Tee
25 - The Who Split Jump Tee
26 - The Who Target Logo Tee
### Classic Action
1 - Molly's Mini
2 - 9-to-5 Pants (could work with t-shirt??)
3 - Hip Huggers
4 - Slashers
5 - Black Leathers
6 - Bling Kitty
7 - Stretchy Leopards
8 - Suit to Thrill Slacks
9 - Worn in the USA Chaps
10 - Warrior Princess (does not load)
11 - Poleyn Leggings
12 - Lucky Stars (does not load)
13 - Stripe Tease Helmet (does not load)
14 - Checked Off Cuff (Single)
15 - Your Mama Don't Pants
16 - Skully Dornholes (does not load)
17 - Hoopdies (does not load)
18 - Stevie Knickers
19 - Casketcase (does not load)
20 - Toci's Feet (does not load)
### Artful Attire
1 - Belfrey Denim
2 - Candy Stripes Legs Micro
3 - Rebel Rebel
4 - Vinyl Maid Bare
5 - Catch o' the Day
6 - Nevermore Micro
7 - Haunt Me, Haunt Me Mini
8 - Pixie Pants
### Suburban Anarchy
1 - Twisted Barbs
2 - Hardcore Shorts
3 - Puck Tails
4 - Bling Leather Mini
5 - Body Panels
6 - Annabelle Pants
7 - Plaid Day
8 - Tartan Skirt
9 - Studcore Leather Pants
10 - Sweet & Tartans
11 - Home Wreckers
### Uninhibited
1 - Josie Wails Leggings
2 - Trussed Issues
3 - Big For Your Breeches
4 - Vinyl Maid
5 - Pants Macabre
6 - Safety Skirt
7 - Nonsense and Sensibility (could work with t-shirt??)
9 - Rubber & Glue Skirt
10 - Brief Examples
11 - Snake-Os
12 - Rapt and Strapped Bottoms
13 - Arch Villain (does not load)
14 - Citlalicue's Legs
15 - Treacherous Spikes (does not load)
16 - Poodle Skirt
17 - Tricerabottoms (does not load)
18 - Camo Cargos
### Ms. Kitty's Stagewear
1 - Botty and the Beat
2 - Venom Vixen Leggings
3 - Heartbreaker Leggings
4 - Lame Leggings
5 - Packing Heat
6 - No Regrets Fishnets
7 - Acid Flashback Leggings (could work with t-shirt???)
8 - Alphabet City Leggings
9 - Trashy Treasure Leggings
10 - Loud Leggings
11 - Matadorable Leggings
12 - Par for the Corset Bottoms
13 - Romp Le Monde Bottoms
14 - Metropolicious Bottoms
15 - Smoothies (does not load)
16 - Nose Ring (does not load)
17 - Sterling Reputation (does not load)
18 - Browbeater (does not load)
19 - Russian Bandana (does not load)
20 - Rock Candy (does not load)
### Modern Basics
1 - Skinny Jeans
2 - Sgt. Sexy
3 - Swell Bottoms
4 - Bulky Shorts
5 - Tiger Tiger
6 - Oi! Jeans!
7 - Jaunt Cargos
8 - Four Cords
9 - Frillseeker Skirt
10 - Main high Water Jeans
11 - Camo Micro Shorts
12 - Might As Well Jumpsuit Slacks
13 - Might As Well Jumpsuit Shorts
### Dystopia 1996
1 - Gam Crackers
2 - Vigilante Panties
3 - Bandito Minito
4 - Spiketress Leggings
5 - Toci's Legs
6 - Wyvern Slayer Leggings
7 - Roadster Leggings
8 - Giant Killer Leggings
9 - Titanium Maiden Leggings
10 - Utilitease
11 - Gird Up Your Loincloth
### Classic Action
2 - Understudy Boots
3 - Embroidered Western Boots
4 - Western Boots
5 - Devil's Angels
6 - Bela boots
7 - Stand & Deliver Platforms
8 - When It Rains Boots
9 - Venus in Spurs
10 - Lyrical Swans
11 - Walkin' Boots
12 - Basket Case Boots
13 - Worn in the USA Boots
14 - Kinky Boots
### Artful Attire
2 - Visigoth Treaders
3 - Infinite Boots
4 - Which Witch's Boots
5 - Mary Birds
6 - Radically '80s Boots
7 - Spiketress Boots
9 - Lenore's Heels
10 - Anne Marie (does not load)
### Suburban Anarchy
2 - Brawler Crawlers (could work with jeans)
3 - Tape Heads
4 - Combat Boots
5 - Painters
6 - Color Me Plaid
7 - Worn Dornholes
8 - Stars & Hype
9 - Dirty mouth Breathers
10 - Dee-lite dornholes
11 - Checkered Past Boots
12 - Lace Pacers
13 - Splatters 6s
14 - Goody Two Tone Boots
15 - Electro-tones
16 - Run Down
17 - 12-Hole Red Riders
18 - Motorcycle Mayhem Boots
19 - Teenage Kicks
20 - Plaid Reputation Boots
21 - Flag Day Boots
22 - Punks Not Threads Feet
24 - Ankhlettes (does not load)
### Uninhibited
2 - Slouchy Stirrup Boots
3 - Nightmare Cowboy
4 - Strap and Spike Heels
5 - Safety Straps
6 - Nine Inch Heels
7 - Motorcycle Mama
8 - Wake Me Up Before You Go Gos
9 - Sky High Thigh Highs
### Ms. Kitty's Stagewear
2 - Bont Laarzen
3 - Platform Anklysaurs
4 - Sickness and Pedicure Heels
5 - Go Tiger!
6 - Maid Marion Boots
7 - Luchador Boots
8 - 22-Hole Glossy Leather Boots
### Modern Basics
2 - Folded Dornholes
3 - Skullduggery Sneakers
4 - Prisoner of Roar Sneakers
5 - Striped Dornholes
6 - Marimbas
7 - Mercuries
8 - Basketball Trainers
9 - 9-to-5 Heels
10 - Low Skool Kicks
11 - Skandalous Slip-ons
12 - Sneaker Boots
13 - Leopard Skin Ultratops
14 - Back in the Saddle w/ Ankle Socks
15 - Back in Saddle Shoes
16 - Back in the Saddle w/ Knee Socks
17 - The Wide Stripes
18 - Wellies
19 - Union Bikini (does not load)
### Dystopia 1996
3 - Butane Jane
4 - Plate Metal Boots
6 - Metal Plate
7 - Thunder Dome Power Stompers
8 - Wyvern Slayer Boots
9 - Roadster Boots
10 - Giant Killer Boots
11 - Titanium Sabatons
12 - Citlalicue's Feet
14 - Miss Force Patrol Boots
## Hats
2 - Pardon Your French w/ Long Hair (could work???)
3 - Pardon Your French w/ Short Hair
4 - Pardon Your French
5 - Biker Cap
6 - Urban Cowboy
8 - Fab Fedora
9 - Suburban Gangster
10 - Mourning Glory Veil
11 - Lolita Hat
12 - Chairman's Cap
13 - Tough Girl
14 - Metal Outlaw w/ Long Hair
15 - Metal Outlaw w/ Short Hair
16 - Head-turning Headdress
17 - Hell on Wheels
18 - Give 'Em Helmet
19 - Speed Demon
20 - Worn in the USA Helmet
21 - Pickelhaube
22 - Friendly Skies Cap
23 - Knock 'Em Dreads
24 - Rasta Mama (could work???)
25 - Top Hat
27 - Super Visor
28 - Holy Bowler
29 - Holy Bowler w/ Short Hair
31 - Wall Flowered (does not load)
32 - Friend or Faux (does not load)
33 - Venus Fly Trap (does not load)
34 - Your Pleatin' Heart (does not load)
## Earrings
2-16 are duplicates
## Piercings
2-9 are duplicates
## Glasses and Masks
Everything from 1-33 are duplicates
## Bandanas
1-15 are duplicates
## Wrists
2-26 are duplicates
## Gloves
2-8 are duplicates
## Rings
2-16 are duplicates
## Hair
2 - Curtained
3 - The Jacqueline
4 - The Betty
5 - Dolled Up
6 - Princess Player
7 - Little Pigtails
8 - Emo Philia
9 - ...And You Will Know Us by the Tail of Dreads
10 - Angel Wings
11 - Feathered
12 - Femover
13 - The Flapper
14 - Dread Falls
15 - Hippie Bangs
16 - Hairajuku
19 - Layered
20 - Punked Out
21 - Long Hair
22 - Long and Straight
23 - Long and Wavy
24 - Casual Hipster
25 - Hot Mes
26 - Lady Valiant
27 - Thingama Bob
28 - Long Pingtails
29 - The Pixie
30 - Reverse Flip
31 - Shaggy Hair
32 - Chopped-Off
33 - Pageboy
34 - Short Spikes
35 - Asymmetrical Bob
36 - Side Ponytail
37 - The Joan
38 - Contrast Fringe
39 - Trihawk
40 - Lolita
41 - Pulled Back
42 - Retro Pony
43 - Nightcat
44 - Beehive
45 - Free Locks
46 - Puck It Up
## Eyebrows
2-15 are duplicates. It is best to remove these.
## Facial Hair
2-20 do not work. It is best to remove these.
## Face Paint
N/A
## Eye Makeup
Everything works!
## Lip Makeup
Everything works!

# Feminine
## Torso
- Denim Demon 
- Rebel without Applause
- Chest for Success
- The Floridian (?)
- Modern Lover
- Highland Ruffles
- Fringe Benefit
- Viva las Vegas
- Doctor What
- Roadie Jacket
- Deliverie Dude
- Vintage Vest with Tee
- Arena Rocker
- Working Classy (?)
- Pump Jockey (?)
- Barrio Lothario
- Lax Rebel Motorcyle Club	
- Vested Interest
- Baja Poncho (it looks buggy asf but its also funny lmao)
- Professor
- Vintage Blazer and Tie
- Rhinestone Cowboy Jacket
- Smoking Jacket
- Sharkskin Suit
- Jimmy's Coat
- Heart of Morocco
- If you dont nomi by now
- Messers Spekyll and Ryde Shirt
- The Libertine
- Complex Napoleon Jacket (?)
- Spider-Silk Capelet
- Libertinette
- Dr. Acula Cape
- Kill' Em Shakespeare Blouse
- Modest Blouse
- Dr. Acula Lab Coat
- Cape Odd
- Drums Tee
- He Shred, She Shred
- AF Shirt
- Camoflange
- Thunder Road
- DIY Vest
- Bicep Brandisher
- Ripped Tee
- Rat Bastard Hoodie
- Cougar Army
- Military Issue
- Dystopia Vest
- Mod Winter Parka
- Blazed Out
- Spiked Twilight
- Junk Pile Argyle
- Underclass Reject
- Escape Artist
- Fashionable But Irrational
- Sonic Superstate Spikes
- Troll Vest
- Zoom Rugby
- Beau Filet
- Hafta Halfshirt
- Truss-Tee
- Slasher
- Cuffed and Collared
- Bondage Scout Uniform
- "Faux Certain" Vest
- Arockalypse Now
- Harford Harness
- O Is Me Hoodie
- On The Ropes
- Metal Demon Shirt
- Floral Values
- Polyester Inferno
- Prince of Parties
- Dressed and Confused
- Misty Mountain Top
- Medallion Stallion
- Continental Kimono
- Macho Man
- Pectacular Top
- Wrestler Tank
- Braced for a Fight
- Baton Jacket
- Glutton of Privilage
- Mr. Zebra
- Good Hoodie
- Flannel Ledbetter (?)
- Ludwig Hoodie
- Good Guy V-Neck
- Alabama Slamma Button-down
- Chambre Shirt
- Triple Fat Moose Vet
- Strummer Studs
- Witticism
- Stockholm COA 
- Brokeback Jacket
- Skully  Sleeveless
- Stella Singlet
- Biohazard Boybeater
- Sleeve it Alone 
- The Amateur Deejay
- Varsity Jacket
- Shoot the Runner Track Jacket
- The Outdoorsman
- Apocophile Leathers
- Vest Behavior
- Brooklyn Vest
- Shoulder the Burden Armor
- God of Latex Attire
- Okiro Armor
- Belt of the Usurper
- Lawless Pauldrons
- Arena Master
- Metal to the Bone
- Beast of Burden Tunic
- Return of the Mackinaw
- Dragon Lord's Armor
- Summoner's Robe
- Junkyard Gladiator
- Heart of Bone
- Favorite Cotton Tee
- Toxic Tee
- Where Eagles Dare
- Death Metal Tee
- The Dragonslayer
- DW Wings Tee
- Electro Harmonix Tee
- EMG Tee
- Ernie Ball Shirt
- Watercolor Fantasy
- Ludwig Tee
- Mount Chiller
- Pearl Tee
- Ring Tone
- Solitary
- Fit to be Tie-Dyed
- High School Wrestling
- Z.Vex Tee
- Vintage Rock Tee
- Ernie Ball Tank
- Zildjian Tank
- Long and Short Tee
- Aussie Kangaroo
- DW Shirt
- Gretsch Drums Shirt
- Promark Shirt
- Metallica Classic Logo
- Negative Union
- Guitar Tee
- The Doors Band Tee
- The Doors Morrison Tee
- The Doors Logo Tee
- Jimi Hendrix Electric Ladyland Tee
- Jimi Hendrix Are you Experienced Tee
- Jimi Hendrix Guitar Tee
- Jimi Hendrix Band of Gypsys Tee
- Jimi Hendrix Rock Pose Tee
- Jimi Hendrix Valley of Neptune Tee
- Jimi Hendrix Woodstock Tee
- Bob Marley Exodus Tee
- Bob Marley Legacy Tee
- Bob Marley Lion Tee
- Bob Marley Soul Rebel Tee
- Bob Marley Trenchdown Tee
- Bob Marley Vintage Tee
- Spinal Tap Flame Logo Tee
- Spinal Tap Intravenus de Milo Tee
- Spinal Tap Classic Logo Tee
- Spinal Tap Shark Sandwich Tee
- Spinal Tap Skeleton Tee
- Spinal Tap Stonehenge Tee
- The Woo Triumph Tee
- The Who Union Jack Tee
- The Who Rock Jump Tee
- The Who Maximum R&B Tee
- The Who Split Jump Tee
- The Who Target Logo Tee

## Legs
- Shorts Pants o Mine
- Dolltree Pinstripes
- Twice Shy Pants
- Ura-Hara Camos
- Neoplastic Sarcastic Jeans
- Molotov Long Shorts
- Graveyard Issue
- Wreckless Pants
- Shredded Shredders
- Ready, Shreaddy, Go 
- DIY Nightmare
- Punk and Disorderly Brief
- Kohl Black Denim
- Star Knight Breeches
- Pop Gothic Pants
- Graver Spacials
- Leather and Mace
- Safety Pants
- Proper Jodhpurs
- Leggings of the Beast
- ¡Toro! Trousers
- Eternal Glamnation Pants
- Pants of the Magic-User
- Hamhuggers
- Worn Cords
- Classic Cut-offs
- Dectwerk
- Floral Boardies
- Bitchin' Boardies
- Truculent Pants
- Hopeless Animal Jeans
- St. Monday's
- Dolltree Leisure Pants
- Forbidden Lover Briefs
- Gladiatorial Combat Leggings
- Kilty as Charged
- Beast of Burden Pants
- Hanzo Leathers
  
## Feet
- Scouser Boots
- Embroided Western Boots
- Ghost Ranchers
- Western Boots
- Velouraptors
- Burn Higher Boots
- Buckle Down Boots
- Devils Angels
- Fab Harness Boots
- Combat Boots
- Wango Tango Shoes
- Dr. Acula Orthopedics
- Future Perfect
- Visigothic Treaders
- Feelin Low Hightops
- Detonators
- Jack Spats
- Nightmare Cowboy
- Buccaneer Booties
- Boot Lined Boots
- Crap Kickers
- Painters
- Color Me Plaid
- Chain Link Boots
- Worn Dornholes
- Stars and Hype
- Dirty Mouth Breathers
- Dee-lites
- Checkered past Boots
- Smoothies
- Electro-tones
- Motorcyle Mayhem Boots
- Lace Pacers
- Splatter 6s
- Teddy Boy Boots
- Melancholy Calf Embracers
- Things
- Plate Metal Boots
- Thunder Dome Battle Boots
- Tommy Stompers
- Das Boots
- 22-Hole Glossy Leather Boots
- No. Thirteens
- I Would Die 4 Shoes
- Dressed to Kill Boots
- Custom Kicks
- Hightops Dornholes
- Star Jumps
- Sporty Sneakers
- N Bucks
- War Club Boots
- Stompinwolf
- Butane Jone
- Roadstar Boots
- Concrete Jungle
- Bone Kickers
- Bont Laarzen
- American Heroes
- Tricerabottoms
- Thunder Dome Power Stompers
- Knights of the metal republic
- Beast of Burden Boots

## Hats
- Aviator Cap
- Biker Cap 
- Wool Bully Cap
- Urban Cowboy
- Knit Cap
- The Humphery
- Hell on Wheels
- G.I. Cap
- Bryn Bonnet
- Newsie
- Give 'Em Helmet
- Super Visor w/ Short Hair
- Readneck
- Backwards Irony Cap
- The Bad Guy
- You and What Army Helmet

## Piercings
- Septum Ring
- Pierce Pressure
- Brow Barbell
- Acting Out
- Needles and Pins
- Masochist
- Symmetrical
- Airport Security Disaster

## Glasses (Most of these are quite bigger but they still look good,so there are a few bad)
- Black Masquerade
- Hockey Mask
- Deft Leopard
- Face of the Tiger
- Unknown Stranger
- Horse with No Name
- The Zebra
- Oi! Oi! Oink!
- Plague Doctor
- Numb Skull
- Sugar Skull
- Fandango Skull
- Day of the Dead
- Jumpin' Flak Mask
- Spiked Gas Mask
  
## Bandanas
- Ragin' Contagion
  
## Wrists
- Perspicacity (Single)
- Perspicacity 
- Wristwarmer (Single)
- Wristwarmers
- Sweatband Collector
- Perspiration & Pyramids
- Sweat & Spikes
- Stripy Wristwarmer
- Devil's Rope (single)
- Devil's Rope Bracelets
- Checked Off Cuff (Single)
- Checked Off Cuffs
- Hero's Cuff (Single)
- Hero's Cuffs
- Laced Down
- Buried in Leather
- Studded Gauntlets(Single)
- Studded Gauntlets 
- Good Time (Single)
- Good Times
- Brad the Impaler Gauntlet
- Buckled Gauntlet (Single)
- Buckled Gauntlets
- Spiked Gauntlet
- Cast-anova
  
## Gloves
- [None]
- Hands in Gloves
- Cotton Gloves
- Palm Warmers
- Driving Gloves
- Skelly Gloves
- Mummy Hands Wraps
- Whole Lotta Gloves
  
## Hairs
- Totally Generic
- Bald Eagle
- Bed Head
- Short Punk
- Buzz Cut
- ...And You Will Know Us By The Tail of Dreads
- Emo Philia
- Fauxhawk
- Feathered
- The Natural
- Afro
- Dapper Dan (Left Part)
- Dapper Dan (Right Part)
- Glamtastic
- The Pompadour
- Greaser
- Long Hair
- Long and Layered
- Boy Toy
- Long and Wavy
- Messy Mop
- Classic Mop
- Power Mullet
- Pretty Boy
- Most Likely to Recede
- Long Twists
- Shaggy Hair
- Curls Just Wanna Have Fun
- Shorts Sipkes
- Better Off Dreads
- Curtained
- Ziggy's Mullet
- Hair Metal
- Hanoi Locks
- Lazyhawk
- Crazyhawk
- Mohawk
- Squeeb
- The Quill Pig
- Mandana
- Nightcat
- Stray Dog
- Robin Badfellow

## Doesn't Load
- Studly Suspenders
- Going Ballistic Vest
- Mighty Mercury's
- Luchador Boots
- Eternal Glamnation Top
- Chopper
- Charles The Bloody
- Long Goatee

**Comment by jnackmclain** [comment]
thank you for the list it was very helpful. I am likely bound to miss something, so a double check would be appreciated, but, fixed.
