### ISSUE TITLE
Note Streak and Overdrive Ready pop-ups don't work

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#928]
that

**Comment by jnackmclain** [comment]
what?
![image](https://github.com/user-attachments/assets/6dc3862b-f25c-4d69-a6aa-e899a1ec4dc8)
![image](https://github.com/user-attachments/assets/dcb0ee30-8c73-48a4-9dbc-e61e429337a2)
![image](https://github.com/user-attachments/assets/548b2929-624d-439e-9967-b5678d671c9a)

**Comment by lunalawl** [comment]
https://youtu.be/8YJmE2uQM3Q

**Comment by jnackmclain** [comment]
post your dx settings. i just tried the same song and it was fine

**Comment by jnackmclain** [comment]
something something issue template

**Comment by lunalawl** [comment]
waht is Issue Template
[dx_settings.txt](https://github.com/user-attachments/files/17895500/dx_settings.txt)

this is 360 btw

**Comment by jnackmclain** [comment]
fixed
