### ISSUE TITLE
Tour/RC Spades cover difficulty rings on results screen

### ISSUE THREAD

**Issue by qfoxb** [hmxmilohax/rock-band-3-deluxe#932]
**Describe the bug**
When beating a song in road challenge/tour mode, the spades in the results screen cover the difficulty rings

**To Reproduce**
1. Beat a song on tour/RC mode
2. Issue occurs

**Expected behavior**
Difficulty rings to not appear, or to be repositioned somewhere else on the screen
**Screenshots**
![image](https://github.com/user-attachments/assets/a14239e7-5e39-456f-ad4b-fa66d1768ec0)

**Game Information**
 - Platform: Xbox 360
 - Version: 2f572c7f9
 - Song Count: 4196

**Comment by jnackmclain** [comment]
fixed in latest dev (now diffs will only show in quickplay)
