### ISSUE TITLE
[PS3] Play a Show's "Refresh Options" is busted

### ISSUE THREAD

**Issue by SonicSBL** [hmxmilohax/rock-band-3-deluxe#934]
**Describe the bug**
In Play a Show, selecting "Refresh Options" makes the menu hang, and the options don't refresh. Then you're stuck there and have to leave the mode.

**To Reproduce**
1. Go to Play a Show.
2. Play an opener and continue to the voting screen.
3. Select "Refresh Options" (in multiplayer, have everyone pick it).
4. The game might lock in the option, but then nothing happens.

**Expected behavior**
The options should change after a countdown.

**Screenshots**
N/A

**DX Settings**
- [dx_settings.txt](https://github.com/user-attachments/files/17910028/dx_settings.txt)
- [dx_modifiers.txt](https://github.com/user-attachments/files/17910030/dx_modifiers.txt)
- [dx_values.txt](https://github.com/user-attachments/files/17910032/dx_values.txt)

**Game Information**
 - Platform: PS3 with CFW
 - Version: latest nightly
 - Song Count: 708

**Additional context**
When I exited and re-entered Play a Show, the game crashed. I've also tried picking a different option after "Refresh" in the past, and nothing happened (that was several months ago now).

**Comment by jnackmclain** [comment]
cannot reproduce, it may take a while depending on different factors, but refresh options def works on hardware
