### ISSUE TITLE
(RPCS3) "Perfect" Text Lingers for a bit too long

### ISSUE THREAD

**Issue by WarGod480** [hmxmilohax/rock-band-3-deluxe#941]
**Describe the bug**
When playing a note "Perfectly", followed up by missing the next note by a bit ("Great" or "Good") the Perfect text freezes at a state before the note gets hit (im sorry i cant explain stuff)

**To Reproduce**
1. Play a song
2. Get a Perfect, then don't get a Perfect
3. Observe
4. Profit

**Expected behavior**
The text should fade away naturally if you dont hit a perfect

**Videos**

https://github.com/user-attachments/assets/4db6fda9-d112-420c-8109-8ef96dd2f56a

**DX Settings**
- `dx_settings.dta`: [dx_settings.txt](https://github.com/user-attachments/files/17936859/dx_settings.txt)
- `dx_modifiers.dta`: [dx_modifiers.txt](https://github.com/user-attachments/files/17936861/dx_modifiers.txt)
- `dx_values.dta`: [dx_values.txt](https://github.com/user-attachments/files/17936862/dx_values.txt)

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-nightly+4f2f271
 - Song Count: 6162

**Comment by jnackmclain** [comment]
(probably) fixed in latest dev
