### ISSUE TITLE
Guitar FX box not appearing

### ISSUE THREAD

**Issue by SonicSBL** [hmxmilohax/rock-band-3-deluxe#950]
**Describe the bug**
When using a guitar controller with an effects switch, moving the switch doesn't bring up the box of effects.

**To Reproduce**
1. Go to Quickplay with a guitar controller that has an effects switch (e.g. the RB2 Strat).
2. Pick a song.
3. Scroll to "Guitar" and pick a difficulty.
4. Move the FX switch to another position.
5. The effect changes during solos/overdrive as always, but no box appears.

**Expected behavior**
The effects box appears above the track with the current effect highlighted.

**Screenshots**
N/A

**DX Settings**
- [dx_settings.txt](https://github.com/user-attachments/files/17971187/dx_settings.txt)
- [dx_modifiers.txt](https://github.com/user-attachments/files/17971190/dx_modifiers.txt)
- [dx_values.txt](https://github.com/user-attachments/files/17971191/dx_values.txt)

**Game Information**
 - Platform: PS3 with CFW
 - Version: 1.1.0-nightly+3df19b5 (latest)
 - Song Count: 708

**Additional context**
Bass is unaffected.

**Comment by jnackmclain** [comment]
Use latest nightly and set the guitar fx to "nothing"
