### ISSUE TITLE
Song title Alignment does not persist between reboots (nightly) 

### ISSUE THREAD

**Issue by Cobalto-Sketcherino** [hmxmilohax/rock-band-3-deluxe#958]
**Describe the bug**
Changing the alignment of the text for the 'Song Title' options does not persist between reboots of the game.

**To Reproduce**
1. Set 'alignment' for the song title using the text options submenu, to right-justified
2. reboot the game
3. Find that text alignment has reverted to left-justified

**Expected behavior**
Have text alignment be retained across reboots, as position and other factors are.

**DX Settings**
- `dx_settings.dta`:
[dx_settings.txt](https://github.com/user-attachments/files/18045279/dx_settings.txt)

- `dx_modifiers.dta`: 
[dx_modifiers.txt](https://github.com/user-attachments/files/18045280/dx_modifiers.txt)

- `dx_values.dta`:
[dx_values.txt](https://github.com/user-attachments/files/18045281/dx_values.txt)

**Game Information**
 - Platform: Xbox 360 (real hardware)
 - Version: RB3DX 1.1.0-nightly+6a60e3b
 - Song Count: 4040 (out of 4042, for some reason)

**Additional context**
apparently this can just be "hey jnack you don’t save mtv position values you dummy”.
Personally, I don't believe Jnack should berate themselves for a simple mistake.

**Comment by jnackmclain** [comment]
fixed in latest nightly
