### ISSUE TITLE
Keys version crashes on RPCS3 since refactoring merge

### ISSUE THREAD

**Issue by ghost** [hmxmilohax/rock-band-3-deluxe#96]
I downloaded the latest keys version from the actions build an also built it locally, and they both crash while RB3 shows the "Loading new downloaded content" progress bar.

If I use the package from action #400 (https://github.com/hmxmilohax/rock-band-3-deluxe/actions/runs/4030283273) or build the keys version from that commit locally, the game runs normally.

It also works if I remove all my DLC. I only have Rock Band and Guitar Hero Exports I downloaded from the songs spreadsheet (https://docs.google.com/spreadsheets/d/1-3lo2ASxM-3yVr_JH14F7-Lc1v2_FcS5Rv_yDCANEmk/edit#gid=0)

**Comment by rjkiv** [comment]
I've identified the error, give me some time to push out a fix

**Comment by rjkiv** [comment]
Should be fixed now - select the latest keys build and give it a try

**Comment by ghost** [comment]
It's working now. Thank you!
