### ISSUE TITLE
is there a way to change the Menu Screen?

### ISSUE THREAD

**Issue by ghost** [hmxmilohax/rock-band-3-deluxe#98]
So,i recently updated RB3DX after a long time and theres a new menu screen that has a LOT fps issues,and i was wondering if there's a way to change to the other ones where your characters appears (since thos didnt gave me any fps issues)

**Comment by lunalawl** [comment]
_ark\ui\init.dta

**Comment by jnackmclain** [comment]
^

**Comment by jnackmclain** [comment]
(sv_number)

**Comment by ghost** [comment]
Thanks!
but if is not bad to ask how do that,like,i just saw the file but how do i include it to the game now?

**Comment by lunalawl** [comment]
rebuild your ark
