### ISSUE TITLE
Pad Mode in this DX?

### ISSUE THREAD

**Issue by AlissaWhoops** [hmxmilohax/rock-band-3-deluxe#99]
There are gonna be Plans to add a Pad mode in this deluxe version?
(sorry if this its not good my english its not too good XD)

**Comment by jnackmclain** [comment]
there already is pad mode. you can select any instrument from vocals

**Comment by AlissaWhoops** [comment]
> there already is pad mode. you can select any instrument from vocals

oh thanks! :)
also,is there a way to unlock all the clothes? because there are a few that are behind a Pro Instrument and well,i dont have it lol XD

**Comment by HideriFN** [comment]
About pad mode, is this thing work with multiple gamepad? Or maybe only detecting 1 gamepad? Because we want to play with friends/other people (Sorry for bad english, not my native language)
